### PR TITLE
Add Mailcow (Formelly Fufix)

### PR DESCRIPTION
**Pull request by joubertredrat**
Mail server suite based on Dovecot, Postfix and other open source software, that provides a modern Web UI for administration.

### CODE REVIEW

**Comment by nodiscc** [comment]
@joubertredrat @Kickball this was already in https://github.com/Kickball/awesome-selfhosted#email , so this is a duplicate. Should we also move Modoboa and Mail-in-a-box to the `Mail` section?

**Comment by Kickball** [comment]
@nodiscc I think if they provide more than just email then they should be in the Self-hosting Solutions or Groupware sections.

**Comment by nodiscc** [comment]
@Kickball ok, then let's remove the mailcow entry in the `Mail` section. We can also add a link at the top of the section:

For preconfigured mail server solutions, see [Self-hosting Solutions](#self-hosting-solutions)

**Comment by Kickball** [comment]
That seems like the best way of doing it.

**Pull request merged**
