### PR TITLE
SharpPaste: added link to demo.

### PR DESCRIPTION
**Pull request by phonicmouse**
I added the demo link to my software. 👍

### CODE REVIEW

**Comment by danger-awesome-Selfhosted** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please update the Pull Request title to contain the script name</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Found 1 link issue</td>
    </tr>
  </tbody>
</table>

#### Link issue by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
2 | Error | https://sharppaste.nl/ <br> SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by phonicmouse** [comment]
Why that says the link is not ok? The site is perfectly working.

**Comment by nodiscc** [comment]
It is working but your TLS configuration is using TLS_RSA_WITH_AES_CBC_SHA 128 bits cipher which is insecure -  Firefox 52 also shows the connection as insecure.

tls

By the way your server also discloses pretty sensitive information in it's HTTP headers:

```
Server: Mono.WebServer.XSP/4.2.0.0 Linux
X-AspNet-Version: 4.0.30319
```

Unfortunately I am not familiar with this server so I can't help you much, but it should be a matter of configuration. Here are some known secure cipher configurations for web servers: https://cipherli.st/


> The site is perfectly working.

So I'd say it is working, but not perfectly :)

I see no problem in merging your changes.

**Comment by phonicmouse** [comment]
@nodiscc Thanks for your reply. That's really strange as my chrome says everything is ok as you can see:
cattura
Anyway...I'll configure it better. I know how to do that, the only problem is that I didn't noticed this problem as my browser hadn't said anything. Anyway thanks for the advice.
This is what happens when you host an ASP.NET app on a linux host LOL.

**Comment by phonicmouse** [comment]
I just fixed the problem with the server. Now everything should be ok. ;)

**Pull request merged**
