### PR TITLE
Add FaaS / Servless section

### PR DESCRIPTION
**Pull request by jacksgt**
Hi,

I added a section about Functions as a Service (FaaS) / Serverless selfhosting solutions,
as it doesn't exist in awesome-sysadmin / awesome-selfhosted yet.

### CODE REVIEW

**Comment by evaryont** [comment]
This is a hard one to immediately approve -- does it belong in awsome-sysadmin or awesome-selfhosted? At first blush, to me, it's a very developer centric tool and has no out of the box usefulness to non-tech people, so I'd recommend putting it in awesome-sysadmin. Not sure though.

**Comment by jacksgt** [comment]
@evaryont I agree with you, this is a difficult call between awesome-sysadmin and awesome-selfhosted. But that also applies to quite a few other categories, and in the end sysadmins are just "selfhosters".

Anyway, but OpenFaaS and [IronFunctions](https://github.com/iron-io/functions-ui) definitely offer GUIs:
OpenFaaS GUI
IronFunctions UI

**Comment by jacksgt** [comment]
@nodiscc Done.

**Comment by jacksgt** [comment]
Ping @nodiscc

**Comment by jacksgt** [comment]
Thanks for merging!

**Pull request merged**
