### PR TITLE
Combined pull request for #1201, #1251, #1254, and #1268.

### PR DESCRIPTION
**Pull request by meitar**
Thank you for taking the time to work on a PR for Awesome-Selfhosted!

To ensure your PR is dealt with swiftly please check the following:

- [x] Your submissions are formatted according to the guidelines. 
        
    ``[Name](http://homepage/) - Short description. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code)) `License` `Language` ``

- [x] Your additions are ordered alphabetically.
- [x] Your additions are [Free software](https://en.wikipedia.org/wiki/Free_software), or if not they have been added to [non-free](non-free.md).
- [x] Your additions are not already listed at [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin) (IT infrastructure management), [staticgen.com](https://www.staticgen.com/) or [staticsitegenerators.net](https://staticsitegenerators.net/) (static site generators).
- [x] Any licenses you have added are in our [list of licenses](https://github.com/Kickball/awesome-selfhosted/blob/master/README.md#list-of-licenses).
- [x] You have searched the repository for any relevant issues or PRs.
- [x] Any category you are creating has the minimum requirement of 3 items.

### CODE REVIEW

**Comment by danger-awesome-Selfhosted** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Found 65 link issues</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
93 | Dupe | http://www.alltubedownload.net 
120 | Dupe | https://github.com/jchampemont/WTFDYUM 
125 | Error | http://demo-bludit.rhcloud.com/ <br> getaddrinfo: Name or service not known
131 | Error | https://hotglue.me/ <br> SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
131 | Error | https://hotglue.me/demo/ <br> SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
138 | Dupe | https://wordpress.org/ 
138 | Dupe | https://github.com/WordPress/WordPress 
141 | Dupe | https://docs.services.mozilla.com/howtos/run-fxa.html 
148 | [530](https://httpstatuses.com/530) | https://save.duyet.net/ 
183 | Error | http://niltalk.com/ <br> Connection timed out - connect(2) for "niltalk.com" port 80
210 | Dupe | https://github.com/atech/postal 
275 | Error | https://jappix.com/ <br> hostname "jappix.com" does not match the server certificate
288 | [503](https://httpstatuses.com/503) | http://www.telescopeapp.org/ 
384 | Dupe | https://github.com/janeczku/calibre-web 
385 | Error | https://blog.slucas.fr/en/oss/calibre-opds-php-server <br> SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
423 | [502](https://httpstatuses.com/502) | https://winds.getstream.io/ 
444 | [502](https://httpstatuses.com/502) | http://erdgeist.org/gitweb/opentracker/ 
456 | [403](https://httpstatuses.com/403) | http://jirafeau.net/ 
461 | Dupe | https://github.com/ethanal/nimbus 
463 | Dupe | https://www.pictshare.net/ 
478 | Dupe | https://github.com/soyuka/explorer 
479 | Error | https://extplorer.net/projects/extplorer/repository <br> hostname "extplorer.net" does not match the server certificate
479 | Error | https://extplorer.net/ <br> hostname "extplorer.net" does not match the server certificate
481 | Dupe | https://github.com/xataz/gobrowser 
484 | [403](https://httpstatuses.com/403) | http://mftp.live/ 
496 | Error | https://posio.abrenaut.com/ <br> Net::ReadTimeout
511 | Error | http://demo.mayan-edms.com <br> getaddrinfo: Name or service not known
522 | Dupe | https://www.edx.org/ 
543 | [500](https://httpstatuses.com/500) | https://gnu.io/fm/ 
545 | Dupe | http://www.icecast.org/ 
545 | Dupe | https://git.xiph.org/?p=icecast-server.git;a=summary 
555 | Error | https://darncoyotes.mstream.io/ <br> SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
578 | Error | https://www.crushpaper.com/ <br> SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
587 | Error | https://projects.miguelpiedrafita.com/LicAPI <br> getaddrinfo: No address associated with hostname
593 | Error | https://notica.us <br> SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
602 | [530](https://httpstatuses.com/530) | https://www.budgetapp.io/ 
611 | Error | https://www.invoiceninja.org/ <br> SSL_connect SYSCALL returned=5 errno=0 state=SSLv3 read server session ticket A
612 | [500](https://httpstatuses.com/500) | https://invoiceplane.com/ 
638 | Error | http://onlyoffice.org/ <br> bad URI(is not URI?): https:\\www.onlyoffice.com
639 | [404](https://httpstatuses.com/404) | http://phpoffice.github.io/ 
656 | Dupe | https://notehub.org 
664 | Error | https://sharppaste.nl/ <br> Cannot assign requested address - connect(2) for "sharppaste.nl" port 443
679 | Error | https://thingsboard.io/ <br> SSL_connect SYSCALL returned=5 errno=0 state=SSLv3 read server session ticket A
701 | Dupe | http://calagator.org/ 
706 | [404](https://httpstatuses.com/404) | http://kyela.net/55232734237c8/ 
708 | Dupe | https://github.com/nearbycoder/materialpoll 
714 | Dupe | https://github.com/thekvs/microproxy 
715 | Dupe | https://github.com/joshdick/miniProxy/ 
718 | Dupe | http://www.apsis.ch/pound/ 
726 | Dupe | http://www.gigablast.com/ 
749 | Error | http://demo.redmine.org/ <br> Connection timed out - connect(2) for "demo.redmine.org" port 80
749 | Error | http://www.redmine.org/ <br> Connection timed out - connect(2) for "www.redmine.org" port 80
749 | Error | https://svn.redmine.org/redmine/ <br> Connection timed out - connect(2) for "svn.redmine.org" port 443
753 | Dupe | https://github.com/thebuggenie/thebuggenie 
762 | Dupe | http://micro.glark.io 
799 | Error | http://demo.taskfreak.com/ <br> getaddrinfo: Name or service not known
800 | Error | https://projects.miguelpiedrafita.com/Tasks/ <br> getaddrinfo: No address associated with hostname
800 | Error | https://demo.miguelpiedrafita.com/tasks/ <br> getaddrinfo: No address associated with hostname
828 | [521](https://httpstatuses.com/521) | https://project.polr.me/ 
840 | Dupe | https://github.com/claudioc/jingo 
850 | [404](https://httpstatuses.com/404) | https://sourceforge.net/p/tikiwiki/code/HEAD/tree/ 
865 | Dupe | http://puffin.rocks/ 
881 | Dupe | https://opensource.org/licenses/BSD-3-Clause 
895 | Error | https://www.isc.org/downloads/software-support-policy/isc-license/ <br> Cannot assign requested address - connect(2) for "www.isc.org" port 443
908 | Error | https://chat.awesome-selfhosted.com <br> getaddrinfo: Name or service not known


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by nodiscc** [comment]
@meitar Thanks, really appreciated, I'd suggest a different approach though;  can you split your patch into commits that

1. make it manageable to review (I've tried to review the whole PR, then your 4 commits separately, it's extremely hard)
2. pass the tests. I know the duplicate/broken links warnings are there because these entries had problems *before* your patch, but we should strive to make the tests pass otherwise we're just sweeping this under the rug and we're never going to fix it.

Where I'd start:
 * Move https://github.com/Kickball/awesome-selfhosted/pull/1269/commits/962b467d5ffab7be96126ea3c67ee6df69abb3f4 and https://github.com/Kickball/awesome-selfhosted/pull/1269/commits/85be66fb37bb6ea9cc8fc167b9a611b90848fcaa to separate PRs so we can merge them right away.
 * Start indentation cleanup with a single section (eg. _Enterprise Resource Planning_), and fix the danger warnings in the same time. The tests should pass.
 * Do the batch license renaming in a separate PR. The tests should pass.

Again, I really appreciate the time you put in your work, the commit messages are nice, etc, but from a maintenance perspective we should take the time to do it really clean.

If other contributors want to fix a section of their choice, please send a PR (and/or coordinate your work here or in https://github.com/Kickball/awesome-selfhosted/issues/1201).

**Comment by meitar** [comment]
> I know the duplicate/broken links warnings are there because these entries had problems before your patch, but we should strive to make the tests pass otherwise we're just sweeping this under the rug and we're never going to fix it.

Respectfully, the purpose of this cleanup is to make it easier to do exactly that; by working on one *issue* instead of one *section* at a time, you can close open issues. Moreover, that work has now actually been done.

As you say, the tests were failing before and still will be failing in the exact same way after this merge, so it's six of one or half-dozen of another. From the looks of it, this has been "swept under the rug" for a while already, except now you have an opportunity to close #1201 immediately; so the choice that the "merge" button represents seems to be between having failing tests and keeping #1201 in an incomplete state (open) versus having failing tests and getting to see #1201 get immediately closed. When things like indentation and what not is inconsistent, it is much more confusing for a contributor unfamiliar with the project to add to it, meaning you'll be cleaning up patches that are inconsistent in thi ls way for longer, too.

Further, I don't know when or if I'll have the time to do this again in piecemeal fashion, so I probably won't. I am sorry. :(

**Comment by nodiscc** [comment]
I understand, I'll find a way to split your PR into reviewable units (proper use of git command line should do the trick, and a good learning opportunity). Let's forget about fixing the links for the time being. Don't worry, it's not wasted work, and I will preserve commit authorship.

**Comment by nodiscc** [comment]
Split into multiple PRs, reviewed separately using command line git (Github diffs have limitations on word diff), merged. Thanks again.

**Pull request merged**
