### PR TITLE
Added PHP QR Code

### PR DESCRIPTION
**Pull request by Ober7**

### CODE REVIEW

**Comment by AndyR207** [comment]
Looks good to me.

**Comment by nodiscc** [comment]
I think this should be removed. It's a library, not a web application. ping @Kickball @AndyR207

**Comment by Kickball** [comment]
Yeah I think @nodiscc is right. We should remove this as it is not a web application.

**Comment by nodiscc** [comment]
Done https://github.com/Kickball/awesome-selfhosted/commit/80aa2dadd681d1a0e59f3526965606f96238c51d

**Pull request merged**
