### PR TITLE
Added Music Streaming - Madsonic

### PR DESCRIPTION
**Pull request by altepizza**
Just added Madsonic as additional music streaming service.

### CODE REVIEW

**Comment by Kickball** [comment]
Please change this to put it in alphabetical order then I can merge this pull request. :smile:

**Comment by altepizza** [comment]
Hope that did the job

**Comment by nodiscc** [comment]
@altepizza @MadMarty this project has no proper commit history (everything was imported in a single, hueg commit). Any idea why?

Also what are the benfits of this fork over the main, authoritative subsonic project (https://github.com/EugeneKay/subsonic)?

**Comment by nodiscc** [comment]
Found at https://www.reddit.com/r/selfhosted/comments/3zfkmc/madsonic_music_and_podcast_playermanager_subsonic/cypq9s3:

> Heads up, the new version is intentionally crippled for free users.

>>    Most features in Madsonic are free, but some (like mobile phone streaming) require that you upgrade to Madsonic Premium after the 30-day free trial.

Source http://beta.madsonic.org/pages/getting-started.jsp

@altepizza @MadMarty do you have more information? Can the software be built from public sources without this limitation? @Kickball Without further info I suggest we move it to non-free.md, or even drop this Pull Request entirely. The original FOSS Subsonic seems healthy, and this fork questionable.

Any input is welcome.

**Comment by Kickball** [comment]
Given that Madsonic is a fork of a maintained FOSS project, plans to charge for premium and does not have a proper commit history. I plan on dropping this PR completely unless an explanation is given by either @altepizza or @MadMarty.

**Comment by AndyR207** [comment]
This hasn't been touched in over a week. It's safe to assume that the concerned parties are not going to respond. Closing the PR.

**Pull request closed without merging**
