### PR TITLE
Add Socialhome

### PR DESCRIPTION
**Pull request by jaywink**
Socialhome is a federated and decentralized profile builder and social network engine written in Python and available under the AGPLv3 license.

Thank you for taking the time to work on a PR for Awesome-Selfhosted!

To ensure your PR is dealt with swiftly please check the following:

- [x] Your submissions are formatted according to the guidelines. 
        
    ``[Name](http://homepage/) - Short description. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code)) `License` `Language` ``

- [x] Your additions are ordered alphabetically.
- [x] Your additions are [Free software](https://en.wikipedia.org/wiki/Free_software), or if not they have been added to [non-free](non-free.md).
- [x] Your additions are not already listed at [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin) (IT infrastructure management), [staticgen.com](https://www.staticgen.com/) or [staticsitegenerators.net](https://staticsitegenerators.net/) (static site generators).
- [x] Any licenses you have added are in our [list of licenses](https://github.com/Kickball/awesome-selfhosted/blob/master/README.md#list-of-licenses).
- [x] You have searched the repository for any relevant issues or PRs.
- [x] Any category you are creating has the minimum requirement of 3 items.

### CODE REVIEW

**Comment by danger-awesome-Selfhosted** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Found 1 entries with syntax error(s).</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Found 1 link issue</td>
    </tr>
  </tbody>
</table>

#### Link issue by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
2 | Dupe | https://socialhome.network 


#### Syntax Issues

 Name | Entry
----|----------------------
Socialhome |   * [Socialhome](https://socialhome.network) - Federated and decentralized profile builder and social network engine. ([Demo](https://socialhome.network), [Source Code](https://github.com/jaywink/socialhome)), `AGPLv3` `Python` 
 

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by jaywink** [comment]
Hmm. The duplicate url is because https://socialhome.network is both 1) the home page and 2) the demo site. Since the home page is an instance of Socialhome which is open for registrations.

What should I do, remove the "Demo" link is the only thing that comes to mind if this dupe warning cannot be bypassed? At least "Reddit", which is just above, is breaking the same dupe rule.

**Comment by Kickball** [comment]
@nodiscc @jaywink I believe the best link for the demo is to either link to the [signup page](https://socialhome.network/accounts/signup) or the [news feed](https://socialhome.network/public/).

I will submit a PR to fix the reddit problem.

**Comment by nodiscc** [comment]
I agree, the [Public news feed](https://socialhome.network/public/) looks like a good candidate for the Demo link

**Comment by jaywink** [comment]
Thanks for the notes, fixed!

**Pull request merged**
