### PR TITLE
Fix OnlyOffice naming

### PR DESCRIPTION
**Pull request by ShockwaveNN**
Product title spelled in single word, all capitals - see http://www.onlyoffice.com/about.aspx

### CODE REVIEW

**Comment by AndyR207** [comment]
Please can you update this to include a link to the source code and the language it is written in

    [ONLYOFFICE](http://onlyoffice.org/) - An office suite that enables you to manage documents, projects, team and customer relations in one place. ([Source Code](https://github.com/ONLYOFFICE/DocumentServer)) `AGPLv3` `Nodejs`

**Comment by ShockwaveNN** [comment]
@AndyR207 Done

**Comment by AndyR207** [comment]
Can you take out `JavaScript` please there should only be one language.

**Comment by ShockwaveNN** [comment]
@AndyR207 Done.

P.S. `IRCAnywhere` should be fixed also - contain `javascript` and `Nodejs`. I can create PR later

**Comment by AndyR207** [comment]
Yeah there are quite a few repos that don't have valid formatting, we're working on some tools to sort this out :)

**Pull request merged**
