### PR TITLE
Update Dangerfile

### PR DESCRIPTION
**Pull request by n8225**
Thank you for taking the time to work on a PR for Awesome-Selfhosted!

To ensure your PR is dealt with swiftly please check the following:

- [ ] Your submissions are formatted according to the guidelines. 
        
    ``[Name](http://homepage/) - Short description. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code)) `License` `Language```
- [ ] Your additions are ordered alphabetically.
- [ ] Your additions are [free software](https://en.wikipedia.org/wiki/Free_software), or if not they have been added to [non-free](non-free.md).
- [ ] Any licenses you have added are in our [list of licenses](https://github.com/Kickball/awesome-selfhosted/blob/master/README.md#list-of-licenses).
- [ ] You have searched the repository for any relevant issues or PRs.
- [ ] Any category you are creating has the minimum requirement of 3 items.

### CODE REVIEW

**Comment by m1guelpf** [comment]
@n8225 I added this 4 days ago at #876

**Comment by n8225** [comment]
I know but I needed to create a PR to test the fixes, to get Danger working again.

**Comment by m1guelpf** [comment]
@n8225 You aren't installing Danger correctly.
Fixed in #879

**Comment by m1guelpf** [comment]
@n8225 To get Danger working, you need to:
1- Install it like in #879 
2- Add DANGER_GITHUB_API_TOKEN to TravisCI and expose it

**Comment by n8225** [comment]
@m1guelpf can you hop on https://chat.awesome-selfhosted.com

**Comment by m1guelpf** [comment]
@n8225 Done

**Comment by danger-awesome-Selfhosted** [comment]
test comment

**Comment by glensc** [comment]
I see DANGER_GITHUB_API_TOKEN value in build logs. are you sure this is okay?

```
$ export DANGER_GITHUB_API_TOKEN=50c8af16a9f49eb5ad4d5b4dba3db26f66929013
```

https://travis-ci.org/Kickball/awesome-selfhosted/builds/569961742

I believe I can make changes to this repository as an owner using this token. Haven't checked.

**Comment by nodiscc** [comment]
@n8225 please revoke the Danger token ASAP while we investigate this (if it's a personal token it should appear in your profile settings). If it's a repository token then only @Kickball has access, and we should contact github support to remove it as he's AFK. Ref. https://github.com/Kickball/awesome-selfhosted/issues/89

The token has at least the permission to create issues, I don't know if it has more privileges like write to the repository. Anyway it should not be displayed in the CI logs. Please revoke it as a temporary safety measure, please confirm.

@glensc many thanks :+1:

**Comment by nodiscc** [comment]
The token does not have push access

```
$ curl -H "Authorization: token 50c8af16a9f49eb5ad4d5b4dba3db26f66929013" -H "Accept: application/vnd.github.inertia-preview+json" https://api.github.com/repos/kickball/awesome-selfhosted/collaborators
{
  "message": "Must have push access to view repository collaborators.",
  "documentation_url": "https://developer.github.com/v3/repos/collaborators/#list-collaborators"
}
```

Still should be hidden from the logs, and rotated

**Comment by m1guelpf** [comment]
(I'm the original author of the Danger PR)

If I remember correctly, the token belongs to a bot account created to comment on this repository. The token cannot be hidden because if it is Danger will not work on PRs coming from a fork (which is 99% of the cases). The solution here would be to migrate the Danger CI version to the new Danger GitHub APP version.

**Comment by n8225** [comment]
It is a bot account I created for this.  It should only have access to write issues.  The API key used to be hidden by Travis.  They must have made some changes. I'll generate a new encrypted API key through Travis today just to be on the safe side.

**Pull request merged**
