### PR TITLE
Adding HomelabOS

### PR DESCRIPTION
**Pull request by NickBusey**
Thank you for taking the time to work on a PR for Awesome-Selfhosted!

To ensure your PR is dealt with swiftly please check the following:

- [x] Your submissions are formatted according to the guidelines. 
        
    ``- [Name](http://homepage/) - Short description, less than 250 characters. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code)) `License` `Language` ``

- [x] Your additions are ordered alphabetically.
- [x] Your additions are [Free software](https://en.wikipedia.org/wiki/Free_software), or if not they have been added to [non-free](non-free.md) and marked `⊘ Proprietary`.
- [x] Your additions are not already listed at [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin) (IT infrastructure management), [staticgen.com](https://www.staticgen.com/) or [staticsitegenerators.net](https://staticsitegenerators.net/) (static site generators).
- [x] Your additions have their `License` main server-side `Language`/platform/requirement listed.
- [x] Any licenses you have added are in our [list of licenses](https://github.com/Kickball/awesome-selfhosted/blob/master/README.md#list-of-licenses).
- [x] You have searched the repository for any relevant [issues](https://github.com/Kickball/awesome-selfhosted/issues) or [PRs](https://github.com/Kickball/awesome-selfhosted/pulls), incluing closed ones.
- [x] Any category you are creating has the minimum requirement of 3 items. If not, your addition may be inserted into `Misc/Other`.
- [x] Any software project you are adding to the list is actively maintained.

### CODE REVIEW

**Comment by NickBusey** [comment]
And can I say that this list, awesome-selfhosted, has been a huge help in putting together HomelabOS in the first place.

**Comment by NickBusey** [comment]
I didn't think a source code link was necessary since the url links directly to the source code.

The url redirects to the gitlab page which is https. I'll check the redirect settings to make sure https://homelabos.com/ redirects as expected as well.

It is production ready (I'm using it), though it is marked as Beta still due to upgrade paths not being guaranteed to be smooth just yet. If you want to hold off on adding it for now due to this, that is fine.

**Comment by nodiscc** [comment]
https://gitlab.com/NickBusey/HomelabOS Why not just link there? I can confirm that https://homelabos.com/ is not listening on port 443.


> This software has not reached version 1.0 and should therefore be considered unstable. While any tagged version should work well on it's own, a nice friendly upgrade path from one version to another is not guaranteed.

> If you like getting your hands dirty in early versions of software, this is for you. If you prefer to wait till things are stable and friendly, maybe hold off for a while.

I like that the docs are honest about it. If you can fix the homepage redirection I will merge it.

> A set of Ansible scripts

Nice, feel free to borrow from [here](https://github.com/nodiscc/srv01) (similar project, similar NO GUARANTEES state, does not use docker though)

**Comment by NickBusey** [comment]
I must have missed that category. It sure does fit better there. I'll move it and fix the redirection.

**Pull request merged**
