### PR TITLE
Added tellform to Polls/Events

### PR DESCRIPTION
**Pull request by whitef0x0**

### CODE REVIEW

**Comment by dodekeract** [comment]
Also removed dudle, is this intended?

**Comment by whitef0x0** [comment]
no this wasn't intended

**Comment by whitef0x0** [comment]
I just added dudle back

**Comment by nodiscc** [comment]
https://github.com/whitef0x0/awesome-selfhosted/pull/1

**Comment by whitef0x0** [comment]
@nodiscc merged your pr

**Comment by nodiscc** [comment]
@whitef0x0 The section should be ordered alphabetically. Can you do it?

**Comment by whitef0x0** [comment]
@nodiscc done.

**Pull request merged**
