### PR TITLE
Add homehost (media streaming), split Media streaming category

### PR DESCRIPTION
**Pull request by ridhwaans**
Thank you for taking the time to work on a PR for Awesome-Selfhosted!

To ensure your PR is dealt with swiftly please check the following:

- [✓] Your submissions are formatted according to the guidelines. 
        
    ``- [Name](http://homepage/) - Short description, less than 250 characters. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code)) `License` `Language` ``

- [✓] Your additions are ordered alphabetically.
- [✓] Your additions are [Free software](https://en.wikipedia.org/wiki/Free_software), or if not they have been added to [non-free](non-free.md).
- [✓] Your additions are not already listed at [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin) (IT infrastructure management), [staticgen.com](https://www.staticgen.com/) or [staticsitegenerators.net](https://staticsitegenerators.net/) (static site generators).
- [✓] Any licenses you have added are in our [list of licenses](https://github.com/Kickball/awesome-selfhosted/blob/master/README.md#list-of-licenses).
- [✓] You have searched the repository for any relevant [issues](https://github.com/Kickball/awesome-selfhosted/issues) or [PRs](https://github.com/Kickball/awesome-selfhosted/pulls).
- [✓] Any category you are creating has the minimum requirement of 3 items.
- [✓] Any software project you are adding to the list is actively maintained.

### CODE REVIEW

**Comment by danger-awesome-Selfhosted** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Found 1 link issue</td>
    </tr>
  </tbody>
</table>

#### Link issue by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
2 | Dupe | https://github.com/ridhwaans/homehost 


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by ridhwaans** [comment]
Added dupe homehost links to https://github.com/Kickball/awesome-selfhosted#audio-streaming and https://github.com/Kickball/awesome-selfhosted#video-streaming because it applies to both categories

**Comment by nodiscc** [comment]
By the way we should find out whether some of these are still working and/or maintained:

* CRMTP: ?
* Darwin: ?
* Flumotion: ?
* Mistserver: ?
* ReadyMedia: ?
* Rygel: ?

**Comment by ridhwaans** [comment]
@nodiscc I will create a new multimedia category and move the other projects you mentioned into it. I can do it in this PR (or do you want me to create a new branch and PR?).  
`homehost` is powered by Spotify API and TMDb API to provide complete metadata for local music and movies. It is a requirement because the app cant function without it otherwise it needs to have major changes. In the future it will need an iTunes API or books API to support books and comics media.

**Comment by nodiscc** [comment]
> I can do it in this PR (or do you want me to create a new branch and PR?)

In this PR would be fine!

I understand the need for external services to find metadata on media files, thanks for the explanation. I can recommend [MusicBrainz](https://en.wikipedia.org/wiki/MusicBrainz) for a good source of audio metadata.

**Pull request merged**
