### PR TITLE
Add Dashing to Personal Dashboard list

### PR DESCRIPTION
**Pull request by mide**
I recently came across [Dashing](https://github.com/Shopify/dashing), which is a fantastic dashboard-building tool.

### CODE REVIEW

**Comment by AndyR207** [comment]
Missing a full stop at the end of your description, other than that you're good.

**Comment by mide** [comment]
Since this is a list and the descriptions aren't sentences, the need for the full stop could be argued. 

But that's a whole different issue, so I've gone ahead and added the period.

Thanks!

**Comment by AndyR207** [comment]
The full stops are for compliance with our scanner that uses regex and expects them (and will thus throw up errors if they are missing).

Looks good to me.

**Comment by nodiscc** [comment]
@AndyR207 the missing full stop should 1. either be tolerated by your scanner 2. either be added by yourself or one of the maintainers after the fact (you can edit the README). It should not require the submitter to edit his PR since the entry is valid (Since this is a list and the descriptions aren't sentences, descriptions missing it are valid)

**Pull request merged**
