### PR TITLE
Add BoZoN

### PR DESCRIPTION
**Pull request by juanito003**

### CODE REVIEW

**Comment by nodiscc** [comment]
@juanito003 Can you add the license and programming language?

Just go to https://github.com/Kickball/awesome-selfhosted/pull/62/files and edit README.md

**Comment by juanito003** [comment]
It seems there is no license for now, I asked the developer and am waiting for his answer.

**Comment by nodiscc** [comment]
@juanito003 BoZon is now licensed under the AGPLv3: https://github.com/broncowdd/BoZoN/#licence

Can you update your patch? (edit README.md in your `patch-2`  branch)

**Comment by nodiscc** [comment]
Thank you, moved to https://github.com/Kickball/awesome-selfhosted/pull/133

**Pull request closed without merging**
