### PR TITLE
Add trello burndown chart.

### PR DESCRIPTION
**Pull request by swordbeta**
Thank you for taking the time to work on a PR for Awesome-Selfhosted!

To ensure your PR is dealt with swiftly please check the following:

- [X] Your submissions are formatted according to the guidelines. 
        
    ``[Name](http://homepage/) - Short description. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code)) `License` `Language```
- [X] Your additions are ordered alphabetically.
- [X] Your additions are [Free software](https://en.wikipedia.org/wiki/Free_software), or if not they have been added to [non-free](non-free.md).
- [X] Your additions are not already listed at [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin) (IT infrastructure management), [staticgen.com](https://www.staticgen.com/) or [staticsitegenerators.net](https://staticsitegenerators.net/) (static site generators).
- [X] Any licenses you have added are in our [list of licenses](https://github.com/Kickball/awesome-selfhosted/blob/master/README.md#list-of-licenses).
- [X] You have searched the repository for any relevant issues or PRs.
- [X] Any category you are creating has the minimum requirement of 3 items.

### CODE REVIEW

**Comment by danger-awesome-Selfhosted** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Found 1 entries with syntax error(s).</td>
    </tr>
  </tbody>
</table>

#### Syntax Issues

 Name | Entry
----|----------------------
Trello Burndown |   * [Trello Burndown](https://github.com/swordbeta/trello-burndown) - An easy to use SCRUM burndown chart for Trello boards.  `MIT` `Go/Docker`  


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by nodiscc** [comment]
@swordbeta Thanks, is there another distribution/installation method than precompiled binaries/docker images? If not, this entry must be moved to non-free.md.

> Free Software allows users to run the software for any purpose, study, modify or distribute the source code.

**Comment by swordbeta** [comment]
@nodiscc Yes, it's possible to clone the repository and compile or install through `go install`.

**Comment by nodiscc** [comment]
Nice. I was just reading the makefile, apparently `make docker` builds the docker image.

There's another minor change required, I think it requires a Trello API key to work and/or connectivity with trello servers? If this is the case, please add the ⚠ symbol after the entry title (See [List of licenses](https://github.com/Kickball/awesome-selfhosted#list-of-licenses) - depends on a third-party service.

Thanks

**Comment by swordbeta** [comment]
@nodiscc Added the icon (amended) and will add instructions to self compile in README!

**Pull request merged**
