### PR TITLE
Updating self-hosted apps list with open source RADIUS solutions

### PR DESCRIPTION
**Pull request by lirantal**
Adding in the popular fortune-500 FreeRADIUS servers for self-hosted RADIUS and AAA based solutions as well as daloRADIUS, the popular web management platform.

### CODE REVIEW

**Comment by lirantal** [comment]
I updated the PR to be able to merge now.

**Comment by nodiscc** [comment]
Hi @lirantal can you fix the following

 * `daloRADIUS on Github` -> `Source Code`
 * source code link should be between parentheses
 * Missing programming languages/platforms
 * Projects should only have one license tag (at worst, `GPLv2/Other` is acceptable)

Check https://github.com/Kickball/awesome-selfhosted#contributing and feel free to request more info. Thanks for the patch.

**Comment by lirantal** [comment]
Yes, I'll address all of them, and resubmit.

**Comment by nodiscc** [comment]
Thanks @lirantal, fixed and merged.

**Comment by lirantal** [comment]
Thanks @nodiscc!

**Pull request merged**
