### PR TITLE
Added Ambar to List of Awesome Self-Hosted

### PR DESCRIPTION
**Pull request by sochix**
Thank you for taking the time to work on a PR for Awesome-Selfhosted!

To ensure your PR is dealt with swiftly please check the following:

- [x] Your submissions are formatted according to the guidelines. 
        
    ``[Name](http://homepage/) - Short description. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code)) `License` `Language```
- [x] Your additions are ordered alphabetically.
- [x] Your additions are [free software](https://en.wikipedia.org/wiki/Free_software), or if not they have been added to [non-free](non-free.md).
- [x] Any licenses you have added are in our [list of licenses](https://github.com/Kickball/awesome-selfhosted/blob/master/README.md#list-of-licenses).
- [x] You have searched the repository for any relevant issues or PRs.
- [x] Any category you are creating has the minimum requirement of 3 items.

### CODE REVIEW

**Comment by sochix** [comment]
@nodiscc Unfortunately we don't have it public on GitHub since we're still preparing entire repo with its history. But you can see the source code inside the virtual machine image that we provide.

**Comment by Kickball** [comment]
@sochix we have always required for all other projects that the source code be available online, prior to downloading, as such it would be best to put this addition on hold until the Source Code is publically available.

Alongside this, the license on the website says that the free version is only for 'Free for Personal / Academic use'.

**Comment by nodiscc** [comment]
Correct, if there are no other downloads than in binary form/VM for now I think it is better tu put this PR on hold. Please let us know when the source code itself is publicly available.

Also the license you referenced (https://en.wikipedia.org/wiki/Fair_License) contradicts with the terms on the website (_Free for Personal / Academic use_). If there are restrictions on usage it must unfortunately be added to non-free.md.

**Comment by sochix** [comment]
Hello @Kickball and @nodiscc ! 

We've made some great steps towards making Ambar more open-source!

1. License is [here](https://github.com/RD17/ambar/blob/master/License.txt) and it's the same on our repo and site.
2. We've open-sourced most of our components, our github repo is [here](https://github.com/RD17/ambar)
3. We've published [docker images](https://hub.docker.com/r/ambar/) and provided users with simple installation instructions. So now anyone can pull our images and explore them.
4. Community Edition Ambar is downscaled Enterprise Edition Ambar
5. Our product is warmly welcomed on [reddit/selfhosted](https://www.reddit.com/r/selfhosted/comments/5t6lrj/selfhosted_document_managment_system/)

**Pls, include Ambar in your awesome list.**

**Comment by nodiscc** [comment]
Great progress on Ambar @sochix and the reddit thread was interesting.

> Pls, include Ambar in your awesome list.

In the current state it can be added to non-free.md. Can you move the Ambar entry there?

 * the only distribution channel is precompiled Docker images
 * license has limitations on number of users
   > It's free for personal use
 * > We've open-sourced _most_ of our components
 * > Is this open source?
   >> Yes, but only partially. https://github.com/RD17/ambar We'll publish some Ambar's modules' Docker images and their sources soon. You can watch our progress on our blog http://blog.rdseventeen.com/


You could move the entry to README.md later when Ambar matches the following criteria:

> Allows users to run the software for any purpose, study, modify or distribute the source code.

**Pull request closed without merging**
