### PR TITLE
Added Magento to E-commerce section

### PR DESCRIPTION
**Pull request by faisalhmohd**

### CODE REVIEW

**Comment by nodiscc** [comment]
Please change the license tag to `OSLv3` and add a relevant link/description in https://github.com/Kickball/awesome-selfhosted#list-of-licenses

**Comment by faisalhmohd** [comment]
Changed the license but the relevant link/description for the license is already added, or am I misunderstanding anything?

**Comment by nodiscc** [comment]
Everything is OK, I had missed the existing entry in the licenses list. Thanks

**Comment by Kickball** [comment]
Could you add a space between the language and license tag? I know it may seem like a minor thing but our scanning system won't like it. Thanks.

**Comment by faisalhmohd** [comment]
Space has been added.

**Comment by Kickball** [comment]
Thanks for making the change, and thanks for the submission.

**Pull request merged**
