### PR TITLE
added Thingspeak, IoT Data Storage

### PR DESCRIPTION
**Pull request by cavebeat**

### CODE REVIEW

**Comment by AndyR207** [comment]
Looks good to me.

**Comment by nodiscc** [comment]
Needs to be moved to the Automation section, right?

> Send sensor data to the cloud.
> Analyze and visualize your data.
> Trigger a reaction.

**Comment by AndyR207** [comment]
You also have an extra bracket before Source Code in this PR.

**Comment by cavebeat** [comment]
i have put it into this section, because it fits to Freeboard. 
Freeboard is a visualizer for the data storage. I don't see myself something related to automation. 

so where to put it?
furthermore is phant no automation.

**Comment by nodiscc** [comment]
Well from the description it looked more like Huginn (in Automation) but Personal Dashboards is ok.

**Comment by Kickball** [comment]
I agree with @nodiscc that it does seem to be both Automation and Personal Dashboards, but until we use a tagging system we'll just add it to the Personal Dashboard section.

**Pull request merged**
