### PR TITLE
Zimbra collaboration

### PR DESCRIPTION
**Pull request by motiko**
Added Zimbra collaboration to Email category.
Free email server (exchange like) hosted solution

### CODE REVIEW

**Comment by Kickball** [comment]
If you could remove the spaces between the [text] and (url) then I'm happy to merge this.

@nodiscc what do you think?

**Comment by motiko** [comment]
Sure

**Comment by Kickball** [comment]
On second thought would this be classified as Groupware or Email? It does provide other options and might better fit into Groupware.

What do you think @nodiscc?

**Comment by motiko** [comment]
I used it back when it was primarily a mail server . I guess the focus is still on that side.
But surely enough it can fit into both categories.

**Comment by Kickball** [comment]
Just waiting for @nodiscc opinion on which sections we should add this to (groupware/email).

**Comment by nodiscc** [comment]
Hi everyone, Groupware seems appropriate.

**Pull request merged**
