### PR TITLE
Some additions and fixes

### PR DESCRIPTION
**Pull request by nodiscc**
See commit details

### CODE REVIEW

**Comment by nodiscc** [comment]
`make listlicenses` currently returns

```

 List of licenses:
AAL` `
AGPLv3` `
Apache` `
Apache 2.0` `
ARTv2` `
BSD` `
CC0` `
CCBYNCv4` `
CC BY-SA 3.0` `
CeCILL-B` `
CPALv1` `
ECLv2` `
EPLv1` `
GPL` `
GPL2` `
GPLv2` `
GPLv3` `
IPL` `
ISC` `
Javascript` `
Language` `
LGPLv2` `
LGPLv3` `
License` `
MIT` `
MPLv2` `
Multiple` `
OSLv3` `
Other` `
Public domain` `
WTFPL` `
Zlib` `
Zope`

```

Obviously there are a few false positives but it helps detecting duplicate/misspelled licenses or ones that are missing from the licenses table.

**Comment by nodiscc** [comment]
`make longdescriptions` returns only 2 descriptions longer than the limit of 250 characters:

```


Descriptions exceeding 250 chars:
) - Self Hosted Git Management Application - GitLab is open source software to collaborate on code. Manage git repositories with fine grained access controls that keep your code secure. Perform code reviews and enhance collaboration with merge requests. Each project can also have an issue tracker and a wiki. ([
) - A basic site for hosting static documents - docstore is a simple way to serve Markdown files without any server-side processing, and without requiring you (as the author) to recompile every time you change an article. It consists of a very simple JS script that makes an ajax request to your server, runs a Markdown processor on what it finds, and then displays the results. Clone the repository and add articles in the text/ directory to get started. ([


```

**Comment by Kickball** [comment]
Could you clarify why the following were removed?

* Gazelle
* Untrusted
* Webalizer

**Comment by nodiscc** [comment]
The details are in commit messages, except for Untrusted which I forgot to re-add to non-free.md (doing it now). It must be moved there since CC BY-NC forbids commercial use, and therefore is a non-free license.

Gazelle was moved to non-free.md in 9b4c4720, it also has a non commercial-use restriction in https://github.com/WhatCD/Gazelle/blob/master/docs/COPYING.txt.

For webalizer, see commit https://github.com/Kickball/awesome-selfhosted/pull/669/commits/62cb13d2b421f0db52680a46b854c467083e4ea5: `remove webalizer (unmaintained, last modification date in source .tgz is 2013)`

**Comment by Kickball** [comment]
My bad for missing the commit messages, all changes look good to me.

**Comment by nodiscc** [comment]
In the future we could run `make` automatically on Pull Requests using a CI tool (Travis?). This would help validate incoming patches; currently `make` returns a ton of errors (mainly missing licenses/languages) which must be fixed.

**Comment by Kickball** [comment]
I'm going to give Travis setup a shot this week alongside setting up issue and PR templates.

**Pull request merged**
