### PR TITLE
Add taskwarrior.org

### PR DESCRIPTION
**Pull request by ahayworth**
Taskwarrior.org is a pretty cool client/server task management solution, with several community-based frontends. I use it daily and love it.

### CODE REVIEW

**Comment by nodiscc** [comment]
Some things are missing: source code link https://taskwarrior.org/download/#git, language is C++, license is MIT.

    [Name](http://homepage/) - Short description ([Demo](http://url.to/demo), [Source code](http://url.of/source/code)) `License` `Language`

@ahayworth Thanks :+1: I will merge it if you can fix the formatting

**Comment by ahayworth** [comment]
Whoops! Updated! :)

**Comment by Kickball** [comment]
Looks good to merge!

**Comment by ahayworth** [comment]
:+1:

- Andrew Hayworth

**Pull request merged**
