### PR TITLE
AlertHub Added

### PR DESCRIPTION
**Pull request by Ardakilic**
Thank you for taking the time to work on a PR for Awesome-Selfhosted!

To ensure your PR is dealt with swiftly please check the following:

- [x] Your submissions are formatted according to the guidelines. 
        
    ``- [Name](http://homepage/) - Short description, less than 250 characters. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code)) `License` `Language` ``

- [x] Your additions are ordered alphabetically.
- [x] Your additions are [Free software](https://en.wikipedia.org/wiki/Free_software), or if not they have been added to [non-free](non-free.md).
- [x] Your additions are not already listed at [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin) (IT infrastructure management), [staticgen.com](https://www.staticgen.com/) or [staticsitegenerators.net](https://staticsitegenerators.net/) (static site generators).
- [x] Any licenses you have added are in our [list of licenses](https://github.com/Kickball/awesome-selfhosted/blob/master/README.md#list-of-licenses).
- [x] You have searched the repository for any relevant [issues](https://github.com/Kickball/awesome-selfhosted/issues) or [PRs](https://github.com/Kickball/awesome-selfhosted/pulls).
- [x] Any category you are creating has the minimum requirement of 3 items.
- [x] Any software project you are adding to the list is actively maintained.

### CODE REVIEW

**Comment by danger-awesome-Selfhosted** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Found 1 link issue</td>
    </tr>
  </tbody>
</table>

#### Link issue by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
2 | Dupe | https://github.com/Ardakilic/alerthub 


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by nodiscc** [comment]
> if you want to only follow new releases, there isn't a way to achieve this from GitHub directly.

https://github.com/Ardakilic/alerthub/releases.atom :) Not to detract anything from your tool, but this feature exists and relies on the well established RSS/ATOM standards.

I'll wait for a review from another maintainer

**Comment by Ardakilic** [comment]
@nodiscc Well it's there, however it's not an easy way to follow. What if there's more than one release/repository you want to follow ? Let's assume you have a recipe in IFTTT that sends an e-mail for each releases.atom update. Do you want to make the same recipe for each repository ? That becomes quite hard to maintain and frustrating after a while. 

This is the reason systems like sibbell.com exist(ed).

**Comment by nodiscc** [comment]
> What if there's more than one release/repository you want to follow ?

RSS feed reader?

cap

Or simple aggregator/planet-like. Such things exist as web apps, desktop apps, cli... 

> recipe in IFTTT that sends an e-mail for each releases.atom update. Do you want to make the same recipe for each repository

Yes IFTTT doesn't scale and is not meant to, I think.

> NodeJS 8.x or newer
> can run AlertHub through a Docker container

The whole NPM/Node stack for an RSS to email bridge? Docker? [rss2email](https://packages.debian.org/jessie/rss2email) does it well, for years, in ~1000 lines of python, which is installed by default on basically every box.

But again, leaving this to the appreciation of other maintainers.

**Comment by Ardakilic** [comment]
> RSS feed reader?

I'm a lazy dude that needs to see the updates up front. That's the reason I've implemented Email and Especially Pushbullet integration. I get such notification directly to my phone.

> Or simple aggregator/planet-like. Such things exist as web apps, desktop apps, cli...

I wanted to self host and make one one myself for my needs, that's why we're here :)

> The whole NPM/Node stack for an RSS to email bridge? Docker?

Why not ? 

So PRs are judged by how big/bloated/hated the used stack is (which is debatable) ? Sorry, I didn't know about this! Many of the tools here are far from being lightweight.

Also, this isn't just an aggregator+email bridge, but also a push notifier. I personally use and like Pushbullet to get notified as I've mentioned, not only for these but also from other parts of my projects.

Dockerizing is also optional. Also if you like to containerize every tool (I don't personally!) as far as I can say, not every containers come with python pre-installed unlike the boxes.

Also, using the GitHub API instead of repo.atom is one of the various stuffs I want to do with a major version bump.

Here's a discussion and other suggestions telling why such tools are demanded by people, if anyone's interested: https://github.com/isaacs/github/issues/410

Also, since this repository's description links to the subreddit, here's this repository's reddit post from 2 months ago: https://www.reddit.com/r/selfhosted/comments/8gitfg/alerthub_get_notified_when_a_github_repository/

**Comment by nodiscc** [comment]
@Ardakilic I understand this is useful to you and also others, and it also offers features like push notifications, so I'm no longer opposed to merging it. Thank you for taking the time to explain.

It just needs the `⚠` symbol like stated in https://github.com/Kickball/awesome-selfhosted#list-of-licenses (there are examples of where to place it in the list, sorry this got removed from pull request guidelines in error), since it depends on closed source 3rd party services.

**Comment by Ardakilic** [comment]
@nodiscc Sorry, I didn't catch the earlier notification. Thanks for reminding!

**Comment by slel** [comment]
GitHub now offers the option to watch a repository with notifications only for releases.

**Comment by Ardakilic** [comment]
@slel Yup, but that doesn't include the Push notification feature which my tool has.

**Pull request merged**
