### PR TITLE
Add REDAXO

### PR DESCRIPTION
**Pull request by fuerbringer**
Thank you for taking the time to work on a PR for Awesome-Selfhosted!

To ensure your PR is dealt with swiftly please check the following:

- [x] Your submissions are formatted according to the guidelines. 
        
    ``[Name](http://homepage/) - Short description. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code)) `License` `Language```
- [x] Your additions are ordered alphabetically.
- [x] Your additions are [free software](https://en.wikipedia.org/wiki/Free_software), or if not they have been added to [non-free](non-free.md).
- [x] Any licenses you have added are in our [list of licenses](https://github.com/Kickball/awesome-selfhosted/blob/master/README.md#list-of-licenses).
- [x] You have searched the repository for any relevant issues or PRs.
- [x] Any category you are creating has the minimum requirement of 3 items.

### CODE REVIEW

**Comment by Kickball** [comment]
Is there English information available? 
If not it could be worth mentioning in the description that it is a German (I think) project.

**Comment by fuerbringer** [comment]
Official documentation for the CMS is mostly only available in German. But the CMS' Backend itself is available in English.
Should I just mention, that the documentation for the CMS is only available in German (in the next commit)?

**Comment by Kickball** [comment]
I'd recommend changing it to be:

``A simple, flexible and useful content management system (documentation only available in German).``

I'd be worth getting the other collaborators feedback on this though. ( @AndyR207 @nodiscc @n8225 )

**Comment by nodiscc** [comment]
@fuerbringer, the change suggested above

>A simple, flexible and useful content management system (documentation only available in German).

would be satisfying (an english documentation even more so :) )

**Pull request merged**
