### PR TITLE
Add Jellyfin

### PR DESCRIPTION
**Pull request by nvllsvm**
Jellyfin is a fully free-software fork of Emby.

To ensure your PR is dealt with swiftly please check the following:

- [X] Your submissions are formatted according to the following requirements:
        
``- [Name](http://homepage/) - Short description, less than 250 characters. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``

- [X] Your additions are ordered alphabetically.
- [X] Your additions are [Free software](https://en.wikipedia.org/wiki/Free_software), or if not they have been added to [non-free](non-free.md) and marked `⊘ Proprietary`.
- [X] If your additions depend on proprietary services outside the user's control, they must be marked `⚠`.
- [X] Your additions are not already listed at [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin) (IT infrastructure management), [staticgen.com](https://www.staticgen.com/) or [staticsitegenerators.net](https://staticsitegenerators.net/) (static site generators).
- [X] Your additions have their `License` main server-side `Language`/platform/requirement listed.
- [X] Any licenses you have added are in our [list of licenses](https://github.com/Kickball/awesome-selfhosted/blob/master/README.md#list-of-licenses).
- [X] You have searched the repository for any relevant [issues](https://github.com/Kickball/awesome-selfhosted/issues) or [PRs](https://github.com/Kickball/awesome-selfhosted/pulls), incluing closed ones.
- [X] If the main link of your addition points to the program's source code, there is no need to add a duplicate _Source Code_ link. The _Demo_ and _Clients_ links are not mandatory.
- [X] Any category you are creating has the minimum requirement of 3 items. If not, your addition may be inserted into `Misc/Other`.
- [X] Any software project you are adding to the list is actively maintained.

### CODE REVIEW

**Comment by danger-awesome-Selfhosted** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Found 1 entries with syntax error(s).</td>
    </tr>
  </tbody>
</table>

#### Syntax Issues

 Name | Entry
----|----------------------
Jellyfin | - [Jellyfin](https://jellyfin.media) - Streaming media server with a slick UI and robust transcoding capabilities. ([Source Code](https://github.com/jellyfin/jellyfin), `GPL-2.0` `C#` 
 

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by joshuaboniface** [comment]
@nvllsvm Should also add us under the Ombi entry:

>Ombi - A content request system for Plex/Emby, connects to SickRage, CouchPotato, Sonarr, with a growing feature set. (Demo, Source Code) GPL-2.0 C#

**Comment by joshuaboniface** [comment]
It would also be fair to mention that we're a fork of Emby, like the Airsonic entry.

**Comment by nvllsvm** [comment]
Eh, we can if some find it valuable but I'd rather Jellyfin stand on it's own here. It kicks ass as-is ;)

**Comment by joshuaboniface** [comment]
Fair!

**Comment by nvllsvm** [comment]
@nodiscc - added fork text to the description.

**Pull request merged**
