### PR TITLE
Added Auth0 to the list of Identity self hosted

### PR DESCRIPTION
**Pull request by mgonto**

### CODE REVIEW

**Comment by nodiscc** [comment]
Does it allow setting up your local, own Identity provider? It looks like this is a suite of dev/client-side tools to interact with the auth provider at auth0.com. If the authentication service can't be self hosted this can't be included.

**Comment by mgonto** [comment]
Yes, you can set up your own IdP.

Basically, when you set up a new "Database connection" on Auth0, it'll store the users in Auth0 service (which can be on prem). Once you have that, you'll be able to use any of the protocols we support to create new users in your AUth0 DB (OpenID COnnect, Saml, Ws-fed, etc.).

Makes sense?

Database Connection: http://d.pr/i/16Uic

**Comment by nodiscc** [comment]
@mgonto can you add a programming language tag? (see entries formatting at https://github.com/Kickball/awesome-selfhosted/blob/master/README.md#contributing)

@Kickball are you ok to merge this?

**Comment by mgonto** [comment]
@nodiscc we have SDKs for most of the different platforms, so it's not just one programming language. You can basically use any :). What should I put?

**Comment by mgonto** [comment]
Thanks for answering so fast :).

**Comment by dgoujard** [comment]
But Auth0 is not open source, you can't install Auth0 service on your own server. 
You can just allow Auth0 Saas to connect to your mysql/postgresql database

**Comment by sandrinodimattia** [comment]
Auth0 server is not open source but you can install it on your own server: https://auth0.com/docs/appliance

**Comment by dgoujard** [comment]
@sandrinodimattia Oh i didn't see it

**Comment by nodiscc** [comment]
> so it's not just one programming language

What is the main language/technology/platform for the software running on user's servers? _Nodes_ described in https://auth0.com/docs/appliance

**Comment by sandrinodimattia** [comment]
Nodejs on Ubuntu

**Comment by nodiscc** [comment]
@mgonto can you add `Nodejs`?

**Comment by mgonto** [comment]
Done @nodiscc thanks for the quick turnaround :).

**Pull request merged**
