### PR TITLE
added farmOS Agriculture Resource Planning

### PR DESCRIPTION
**Pull request by cavebeat**
Thank you for taking the time to work on a PR for Awesome-Selfhosted!

To ensure your PR is dealt with swiftly please check the following:

- [x] Your submissions are formatted according to the guidelines. 
        
    ``[Name](http://homepage/) - Short description. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code)) `License` `Language` ``

- [x] Your additions are ordered alphabetically.
- [x] Your additions are [Free software](https://en.wikipedia.org/wiki/Free_software), or if not they have been added to [non-free](non-free.md).
- [x] Your additions are not already listed at [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin) (IT infrastructure management), [staticgen.com](https://www.staticgen.com/) or [staticsitegenerators.net](https://staticsitegenerators.net/) (static site generators).
- [x] Any licenses you have added are in our [list of licenses](https://github.com/Kickball/awesome-selfhosted/blob/master/README.md#list-of-licenses).
- [x] You have searched the repository for any relevant issues or PRs.
- [x] Any category you are creating has the minimum requirement of 3 items.

### CODE REVIEW

**Comment by cavebeat** [comment]
License is GPL regarding homepage and drupal page, 
Pending https://github.com/farmOS/farmOS/pull/38

**Comment by danger-awesome-Selfhosted** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Found 1 entries with syntax error(s).</td>
    </tr>
  </tbody>
</table>

#### Syntax Issues

 Name | Entry
----|----------------------
farmOS |   * [farmOS](http://farmos.org/) - A web-based farm record keeping application. ([Source Code](https://github.com/farmOS/farmOS)) `GPLv2 `PHP` 
 

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by cavebeat** [comment]
changed GPLv3 -> GPLv2 
removed typo

**Comment by Kickball** [comment]
@nodiscc @cavebeat won't the addition of the section in both this PR and #1142 create PR issues?

I'm happy with the Agriculture resource planning section to stay, although ideally, we should have 3 items within it.

**Comment by nodiscc** [comment]
>won't the addition of the section in both this PR and #1142 create PR issues?

Yes, can be resolved manually.

> although ideally, we should have 3 items within it.

Yes that would be ideal. I think that some more subsections and reordering will be needed sometime soon (https://github.com/Kickball/awesome-selfhosted/issues/1146)

**Pull request merged**
