### PR TITLE
Update Apostrophe

### PR DESCRIPTION
**Pull request by mightyfree**
Updated Apostrophe url to new official site: http://apostrophecms.org

- [x] Your submissions are formatted according to the guidelines.

### CODE REVIEW

**Comment by Kickball** [comment]
@nodiscc @mightyfree this looks good. Happy for this to be merged once the conflict has been resolved.

**Comment by nodiscc** [comment]
Resolved the merge conflict using the Github conflict resolving tool (quite nice)

**Comment by danger-awesome-Selfhosted** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please rebase to get rid of the merge commits in this Pull Request</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by nodiscc** [comment]
> Please rebase to get rid of the merge commits in this Pull Request

You can ignore this.

**Pull request merged**
