### PR TITLE
Add CraftCMS to the list of Content Management Systems

### PR DESCRIPTION
**Pull request by volodymyr-kushnir**
Add CraftCMS to the list of Content Management Systems

### CODE REVIEW

**Comment by nodiscc** [comment]
Thank you, unfortunately it seems CraftCMS is non-free (proprietary) software, as per https://github.com/Kickball/awesome-selfhosted#contributing this entry must be added to https://github.com/Kickball/awesome-selfhosted/blob/master/non-free.md instead.

**Comment by volodymyr-kushnir** [comment]
I'm not sure, I was able to install and use it, it's kind of freemium (free to use with single admin account). I'll double-check it later.

**Comment by Kickball** [comment]
@volodymyr-kushnir did you check?

**Comment by Kickball** [comment]
@volodymyr-kushnir we will close this PR 7 days from now due inactivity, and the limit of one admin account.

**Pull request closed without merging**
