### PR TITLE
adding silverstripe to cms list

### PR DESCRIPTION
**Pull request by spekulatius**

### CODE REVIEW

**Comment by Kickball** [comment]
Mind adding the programming language it was written in just after the license, example:

* [SilverStripe](https://www.silverstripe.org) - easy to use CMS with powerful MVC framework underlying. `BSD` `Python`

If you could also add a link to the demo: http://demo.silverstripe.org and a link the source code: https://github.com/silverstripe

Then we should be able to merge this request.

**Comment by spekulatius** [comment]
Hello @Kickball ,

thank you for your response and giving me indication about further information to add. I've updated my pull request to include github, the demo as well as PHP.

Cheers :)

**Comment by Kickball** [comment]
Looks good, thanks for the pull request :)

**Comment by spekulatius** [comment]
no problem :)

**Pull request merged**
