### PR TITLE
Add savepad and scri.ch(travis test)

### PR DESCRIPTION
**Pull request by n8225**
Thank you for taking the time to work on a PR for Awesome-Selfhosted!

To ensure your PR is dealt with swiftly please check the following:

- [x] Your submissions are formatted according to the guidelines. 
        
    ``[Name](http://homepage/) - Short description. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code)) `License` `Language```
- [x] Your additions are ordered alphabetically.
- [x] Your additions are [free software](https://en.wikipedia.org/wiki/Free_software), or if not they have been added to [non-free](non-free.md).
- [x] Any licenses you have added are in our [list of licenses](https://github.com/Kickball/awesome-selfhosted/blob/master/README.md#list-of-licenses).
- [x] You have searched the repository for any relevant issues or PRs.
- [x] Any category you are creating has the minimum requirement of 3 items.

### CODE REVIEW

**Comment by danger-awesome-Selfhosted** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Found 1 link issue</td>
    </tr>
  </tbody>
</table>

#### Link issue by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
3 | Error | https://scri.ch/ <br> Connection reset by peer - SSL_connect


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by greggluhring** [comment]
Please remove me I tried every other channel


On December 16, 2016 6:09:56 PM danger-awesome-Selfhosted 
<notifications@github.com> wrote:

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Found 1 link issue</td>
    </tr>
  </tbody>
</table>

#### Link issue by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
3 | Error | https://scri.ch/ <br> Connection reset by peer - SSL_connect


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by greggluhring** [comment]
I've been trying to get off this list for months please remove me


On December 16, 2016 6:09:18 PM n8225 <notifications@github.com> wrote:

Thank you for taking the time to work on a PR for Awesome-Selfhosted!

To ensure your PR is dealt with swiftly please check the following:

- [ ] Your submissions are formatted according to the guidelines.

    ``[Name](http://homepage/) - Short description. 
([Demo](http://url.to/demo), [Source Code](http://url.of/source/code)) 
`License` `Language```
- [ ] Your additions are ordered alphabetically.
- [ ] Your additions are [free 
software](https://en.wikipedia.org/wiki/Free_software), or if not they have 
been added to [non-free](non-free.md).
- [ ] Any licenses you have added are in our [list of 
licenses](https://github.com/Kickball/awesome-selfhosted/blob/master/README.md#list-of-licenses).
- [ ] You have searched the repository for any relevant issues or PRs.
- [ ] Any category you are creating has the minimum requirement of 3 items.

You can view, comment on, or merge this pull request online at:

  https://github.com/Kickball/awesome-selfhosted/pull/898

-- Commit Summary --

  * Added anchr.io and http2-serverpush-proxy
  * Fix HRM formatting
  * lowercase resources in link
  * Merge pull request #889 from Kickball/hrm-fix
  * Add REDAXO
  * Update AUTHORS file (#890)
  * Move Anchr to Misc Category
  * Merge pull request #859 from Kickball/add-ah
  * Changed REDAXO CMS description
  * Merge pull request #893 from fuerbringer/redaxo
  * Add savepad and scri.ch
  * fix license/lang

-- File Changes --

    D AUTHORS (204)
    A AUTHORS.md (102)
    M README.md (11)

-- Patch Links --

https://github.com/Kickball/awesome-selfhosted/pull/898.patch
https://github.com/Kickball/awesome-selfhosted/pull/898.diff

-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/Kickball/awesome-selfhosted/pull/898

**Comment by greggluhring** [comment]
Please remove I have been trying for a long time you won't, listen.


On December 16, 2016 6:09:18 PM n8225 <notifications@github.com> wrote:

Thank you for taking the time to work on a PR for Awesome-Selfhosted!

To ensure your PR is dealt with swiftly please check the following:

- [ ] Your submissions are formatted according to the guidelines.

    ``[Name](http://homepage/) - Short description. 
([Demo](http://url.to/demo), [Source Code](http://url.of/source/code)) 
`License` `Language```
- [ ] Your additions are ordered alphabetically.
- [ ] Your additions are [free 
software](https://en.wikipedia.org/wiki/Free_software), or if not they have 
been added to [non-free](non-free.md).
- [ ] Any licenses you have added are in our [list of 
licenses](https://github.com/Kickball/awesome-selfhosted/blob/master/README.md#list-of-licenses).
- [ ] You have searched the repository for any relevant issues or PRs.
- [ ] Any category you are creating has the minimum requirement of 3 items.

You can view, comment on, or merge this pull request online at:

  https://github.com/Kickball/awesome-selfhosted/pull/898

-- Commit Summary --

  * Added anchr.io and http2-serverpush-proxy
  * Fix HRM formatting
  * lowercase resources in link
  * Merge pull request #889 from Kickball/hrm-fix
  * Add REDAXO
  * Update AUTHORS file (#890)
  * Move Anchr to Misc Category
  * Merge pull request #859 from Kickball/add-ah
  * Changed REDAXO CMS description
  * Merge pull request #893 from fuerbringer/redaxo
  * Add savepad and scri.ch
  * fix license/lang

-- File Changes --

    D AUTHORS (204)
    A AUTHORS.md (102)
    M README.md (11)

-- Patch Links --

https://github.com/Kickball/awesome-selfhosted/pull/898.patch
https://github.com/Kickball/awesome-selfhosted/pull/898.diff

-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/Kickball/awesome-selfhosted/pull/898

**Pull request closed without merging**
