### PR TITLE
Add edx

### PR DESCRIPTION
**Pull request by NamPNQ**

### CODE REVIEW

**Comment by Kickball** [comment]
I believe the proper format for this should be:

[edX](https://edx.org) - The Open edX platform is open-source code that powers edx.org. ([Source code](https://github.com/edx/)) `AGPLv3` `Python`

But I'd like to see what @nodiscc thinks.

**Comment by NamPNQ** [comment]
@Kickball Tks for feedback, updated format

**Comment by nodiscc** [comment]
The correct format is

    `AGPLv3` `Python`

**Comment by Kickball** [comment]
@NamPNQ any progress on the formatting fixes?

**Comment by Kickball** [comment]
Moved to #409 because of inactivity.

**Pull request closed without merging**
