### PR TITLE
ASTPP

### PR DESCRIPTION
**Pull request by Mancy**
Open Source VoIP Billing Solution for Freeswitch

### CODE REVIEW

**Comment by Mancy** [comment]
@nodiscc As i can see, this is not the case with Freepbx and FusionPBX
maybe ASTPP should be moved to the IPBX section instead?

**Comment by nodiscc** [comment]
@Mancy you are right, basically Asterisk and FreeSWITCH should be moved to IPBX section and this would be a good way to list software based on them:

#### IPBX

- Asterisk
  - Freepbx
- FreeSWITCH
  - ASTPP
  - FusionPBX

Can you move the items as I suggested?

**Comment by nodiscc** [comment]
ping @Mancy

**Comment by Mancy** [comment]
@nodiscc 
I have just moved the ASTPP to IPBX category since both asterisk and Freeswitch are SIP, and thus i am confused to move them to IPBX

**Comment by nodiscc** [comment]
@Mancy You are right... Now I'm wondering about merging these sections into a single `SIP/IPBX` section. There is overlap between all of these projects...

**Comment by Mancy** [comment]
Alright I will merge the two sections, as a non-nested list, since it's a bit complicated to nest the list, for example Kamailio sometimes used with Asterisk or FreeSwitch

**Pull request merged**
