### PR TITLE
Added "Chevereto Free" in Photo and Video Galleries

### PR DESCRIPTION
**Pull request by rodolfoberrios**
Added "Chevereto Free" in Photo and Video Galleries.

### CODE REVIEW

**Comment by AndyR207** [comment]
[Chevereto (Free version)](https://chevereto.com/free/) - A powerful and fast image hosting script that allows you to create your very own full featured image hosting website in just minutes. ([Demo](http://demo.chevereto.com/), [Source Code](https://github.com/Chevereto/Chevereto-Free)) `PHP`

**Comment by nodiscc** [comment]
> Permission is granted to anyone to use this software for any purpose except for distribution or re-distribution in its original and/or modified form. Any third-party distribution or re-distribution including but not limited to hosted applications based on the software must be approved by the copyright owner. The software is offered on an “as-is” basis and no warranty, either expressed or implied, is given.

https://en.wikipedia.org/wiki/Free_software:

> computer software that gives users the freedom to run the software for any purpose as well as to study, change, and distribute the software and any adapted versions.

I think this should go in non-free.md

**Comment by rodolfoberrios** [comment]
Is free as free beer. The description of this github repo never mentioned that the software must be free as free speech. This is a common debate when you use the word "free".

Chevereto also has an Open Source version which seems to fill your free speech thing.

**Comment by nodiscc** [comment]
Yes https://github.com/Chevereto/Chevereto-2.X is released under MIT license (suitable for the main list). Feel free to reopen this pull request with one or both versions added to the correct files.

**Pull request closed without merging**
