### PR TITLE
Added MkDocs

### PR DESCRIPTION
**Pull request by Aisbergg**
A static site generator for building project documentation

### CODE REVIEW

**Comment by nodiscc** [comment]
> A static site generator

We don't list them: https://github.com/Kickball/awesome-selfhosted#static-site-generators

https://github.com/Kickball/awesome-selfhosted/pulls?q=is%3Aclosed%20static
https://github.com/Kickball/awesome-selfhosted/pull/484

You can use the search functionality to check if an entry has already been submitted.

**Comment by Aisbergg** [comment]
In the category `Documentation Generators` are more of those static site generators listed. *MkDOcs* follows the same principals as *ReadTheDocs* and *MdWiki*. It also comes with an integrated server, that is looking for file changes and serves the generated conetet.

**Comment by nodiscc** [comment]
@Aisbergg the goal is to avoid duplication of effort. As you can see MkDocs and Mdwiki are already listed at https://staticsitegenerators.net/ so it's ok to remove those from here (can you do it?). I'd agree to also remove ReadTheDocs, but it needs to be ported to staticsitegenerators.net first (https://github.com/bevry/staticsitegenerators-list/edit/master/list.yaml)

**Comment by Aisbergg** [comment]
@nodiscc I will take care of it. I think a reference to the `Static site generators`  in the `Documentation Generators` section would be reasonable, because most user expecting the documentation apps to be there. (At least I did)

**Comment by Aisbergg** [comment]
See #620

**Pull request closed without merging**
