### PR TITLE
Update README URLs based on HTTP redirects

### PR DESCRIPTION
**Pull request by m1guelpf**
### GitHub Corrected URLs 
Was | Now 
--- | --- 
https://github.com/HabitRPG/habitrpg | https://github.com/HabitRPG/habitica 
https://github.com/TelescopeJS/Telescope | https://github.com/VulcanJS/Vulcan 
https://github.com/adobo/agendav | https://github.com/agendav/agendav 
https://github.com/andris9/mailtrain | https://github.com/Mailtrain-org/mailtrain 
https://github.com/andryyy/mailcow | https://github.com/mailcow/mailcow 
https://github.com/cantino/huginn | https://github.com/huginn/huginn 
https://github.com/e14n/pump.io | https://github.com/pump-io/pump.io 
https://github.com/feross/bittorrent-tracker | https://github.com/webtorrent/bittorrent-tracker 
https://github.com/feross/instant.io | https://github.com/webtorrent/instant.io 
https://github.com/hanzz/spectrum2 | https://github.com/SpectrumIM/spectrum2 
https://github.com/idno/idno | https://github.com/idno/Known 
https://github.com/ipfspics/server | https://github.com/ipfspics/ipfspics-server 
https://github.com/j8r/DPlatform | https://github.com/DFabric/DPlatform-ShellCore 
https://github.com/jasonmunro/hm3 | https://github.com/jasonmunro/cypht 
https://github.com/jkbrzt/cloudtunes | https://github.com/jakubroztocil/cloudtunes 
https://github.com/ldleman/Leed | https://github.com/LeedRSS/Leed 
https://github.com/mauricesvay/moonmoon | https://github.com/moonmoon/moonmoon 
https://github.com/novavex/textpad | https://github.com/fendatr/textpad 
https://github.com/open-classifieds/open-eshop | https://github.com/belherdigital/open-eshop 
https://github.com/open-classifieds/openclassifieds2 | https://github.com/yclas/yclas 
https://github.com/openhab/openhab | https://github.com/openhab/openhab1-addons 
https://github.com/plainmade/unmark | https://github.com/cdevroe/unmark 
https://github.com/pymedusa/SickRage | https://github.com/pymedusa/Medusa 
https://github.com/remie/YouTransfer | https://github.com/YouTransfer/YouTransfer 
https://github.com/rolandgeider/wger | https://github.com/wger-project/wger 
https://github.com/sebsauvage/rss-bridge | https://github.com/RSS-Bridge/rss-bridge 
https://github.com/socketubs/leselys | https://github.com/toxinu/leselys 
https://github.com/ssddanbrown/BookStack | https://github.com/BookStackApp/BookStack 
https://github.com/timovn/blogotext | https://github.com/BlogoText/blogotext 
https://github.com/tonioo/modoboa | https://github.com/modoboa/modoboa 
https://github.com/torchbox/wagtail | https://github.com/wagtail/wagtail 
https://github.com/whitef0x0/tellform | https://github.com/tellform/tellform 
https://github.com/woothemes/woocommerce | https://github.com/woocommerce/woocommerce 

### HTTPS Corrected URLs 
Was | Now 
--- | --- 
http://1pxsolidblack.pl/jarr-en.html | https://1pxsolidblack.pl/jarr-en.html 
http://blog.zx2c4.com/567 | https://blog.zx2c4.com/567 
http://cypht.org/index.html | https://cypht.org/index.html 
http://demo.phproject.org/ | https://demo.phproject.org/ 
http://demo.publify.co/ | https://demo.publify.co/ 
http://demo.visualcaptcha.net/ | https://demo.visualcaptcha.net/ 
http://diamantedesk.com/ | https://diamantedesk.com/ 
http://diamantedesk.com/demo/ | https://diamantedesk.com/demo/ 
http://droppy.silverwind.io/ | https://droppy.silverwind.io/ 
http://emby.media/ | https://emby.media/ 
http://file.pizza/ | https://file.pizza/ 
http://fluxbb.org/ | https://fluxbb.org/ 
http://framanews.org/ | https://framanews.org/ 
http://freshrss.org/ | https://freshrss.org/ 
http://getdirectus.com/ | https://getdirectus.com/ 
http://git.exim.org/exim.git | https://git.exim.org/exim.git 
http://git.freepbx.org/projects/FREEPBX | https://git.freepbx.org/projects/FREEPBX 
http://git.tuxfamily.org/galette/galette.git/ | https://git.tuxfamily.org/galette/galette.git/ 
http://github.com/nordaaker/convos | https://github.com/nordaaker/convos 
http://goaccess.io/ | https://goaccess.io/ 
http://habitica.com/ | https://habitica.com/ 
http://hastebin.com/ | https://hastebin.com/ 
http://hastebin.com/about.md | https://hastebin.com/about.md 
http://ihatemoney.org/ | https://ihatemoney.org/ 
http://kanboard.net/ | https://kanboard.net/ 
http://keeper.nunux.org/ | https://keeper.nunux.org/ 
http://keithp.com/calypso/ | https://keithp.com/calypso/ 
http://keithp.com/cgi-bin/gitweb.cgi?p=calypso.git;a=tree | https://keithp.com/cgi-bin/gitweb.cgi?p=calypso.git;a=tree 
http://koel.phanan.net/ | https://koel.phanan.net/ 
http://lehollandaisvolant.net/blogotext/ | https://lehollandaisvolant.net/blogotext/ 
http://lehollandaisvolant.net/tout/oranjeproxy/ | https://lehollandaisvolant.net/tout/oranjeproxy/ 
http://libresonic.org/ | https://libresonic.org/ 
http://livehelperchat.com/ | https://livehelperchat.com/ 
http://lychee.electerious.com/ | https://lychee.electerious.com/ 
http://mailcatcher.me/ | https://mailcatcher.me/ 
http://mftp.live/ | https://mftp.live/ 
http://mistserver.org/ | https://mistserver.org/ 
http://modoboa.org/en/ | https://modoboa.org/en/ 
http://modx.com/ | https://modx.com/ 
http://niltalk.com/ | https://niltalk.com/ 
http://nodered.org/ | https://nodered.org/ 
http://opensource.org/licenses/Artistic-2.0 | https://opensource.org/licenses/Artistic-2.0 
http://opensource.org/licenses/CPAL-1.0 | https://opensource.org/licenses/CPAL-1.0 
http://opensource.org/licenses/ECL-2.0 | https://opensource.org/licenses/ECL-2.0 
http://opensource.org/licenses/LGPL-2.1 | https://opensource.org/licenses/LGPL-2.1 
http://opensource.org/licenses/LGPL-3.0 | https://opensource.org/licenses/LGPL-3.0 
http://opensource.org/licenses/MIT | https://opensource.org/licenses/MIT 
http://opensource.org/licenses/ZPL-2.0 | https://opensource.org/licenses/ZPL-2.0 
http://photos.jasondonenfeld.com/ | https://photos.jasondonenfeld.com/ 
http://phpaste.sourceforge.io/ | https://phpaste.sourceforge.io/ 
http://posativ.org/isso/ | https://posativ.org/isso/ 
http://reader.nunux.org/ | https://reader.nunux.org/ 
http://readerself.com/ | https://readerself.com/ 
http://redaxscript.com/ | https://redaxscript.com/ 
http://repos.goffi.org/libervia | https://repos.goffi.org/libervia 
http://repos.goffi.org/sat | https://repos.goffi.org/sat 
http://selfoss.aditu.de/ | https://selfoss.aditu.de/ 
http://snowplowanalytics.com/ | https://snowplowanalytics.com/ 
http://sourceforge.net/projects/minidlna/ | https://sourceforge.net/projects/minidlna/ 
http://taskboard.matthewross.me/ | https://taskboard.matthewross.me/ 
http://textpattern.co/demo | https://textpattern.co/demo 
http://thelia.net/ | https://thelia.net/ 
http://trac.calendarserver.org/ | https://trac.calendarserver.org/ 
http://trac.edgewall.org/ | https://trac.edgewall.org/ 
http://trigger-happy.eu/ | https://trigger-happy.eu/ 
http://visualcaptcha.net/ | https://visualcaptcha.net/ 
http://wide.b3log.org/signup | https://wide.b3log.org/signup 
http://wiki.goffi.org/wiki/Libervia/en | https://wiki.goffi.org/wiki/Libervia/en 
http://www.afterlogic.org/webmail-lite | https://www.afterlogic.org/webmail-lite 
http://www.couchcms.com/ | https://www.couchcms.com/ 
http://www.davical.org/ | https://www.davical.org/ 
http://www.dovecot.org/ | https://www.dovecot.org/ 
http://www.horde.org/ | https://www.horde.org/ 
http://www.kamailio.org/w/ | https://www.kamailio.org/w/ 
http://www.koding.com/ | https://www.koding.com/ 
http://www.mattermost.org/ | https://www.mattermost.org/ 
http://www.monstaftp.com/ | https://www.monstaftp.com/ 
http://www.musicpd.org/ | https://www.musicpd.org/ 
http://www.mybb.com/ | https://www.mybb.com/ 
http://www.otrs.com/ | https://www.otrs.com/ 
http://www.phproject.org/ | https://www.phproject.org/ 
http://www.sendmail.com/sm/open_source/ | https://www.sendmail.com/sm/open_source/ 
http://www.sphido.org/ | https://www.sphido.org/ 
http://www.spip.net/fr | https://www.spip.net/fr 
http://www.vimbadmin.net/ | https://www.vimbadmin.net/ 
http://www.vimbadmin.net/demo/auth/login | https://www.vimbadmin.net/demo/auth/login 
http://www.ympd.org/ | https://www.ympd.org/ 

### Other Corrected URLs 
Was | Now 
--- | --- 
http://WikiSuite.org | http://WikiSuite.org/Software 
http://allegro.tech/tipboard/ | http://lightspeed1.nsnet.net/access/web?id=13127b03-6bd9-11e7-8b13-00e0ed148814 
http://apostrophenow.org/ | http://apostrophecms.org/ 
http://baikal-server.com/ | http://sabre.io/baikal/ 
http://bumpy-booby.derivoile.fr/ | http://bumpy-booby.derivoile.fr/default/dashboard 
http://cvsweb.openbsd.org/cgi-bin/cvsweb/src/usr.bin/ssh | http://cvsweb.openbsd.org/cgi-bin/cvsweb/src/usr.bin/ssh/ 
http://cyrusimap.org/ | https://www.cyrusimap.org/ 
http://cytu.be | http://lightspeed1.nsnet.net/access/web?id=09479e9c-6bd9-11e7-8b13-00e0ed148814 
http://demo.apostrophenow.com/ | http://demo.apostrophenow.com/spinup 
http://demo.ilias.de | https://demo.ilias.de/ 
http://demo.kopano.com | https://demo.kopano.com/ 
http://demo.mayan-edms.com | http://demo.mayan-edms.com/authentication/login/?next=/ 
http://demo.microweber.org/ | http://demo2.microweber.com/api/user_login?username=demomic6&password=7Mp1Ve32vk&redirect=http://demo2.microweber.com/versace?editmode=y 
http://demo.prestashop.com/ | http://demo.prestashop.com/en/ 
http://demo.rainloop.net/ | https://mail.rainloop.net/ 
http://demo.sogo.nu/SOGo/ | http://demo.sogo.nu/SOGo/index 
http://demos.subrion.com | http://demos.subrion.org/ 
http://easybook-project.org/ | http://lightspeed1.nsnet.net/access/web?id=0a579b30-6bd9-11e7-8b13-00e0ed148814 
http://fileshelter.suroot.com/ | http://lightspeed1.nsnet.net/access/web?id=0022e77e-6bd9-11e7-8b13-00e0ed148814 
http://friendica.com/ | http://www.friendica.com/ 
http://georgeosddev.github.com/markdown-edit/ | http://georgeosddev.github.io/markdown-edit/ 
http://gitlab.org/ | https://about.gitlab.com/ 
http://groovebasin.com/ | http://lightspeed1.nsnet.net/access/web?id=086c2c24-6bd9-11e7-8b13-00e0ed148814 
http://guac-dev.org/ | http://guacamole.incubator.apache.org/ 
http://leed.idleman.fr | http://lightspeed1.nsnet.net/access/web?id=fd3bff7d-6bd8-11e7-8b13-00e0ed148814 
http://materialpoll.tk | http://lightspeed1.nsnet.net/access/web?id=153ed33d-6bd9-11e7-8b13-00e0ed148814 
http://mediadrop.net/ | https://mediadrop.video/ 
http://mediagoblin.org | https://mediagoblin.org/ 
http://oddnetworks.com | https://oddnetworks.com/ 
http://odoo.com | https://www.odoo.com/ 
http://oxidforge.org | https://oxidforge.org/ 
http://p.thorsen.pm/ | https://ssl.thorsen.pm/paste/ 
http://phabricator.org/ | https://www.phacility.com/ 
http://phpaste.sourceforge.net/demo | https://phpaste.sourceforge.io/demo 
http://playground.xwiki.org | http://playground.xwiki.org/xwiki/bin/view/Main/WebHome 
http://poffer.gabinaureche.com | https://poffer.gabinaureche.com/ 
http://projet.idleman.fr/blazekiss/ | http://lightspeed1.nsnet.net/access/web?id=1ed0d3a4-6bd9-11e7-8b13-00e0ed148814 
http://publify.co/ | https://github.com/publify/publify 
http://redash.io | https://redash.io/ 
http://restya.com/board/demo.html | http://restya.com/board/demo 
http://retroshare.org | http://retroshare.sourceforge.net 
http://riot.im | https://about.riot.im 
http://slimta.org | http://slimta.org/en/latest/ 
http://wheatbin.com/ | http://www.wheatbin.com/ 
http://wikisuite.org/Source | http://wikisuite.org/Source-Code 
http://www.cerberusweb.com/ | http://cerb.ai/ 
http://www.cerberusweb.com/license | http://cerb.ai/license 
http://www.citadel.org/ | http://www.citadel.orgdoku.php 
http://www.egroupware.org/ | http://www.egroupware.org/en/ 
http://www.elabftw.net | https://www.elabftw.net/ 
http://www.freepbx.org | https://www.freepbx.org/ 
http://www.ilias.de | https://www.ilias.de/ 
http://www.oxwall.org/ | https://www.oxwall.com 
http://www.paraio.org | http://paraio.org/ 
http://www.privoxy.org | http://lightspeed1.nsnet.net/access/web?id=16016799-6bd9-11e7-8b13-00e0ed148814 
http://www.resourcespace.org | http://www.resourcespace.com/ 
http://www.resourcespace.org/svn | http://www.resourcespace.com/svn 
http://www.resourcespace.org/trial | http://www.resourcespace.com/trial 
http://www.salut-a-toi.org/ | https://salut-a-toi.org/ 
http://www.sogo.nu/ | https://sogo.nu/ 
http://www.squid-cache.org/ | http://lightspeed1.nsnet.net/access/web?id=16083545-6bd9-11e7-8b13-00e0ed148814 
http://www.subrion.org | https://subrion.org/ 
http://www.wtfpl.net/about/ | http://lightspeed1.nsnet.net/access/web?id=22b1030b-6bd9-11e7-8b13-00e0ed148814 
http://www.xwiki.org | http://www.xwiki.org/xwiki/bin/view/Main/WebHome 
http://yacy.net/en/index.html | http://lightspeed1.nsnet.net/access/web?id=168af364-6bd9-11e7-8b13-00e0ed148814 
http://yourls.org/ | http://lightspeed1.nsnet.net/access/web?id=1e8fc9de-6bd9-11e7-8b13-00e0ed148814 
https://app.invoiceninja.com/invoices/create | https://app.invoiceninja.com/login 
https://avatar.playat.ch:1000/ | https://demo.thelounge.chat 
https://banu.com/tinyproxy/ | https://tinyproxy.github.io/ 
https://bitbucket.org/zhb/iredmail/commits/ | https://bitbucket.org/zhb/iredmail/commits/all 
https://cozy.io | https://cozy.io/en/ 
https://creativecommons.org/about/cc0/ | http://creativecommons.org/share-your-work/public-domain/cc0/ 
https://demo.elabftw.net | https://demo.elabftw.netexperiments.php 
https://demo.invoiceplane.com | https://demo.invoiceplane.com/index.php/sessions/login 
https://demo.odoo.com/ | https://master.odoo.com/saas_master/demo/ 
https://demo.redash.io | https://demo.redash.io/login?next=https%3A%2F%2Fdemo.redash.io%2F 
https://demo.sandstorm.io/ | https://oasis.sandstorm.io/demo 
https://demo.sandstorm.io/appdemo/h37dm17aa89yrd8zuqpdn36p6zntumtv08fjpu8a8zrte7q1cn60 | https://oasis.sandstorm.io/appdemo/h37dm17aa89yrd8zuqpdn36p6zntumtv08fjpu8a8zrte7q1cn60 
https://docs.services.mozilla.com/howtos/run-fxa.html | https://mozilla-services.readthedocs.io/howtos/run-fxa.html 
https://docs.services.mozilla.com/howtos/run-sync-1.5.html | https://mozilla-services.readthedocs.io/howtos/run-sync-1.5.html 
https://firefly-iii.nder.be/ | https://firefly-iii.nder.be/login 
https://gitea.io | https://gitea.io/en-US/ 
https://gitlab.com/ | https://about.gitlab.com/ 
https://graphhopper.com/ | https://www.graphhopper.com/ 
https://hubzilla.org | https://project.hubzilla.org/ 
https://jenkins-ci.org/ | https://jenkins.io/index.html 
https://jitsi.org/Projects/JitsiMeet | https://jitsi.org/jitsi-meet/ 
https://jitsi.org/Projects/JitsiVideobridge | https://jitsi.org/jitsi-videobridge/ 
https://jsxc.org | https://www.jsxc.org/ 
https://leanote.com/note | https://leanote.com/login 
https://mastodon.social | https://mastodon.social/about 
https://os.js.org/ | https://www.os-js.org/ 
https://phabricator.wikimedia.org/diffusion/MW/ | https://phabricator.wikimedia.org/source/mediawiki/ 
https://phplist.org | https://www.phplist.org/ 
https://podupti.me/go.php | https://loma.ml 
https://pretix.eu/ | https://pretix.eu/about/en/ 
https://projects.miguelpiedrafita.com/LicAPI | https://projects.miguelpiedrafita.com/LicAPI/ 
https://seacloud.cc/demo | https://seacloud.cc/demo/ 
https://serposcope.serphacker.com/ | https://serposcope.serphacker.com/en/ 
https://snipt.net/ | https://github.com/nicksergeant/snipt 
https://sprut.io | https://sprut.io/en 
https://stash.kopano.io | https://stash.kopano.io/dashboard 
https://stash.z-hub.io/projects/ZP/repos/z-push | https://stash.z-hub.io/projects/ZP/repos/z-push/browse 
https://tiki.org | http://tiki.org/tiki-index.php 
https://try.rhodecode.com/ | https://code.rhodecode.com/ 
https://turtl.it/ | https://turtlapp.com/ 
https://u.pste.pw | https://pste.pw/ 
https://vanillaforums.org/ | https://vanillaforums.com/en/software 
https://weblate.org | https://weblate.org/en/ 
https://wger.de | https://wger.de/en/ 
https://wger.de/ | https://wger.de/en/ 
https://www.admidio.org/demo/ | https://www.admidio.org/demo/adm_program/modules/announcements/announcements.php 
https://www.bestpractical.com/rt/ | https://bestpractical.com/rt/ 
https://www.cups.org/software.php | https://www.cups.org/software.html 
https://www.humhub.org/ | https://www.humhub.org/en 
https://www.impresspages.org/demo | http://69042.cloud.impresspages.org?pa=CloudService.autologin&key=hLlqljhAqxuEibLuKlmZq2qrrtXetteC6pSiz1IQn3kw4XQF84toXLHe5tjp 
https://www.modernpaste.com | http://modernpaste.com/ 
https://www.mozilla.org/MPL/2.0/index.txt | https://www.mozilla.org/media/MPL/2.0/index.txt 
https://www.pimcore.org/ | https://www.pimcore.org/en 
https://www.prestashop.com/ | https://www.prestashop.com/en 
https://www.privacytools.io/ | https://privacytoolsio.github.io/privacytools.io/ 
https://www.redaxo.org | https://redaxo.org/ 
https://www.sendmail.com/pdfs/open_source/sendmail_license.pdf | https://www.proofpoint.com/us/products/sendmail-sentrion/ 
https://www.shuup.com/ | https://www.shuup.com/en/ 
https://www.sonerezh.bzh/demo/ | https://www.sonerezh.bzh/demo/login 
https://www.tine20.org | http://www.tine20.com/willkommen-community/ 
https://www.wallabag.org | https://www.wallabag.org/en 
https://www.webtrees.net | https://www.webtrees.net/index.php/en/ 
https://www.woothemes.com/woocommerce/ | https://woocommerce.com/woocommerce/ 
https://www.wtfdyu.me/ | https://wtfdyu.me:443/

### CODE REVIEW

**Comment by danger-awesome-Selfhosted** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Found 29 link issues</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
13 | Dupe | https://github.com/jchampemont/WTFDYUM 
23 | [404](https://httpstatuses.com/404) | https://keithp.com/cgi-bin/gitweb.cgi?p=calypso.git;a=tree 
24 | [404](https://httpstatuses.com/404) | https://about.gitlab.com/davical-project/davical 
24 | Dupe | https://about.gitlab.com/ 
33 | Error | http://www.citadel.orgdoku.php <br> getaddrinfo: Name or service not known
70 | Error | https://demo.elabftw.netexperiments.php <br> getaddrinfo: Name or service not known
74 | [503](https://httpstatuses.com/503) | https://demo.publify.co/ 
74 | Dupe | https://github.com/publify/publify 
93 | Error | http://lightspeed1.nsnet.net/access/web?id=fd3bff7d-6bd8-11e7-8b13-00e0ed148814 <br> getaddrinfo: Name or service not known
99 | [404](https://httpstatuses.com/404) | https://tt-rss.org/gitlab/fox/tt-rss 
107 | Error | http://lightspeed1.nsnet.net/access/web?id=0022e77e-6bd9-11e7-8b13-00e0ed148814 <br> getaddrinfo: Name or service not known
108 | Error | https://ipfs.pics/ <br> Connection refused - connect(2) for "ipfs.pics" port 443
115 | Error | https://osjsv2.0o.no/ <br> SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
127 | Error | http://lightspeed1.nsnet.net/access/web?id=086c2c24-6bd9-11e7-8b13-00e0ed148814 <br> getaddrinfo: Name or service not known
133 | Error | http://lightspeed1.nsnet.net/access/web?id=09479e9c-6bd9-11e7-8b13-00e0ed148814 <br> getaddrinfo: Name or service not known
138 | Error | http://lightspeed1.nsnet.net/access/web?id=0a579b30-6bd9-11e7-8b13-00e0ed148814 <br> getaddrinfo: Name or service not known
142 | [403](https://httpstatuses.com/403) | https://dev.webtrees.net/demo-stable/index.php?ctype=gedcom&ged=demo 
146 | [500](https://httpstatuses.com/500) | https://invoiceplane.com/ 
159 | Error | http://lightspeed1.nsnet.net/access/web?id=13127b03-6bd9-11e7-8b13-00e0ed148814 <br> getaddrinfo: Name or service not known
160 | [404](https://httpstatuses.com/404) | https://wger.de/en/en// 
165 | Error | http://lightspeed1.nsnet.net/access/web?id=153ed33d-6bd9-11e7-8b13-00e0ed148814 <br> getaddrinfo: Name or service not known
165 | Dupe | https://github.com/nearbycoder/materialpoll 
168 | Error | http://lightspeed1.nsnet.net/access/web?id=16016799-6bd9-11e7-8b13-00e0ed148814 <br> getaddrinfo: Name or service not known
169 | Error | http://lightspeed1.nsnet.net/access/web?id=16083545-6bd9-11e7-8b13-00e0ed148814 <br> getaddrinfo: Name or service not known
173 | Error | http://lightspeed1.nsnet.net/access/web?id=168af364-6bd9-11e7-8b13-00e0ed148814 <br> getaddrinfo: Name or service not known
177 | Dupe | https://code.rhodecode.com/ 
194 | Error | http://lightspeed1.nsnet.net/access/web?id=1e8fc9de-6bd9-11e7-8b13-00e0ed148814 <br> getaddrinfo: Name or service not known
195 | Error | http://lightspeed1.nsnet.net/access/web?id=1ed0d3a4-6bd9-11e7-8b13-00e0ed148814 <br> getaddrinfo: Name or service not known
214 | Error | http://lightspeed1.nsnet.net/access/web?id=22b1030b-6bd9-11e7-8b13-00e0ed148814 <br> getaddrinfo: Name or service not known


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by m1guelpf** [comment]
Fixed issues

**Comment by nodiscc** [comment]
Very appreciated, thanks. However this will be very hard to review, nobody will probably have time to do it. Can you send separate pull requests for separate sections (at most 2-4 sections in a PR)?

**Comment by nodiscc** [comment]
In the first time you can send a pull request containing only HTTP->HTTPS changes. Let's clear this out first.

**Comment by m1guelpf** [comment]
@nodiscc It's automated using https://github.com/dkhamsing/frankenstein, you can give it a run to test.

**Comment by nodiscc** [comment]
There are merge conflicts. Moved to #1120.

**Pull request closed without merging**
