### PR TITLE
Add ReleaseBell

### PR DESCRIPTION
**Pull request by nebulade**
ReleaseBell was written after Sibbell got discontinued.

Thank you for taking the time to work on a PR for Awesome-Selfhosted!

To ensure your PR is dealt with swiftly please check the following:

- [x] Your submissions are formatted according to the following requirements:
        
``- [Name](http://homepage/) - Short description, less than 250 characters. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``

Depends on proprietary services:

``- [Name](http://homepage/) `⚠` - Short description, less than 250 characters. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``

Non-free software in `non-free.md`:

``- [Name](http://homepage/) `⊘ Proprietary` - Short description, less than 250 characters. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `Language` ``

- [x] Your additions are ordered alphabetically.
- [x] Your additions are [Free software](https://en.wikipedia.org/wiki/Free_software), or if not they have been added to [non-free](non-free.md) and marked `⊘ Proprietary`.
- [x] If your additions depend on proprietary services outside the user's control, they must be marked `⚠`.
- [x] Your additions are not already listed at [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin) (IT infrastructure management), [staticgen.com](https://www.staticgen.com/) or [staticsitegenerators.net](https://staticsitegenerators.net/) (static site generators).
- [x] Your additions have their `License` main server-side `Language`/platform/requirement listed.
- [x] Any licenses you have added are in our [list of licenses](https://github.com/Kickball/awesome-selfhosted/blob/master/README.md#list-of-licenses).
- [x] You have searched the repository for any relevant [issues](https://github.com/Kickball/awesome-selfhosted/issues) or [PRs](https://github.com/Kickball/awesome-selfhosted/pulls), including closed ones.
- [x] If the main link of your addition points to the program's source code, there is no need to add a duplicate _Source Code_ link. The _Demo_ and _Clients_ links are not mandatory.
- [x] Any category you are creating has the minimum requirement of 3 items. If not, your addition may be inserted into `Misc/Other`.
- [x] Any software project you are adding to the list is actively maintained.

### CODE REVIEW

**Comment by nodiscc** [comment]
What is the point of this tool? You can subscribe to Github release announcements for any repo. RSS feeds are also available.

**Comment by nebulade** [comment]
Following its predecessor sibbell it will further gather releases from other sources (like gitlab) rather than only github.

**Comment by nodiscc** [comment]
Seems like we're having [this discussion](https://github.com/Kickball/awesome-selfhosted/pull/1378) again. Github/Gitlab both features to notify you of new releases, whether you have an account (watched repos) or not (RSS/ATOM).

Since we merged the other PR I see no reason to reject this one - but all of this looks a bit like NIH syndrome to me.

Waiting for approval of other maintainers, @nebulade if you could clarify why I should install this tool instead of relying on native mail notifications/RSS/Alerthub/rss2email..., your input is welcome.

**Comment by evaryont** [comment]
There is value in having a centralized and convenient place to see release notifications. Especially if even more sources get added -- Linux repos, SourceForge, src.ht, etc. 

I'm unsure if we should start filtering additions to list list due to some perceived lack of value/originality -- see the 'redundancy in the RSS section for an example where that could be easily go awry. To me, this list is a description of what's out there, not a recommendation or curated list (outside of maintenance).

**Comment by nodiscc** [comment]
> I'm unsure if we should start filtering additions to list list due to some perceived lack of value/originality

No, we should not. I was just curious why this was a thing, while GH/Gitlab already provide ways to centralize notifications (mail, rss).

Moreover the other sources you listed (linux repos, sourceforge...) do provide RSS feeds, while ReleaseBell doesn't seem to work with them at all.

There are no other requirements than those listed in CONTRIBUTING.md. awesome-sysadmin has a [guideline](https://github.com/n1trux/awesome-sysadmin/blob/master/.github/PULL_REQUEST_TEMPLATE.md#why-it-is-awesome) that requires submitters to write one or two lines explaining why the software is awesome - I don't think we should go this way. But using the Pull Request comments as a sort of review/discussion thread for the application could be interesting (I think it was mentioned in https://github.com/Kickball/awesome-selfhosted/issues/1684)

**Comment by evaryont** [comment]
> No, we should not. I was just curious why this was a thing, while GH/Gitlab already provide ways to centralize notifications (mail, rss).

Perhaps this was me reading too much into your text, but it felt like to me your text implied something along the lines of "this probably doesn't belong but I'll approve it because it doesn't violate any rules". Dunno if I'm in a bad mood or if the text wasn't clear enough about intentions.

**Comment by nodiscc** [comment]
> this probably doesn't belong but I'll approve it because it doesn't violate any rules

Something like this yeah :)

Curating new additions more is a frequent request + I don't clearly see the value of this tool (@nebulade could clear this up in 1 or 2 lines...) -> I am reluctant to merge it.

But rules are rules - unless you think they should be changed. I don't see a way to further filter additions, that wouldn't be arbitrary. @evaryont thank you again for helping with the reviews

**Pull request merged**
