### PR TITLE
Add eLabFTW to the list

### PR DESCRIPTION
**Pull request by NicolasCARPi**
Hello,

This PR is to add elabftw to the list.

Regards,
~Nico

### CODE REVIEW

**Comment by nodiscc** [comment]
Thanks. I don't know if CMS is the best category though.

**Comment by NicolasCARPi** [comment]
Yeah I'm not sure either. But as you don't have an ELN category, I put it here. Feel free to move it :)

**Comment by nodiscc** [comment]
On the second look it indeed _is_ a CMS, with a specific purpose. The [ELN](https://en.wikipedia.org/wiki/Electronic_lab_notebook) article on Wikipedia for those curious about it. Good to merge, merci!

**Comment by NicolasCARPi** [comment]
De rien ;)

**Comment by Kickball** [comment]
We don't list the database backend used, so please remove the /MySQL from the language section.

**Comment by nodiscc** [comment]
True. Thanks for the review @Kickball

**Comment by NicolasCARPi** [comment]
Removed.

**Comment by nodiscc** [comment]
Please use AGPLv3 like every other AGPL entry in the list. Squashing your commits would be appreciated.

**Comment by NicolasCARPi** [comment]
AGPLv3 added, commits squashed :)

**Pull request merged**
