### PR TITLE
Pull Request 16, 32, 33 rebased and edited, more fixes

### PR DESCRIPTION
**Pull request by nodiscc**
Rebased and splitted https://github.com/Kickball/awesome-selfhosted/pull/16 #32 in several commits since it didn't merge anymore. Thanks @Kovah @stevesbrain 

I have removed your additions for `no license`; we should re-check these projects (https://github.com/Kickball/awesome-selfhosted/pull/16/files) and mark them as `⊘ Proprietary` if there is really no license.

### CODE REVIEW

**Comment by nodiscc** [comment]
It also merges https://github.com/Kickball/awesome-selfhosted/pull/33 since it conflicted, and a small fix for the music players section.

**Comment by nodiscc** [comment]
I've shortened the license names for GPL and AGPL

**Comment by nodiscc** [comment]
This changes `⊘ Closed Source` to `⊘ Proprietary` (in case the software is Open Source but non-free, i.e it doesn't allow you to _run the software for any purpose as well as to study, modify, and distribute the original software and the adapted versions_). The proprietary tag should appear right next to the software name.

**Comment by Kickball** [comment]
Everything looks good here.

The repo is coming along nicely :)

**Pull request merged**
