### PR TITLE
Added our list

### PR DESCRIPTION
**Pull request by rosehosting**
Thank you for taking the time to work on a PR for Awesome-selfhosted!

To ensure your PR is dealt with swiftly please check the following:

- [x] Your submissions are formatted according to the guidelines. 
        
    ``[Name](http://homepage/) - Short description. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code)) `License` `Language```
- [x] Your additions are ordered alphabetically.
- [x] Your additions are [free software](https://en.wikipedia.org/wiki/Free_software), or if not they have been added to [non-free](non-free.md).
- [x] Any licenses you have added are in our [list of licenses](https://github.com/Kickball/awesome-selfhosted/blob/master/README.md#list-of-licenses).
- [x] You have searched the repository for any relevant issues or PRs.
- [x] Any category you are creating has the minimum requirement of 3 items.

We published an article - a list of more than 100 self-hosted apps as alternatives to popular online services and added it in the External links.

### CODE REVIEW

**Comment by nodiscc** [comment]
I'm against adding this or we would end up adding every blog post about self-hosted software out there.

**Comment by Kickball** [comment]
I think it should be alright to sites completely dedicated to selfhosting, but individual blog posts will cause problems as @nodiscc highlighted above.

**Comment by AndyR207** [comment]
I don't think it should appear as a list item, however what about in the external links section?

**Comment by n8225** [comment]
I agree with nodiscc.  If the site was nothing but self hosted I would be fine with it.  But it's a blog post on a paid VPS site.

**Comment by nodiscc** [comment]
https://reddit.com/r/selfhosted is a better place for such articles. Closing, feel free to reopen.

**Pull request closed without merging**
