### PR TITLE
add PrestaShop (self hosted e-commerce solution) into CMS section

### PR DESCRIPTION
**Pull request by marcpicaud**

### CODE REVIEW

**Comment by nodiscc** [comment]
Do we need a separate section for this (or a sub-section of CMS)? I know there are a few E-Shop solutions out there.

**Comment by Kickball** [comment]
I think the best thing would be to add E-Shops as a sub section of CMSes.

**Comment by nodiscc** [comment]
@marcpicaud thanks, can you rename that section to `E-commerce`? Sorry for being picky :+1:

**Comment by marcpicaud** [comment]
Done :) no problem @nodiscc , thanks for maintaining this repo :+1:

**Pull request merged**
