### PR TITLE
WikiSuite

### PR DESCRIPTION
**Pull request by daniel-lucio**
As requested by Marc Laporte, I added the WikiSuite project

### CODE REVIEW

**Comment by nodiscc** [comment]
Hi @daniel-lucio, thanks you. I think Wikisuite should be in the https://github.com/Kickball/awesome-selfhosted#self-hosting-solutions section. Am I right?

**Comment by daniel-lucio** [comment]
I don't know. Please contact @marclaporte for that discussion

**Comment by nodiscc** [comment]
@daniel-lucio Please fix the entry as suggested. (you are responsible for the patches you submit, not someone else).

**Comment by marclaporte** [comment]
Hi!

That list contains mostly personal servers:

* arkOS "Your personal server sets sail."
* Freedombone: "self-hosted home server"
* FreedomBox: "a ready made personal server"
* Sandstorm: "personal and private clouds."
* Sovereign: "maintain your own private cloud"
* UBOS: "run their own Personal Server"
* YunoHost: "a full VPS per user will be just fine, and we believe is a better way to go."

While this is great for personal usage, you can't manage the information of a typical organization. These are not FLOSS alternatives to Google Apps for Work, Microsoft Office 365 Enterprise E5 and Zoho Suite.

Also, in some cases, it's more about making it easy to install apps than getting these apps to work well together.  I propose that we have a new category with the following guideline:

"The enterprise suite category is for solutions for organizations that cover more than 10 categories in an integrated fashion (ex.: logins work throughout all apps, etc.)".

WikiSuite offers functionality for over 30 categories:
* Analytics
* Blogging Platforms
* Calendar and Address Books
* Communication systems
* Email
* Mail Transfer Agents
* Mail Delivery Agents
* Newsletter management
* Webmail clients
* SIP
* IPBX
* Social Networks and Forums
* XMPP Servers
* Content Management Systems (CMS)
* E-commerce
* Feed Readers
* File transfer/synchronization
* Web based file managers
* Groupware
* Video Streaming
* Note-taking & Editors
* Office Suites
* Password Managers
* Photo and Video Galleries
* Polls and Events
* Project Management
* Bug Trackers
* Task management/To-do lists
* Ticketing
* VPN
* Web servers
* Wikis
* Self-hosting Solutions

What do you think?

Thanks!

**Comment by nodiscc** [comment]
Hi @marclaporte thanks for your feedback.

 * I'd rather not have a new category that contains a single entry. @Kickball @AndyR207 please advise.
 * Note that some self-hosting solutions already support single sign-on (Yunohost comes to mind), and many offer more than 10 services (yunohost, sovereign...). So in this regard WS is not an exception.
 * I first thought about placing WikiSuite under the Groupware section, but Self-Hosting Solutions seems to be a better fit.
 * Update: I can't find the source code for the base system using the link you provided. Where is the source for WikiSuite? I can find the individual web applications, but not for your own product. Can you help?
 * Update: The install instructions point to 1. How to install ClearOS 2+. How to install provided services and applications on ClearOS. Are there other components (what does WikiSuite itself provide? A link to the actual source would help)
 * The last tag is for _Main Language/Platform_. Since WS seems to require a custom, dedicated OS (ClearOS), please specify it as the platform.

**Comment by marclaporte** [comment]
"I'd rather not have a new category that contains a single entry." ->  Agreed. That makes it weird.

"Note that some self-hosting solutions already support single sign-on (Yunohost comes to mind), and many offer more than 10 services (yunohost, sovereign...). They can be used for enterprise deployments. So in this regard WS is not an exception."  -> Super!  So they could move to the Enterprise Suite category :-)   Or maybe there could be a 1st level "Self-hosting Solutions" section and a second level with two sections: 1- Personal Server and 2- Enterprise Suite

"I first thought about placing WikiSuite under the Groupware section, but Self-Hosting Solutions seems to be a better fit."  -> Indeed.

"The description can be updated to something more descriptive if you need to insist on the difference vs. other solutions. (alternative to Google Apps for Work, Microsoft Office 365 Enterprise E5 and Zoho Suite.?)" -> OK.

"Update: I can't find the source code for the base system using the link you provided. Where is the source for WikiSuite? I can find it for the individual web applications/services, but not for your own product. Can you help?" + "Update: The install instructions point to 1. How to install ClearOS 2+. How to install provided services and applications on ClearOS. Are there other components (what does WikiSuite itself provide? A link to the actual source would help)" -> The goal is to do all the code upstream so that it's useful even if you are not using WikiSuite. And for WikiSuite to mostly "just" be configuration. And if we can't do upstream, we do in the ClearOS app, such as: https://github.com/clearos/app-tiki

"The last tag is for Main Language/Platform. Since WS seems to require a specific, dedicated OS (ClearOS), please specify it as the platform." -> Ok, will do.

"Update 2: where is the source code for ClearOS?" ->  Thanks for the question. I added links here: http://wikisuite.org/Source

Thanks!

**Comment by nodiscc** [comment]
https://github.com/daniel-lucio/awesome-selfhosted/pull/1 @daniel-lucio

**Comment by marclaporte** [comment]
@nodiscc  Your adaptation is fine for me. Thank you very much.

**Comment by nodiscc** [comment]
Without reply this PR will be closed in 7 days.

**Comment by Kickball** [comment]
@nodiscc what needs to happen before this can PR be merged?

**Comment by nodiscc** [comment]
@Kickball https://github.com/daniel-lucio/awesome-selfhosted/pull/1/files

**Comment by Kickball** [comment]
Alright, @nodiscc if @daniel-lucio hasn't merged the patch within 3 days (from today) then I'll redo the PR.

**Comment by nodiscc** [comment]
Closing. Please resubmit the changes as discussed in https://github.com/Kickball/awesome-selfhosted/pull/589

**Pull request closed without merging**
