### PR TITLE
Reorganize Contribution Sections of Project

### PR DESCRIPTION
**Pull request by Kickball**
Previously the contributing guidelines were hidden at the bottom of the project page. This PR moves the contributing guidelines and the contributors list to CONTRIBUTING.md

@AndyR207 @nodiscc

### CODE REVIEW

**Comment by AndyR207** [comment]
People have already said they've not seen it. As for the list of contributors, they were together before it seems sensible to keep them together now.

**Comment by nodiscc** [comment]
Ok, why not

 * put contribution guidelines in CONTRIBUTING.md (don't forget to update links from the main README)
 * Put the authors list in an AUTHORS file, link to it from a short text in the license section `The list of contributors can be found [here](AUTHORS)`
 * The license is already in it's own file and properly linked.

**Comment by nodiscc** [comment]
@Kickball ping?

**Comment by Kickball** [comment]
@nodiscc sorry about this, been quite busy lately. 

I'm happy with your suggestions from the 12th of July, I'll implement them in a new PR later today.

Can you check chat.awesome-selfhosted.com when you get chance?

**Pull request closed without merging**
