### PR TITLE
ADD :: Public instance, source code, license & language for 'Gitlab'

### PR DESCRIPTION
**Pull request by vincent-clipet**
Thank you for taking the time to work on a PR for Awesome-selfhosted!

To ensure your PR is dealt with swiftly please check the following:

- [x] Your submissions are formatted according to the guidelines. 
        
    ``[Name](http://homepage/) - Short description. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code)) `License` `Language```
- [x] Your additions are ordered alphabetically.
- [x] Your additions are [free software](https://en.wikipedia.org/wiki/Free_software), or if not they have been added to [non-free](non-free.md).
- [x] Any licenses you have added are in our [list of licenses](https://github.com/Kickball/awesome-selfhosted/blob/master/README.md#list-of-licenses).
- [x] You have searched the repository for any relevant issues or PRs.
- [x] Any category you are creating has the minimum requirement of 3 items.

### CODE REVIEW

**Comment by AndyR207** [comment]
Description needs to be shortened to 250 chars max. Public instance isn't a valid link, please remove it. Source Code needs a capital 'C' in the link title.

**Comment by nodiscc** [comment]
Ok to change `Public instance` to `Demo` ?

**Comment by vincent-clipet** [comment]
Shortened the description, fixed the typo, and changed 'Public Instance' for 'Demo'

**Comment by n8225** [comment]
I think you may have shortened the description a little too much.  How about something similiar to:

>Git repository management, code reviews, issue tracking, activity feeds and wikis.

**Comment by AndyR207** [comment]
#763 resolved this.

**Pull request closed without merging**
