### PR TITLE
Update contributing guidelines.

### PR DESCRIPTION
**Pull request by AndyR207**
Update contributing guidelines.

### CODE REVIEW

**Comment by nodiscc** [comment]
What is the difference between Demo and Example?

**Comment by AndyR207** [comment]
> By the way I have no strong feelings about proper capitalization.

The regex has fairly strong feelings about it though.

**Comment by Kickball** [comment]
7b43cce removes the only use example use case, it can now be completely removed from the guidelines.

We should stick to strict capitalization as per the regex and guidelines.

**Comment by AndyR207** [comment]
893ce1c removes "Example" from the guidelines.

**Comment by nodiscc** [comment]
Looks good, thanks

**Pull request merged**
