### PR TITLE
added PictShare

### PR DESCRIPTION
**Pull request by cavebeat**
@chrisiaut https://github.com/chrisiaut/pictshare
PictShare is a multi lingual, open source image hosting service with a simple resizing and upload API that you can host yourself.

### CODE REVIEW

**Comment by AndyR207** [comment]
Please add a link to the source code, add the license and add the language. Make sure it confirms to the format as described in [contributing section](https://github.com/Kickball/awesome-selfhosted#contributing).

**Comment by cavebeat** [comment]
updated regarding your contributing section

**Comment by Kickball** [comment]
Please add a dash between the name of the project and the description.

**Comment by cavebeat** [comment]
updated

**Comment by Kickball** [comment]
Please capitalize the Code in Source Code, then this commit will be ready to merge.

**Pull request closed without merging**
