### PR TITLE
Add Jekyll static site generator

### PR DESCRIPTION
**Pull request by erimar77**

### CODE REVIEW

**Comment by jalcine** [comment]
Yeah, I was surprised this wasn't on the list!

**Comment by nodiscc** [comment]
I don't think we should start referencing static site generators. These websites https://staticsitegenerators.net/ and https://www.staticgen.com/ do a much better job than us at listing, sorting and comparing them.

A subsection for CMS like this would be great:

## Static Site Generators

See https://staticsitegenerators.net/ and  https://www.staticgen.com/ for detailed listings

**Comment by jalcine** [comment]
Woah, didn't notice about these sites :+1:! I'm more of favor of that now than adding the Jekyll entry.

**Comment by nodiscc** [comment]
@erimar77 can you update your patch? Otherwise I'll do it tomorrow

**Pull request closed without merging**
