### PR TITLE
Add Poffer, update contributing with 3rd-party service warning

### PR DESCRIPTION
**Pull request by Zhouzi**
Poffer is a tool built on top of [Pocket](https://getpocket.com) and [Buffer](https://buffer.com). It makes it easier to write and schedule tweets from the content saved to Pocket.

--

- [x] Your submissions are formatted according to the guidelines.
- [x] Your additions are ordered alphabetically.
- [x] Your additions are [free software](https://en.wikipedia.org/wiki/Free_software), or if not they have been added to [non-free](non-free.md).
- [x] Any licenses you have added are in our [list of licenses](https://github.com/Kickball/awesome-selfhosted/blob/master/README.md#list-of-licenses).
- [x] You have searched the repository for any relevant issues or PRs.
- [x] Any category you are creating has the minimum requirement of 3 items.

### CODE REVIEW

**Comment by nodiscc** [comment]
@Zhouzi thanks, can you merge https://github.com/Zhouzi/awesome-selfhosted/pull/1 ?

I agree that the requirement for the `⚠` symbol is not very clear (https://github.com/Kickball/awesome-selfhosted#list-of-licenses see TextBelt and Huboard), not written down in contributing.md, we should probably add it. Basically if the program _requires_ access to a third-party service (here Pocket+Twitter), the warning symbol should be added.

Advice welcome

**Comment by Zhouzi** [comment]
Thank you very much for fixing those :) Yeah, I tried to follow the rules but missed that one. May be a good idea to add a note ^^ Would probably make sense to add it [along the syntax rules](https://github.com/Kickball/awesome-selfhosted/blob/master/.github/CONTRIBUTING.md).

**Comment by nodiscc** [comment]
OK to merge https://github.com/Zhouzi/awesome-selfhosted/pull/2 ? I clarified a bit and grouped it with the non-free requirement.

@Kickball @AndyR207 @n8225 ping, feedback welcome

**Comment by Zhouzi** [comment]
Done 🤘

**Comment by Kickball** [comment]
Looks good to me, I'll let @n8225 or @andy

**Pull request merged**
