### PR TITLE
Merge some links from awesome-sysadmin, link there when appropriate

### PR DESCRIPTION
**Pull request by nodiscc**
Also adds 2 sections "VPN" and "Web servers"
See commit details.

Also ping @n1trux, would you like to work with this project to reduce overlap in the 2 lists? I understand your list is more curated than this one, while this one focuses on web applications.

### CODE REVIEW

**Comment by nodiscc** [comment]
@Kickball is this ok?

**Comment by Kickball** [comment]
Yeah this seems good.

Could we suggest to the owner of awesome-sysadmin that we host the XMPP client and him the servers, or something of the sort?

**Comment by jungle-boogie** [comment]
FWIW, I disagree with this change.

https://github.com/n1trux/awesome-sysadmin

`A curated list of amazingly awesome open source sysadmin resources.`

Even though they have xmpp server listed, I don't necessarily consider that a resource, like I would something related to DNS. 

The description of this project is a little easier to follow:
`Selfhosting is the process of locally hosting and managing applications instead of renting from SaaS providers.` 

Xmpp servers fall in here, voip/sip things fall in there, irc, blogs, version control, etc.


Blog related things on this project could be removed as sysadmins setup and manage blogs for their company and/or knowledge base things. 

I don't think the overlap is a terrible thing.

**Comment by nodiscc** [comment]
These sections from awesome-sysadmin fit to the project description

>This is a list of network services and web applications which can be hosted locally.

https://github.com/n1trux/awesome-sysadmin#project-management
https://github.com/n1trux/awesome-sysadmin#rdbms
https://github.com/n1trux/awesome-sysadmin#statistics
https://github.com/n1trux/awesome-sysadmin#status-pages
https://github.com/n1trux/awesome-sysadmin#version-control
https://github.com/n1trux/awesome-sysadmin#ticketing-systems
https://github.com/n1trux/awesome-sysadmin#vpn
https://github.com/n1trux/awesome-sysadmin#xmpp
https://github.com/n1trux/awesome-sysadmin#web
https://github.com/n1trux/awesome-sysadmin#wiki-software
https://github.com/n1trux/awesome-sysadmin#cloud-storage
https://github.com/n1trux/awesome-sysadmin#code-review
https://github.com/n1trux/awesome-sysadmin#collaborative-software
https://github.com/n1trux/awesome-sysadmin#continuous-integration--continuous-deployment
https://github.com/n1trux/awesome-sysadmin#control-panels
https://github.com/n1trux/awesome-sysadmin#distributed-filesystems
https://github.com/n1trux/awesome-sysadmin#dns
https://github.com/n1trux/awesome-sysadmin#identity-management
https://github.com/n1trux/awesome-sysadmin#it-asset-management
https://github.com/n1trux/awesome-sysadmin#mail-servers
https://github.com/n1trux/awesome-sysadmin#monitoring

**Comment by Kickball** [comment]
I'm not sure how I feel about this, some of the stuff does fit into our list, but I don't want to flat out duplicate parts of the awesome-sysadmin list.

**Comment by nodiscc** [comment]
I don't know. Software in these sections pertain to both systems administration and self-hosting (network services and web applications). We _already_ have sections for most of these, so adding software from awesome-sysadmin shouldn't be too hard. awesome-sysadmin is also under CC-BY-SA 4.0.

However overlap/maintaining 2 lists is not ideal. ping @n1trux, what do you think?

**Comment by n1trux** [comment]
I'm perfectly fine to move some stuff from awesome-sysadmin to this repo here, although I agree with @nodiscc that software could be on both lists.

I think software like server control panels and standard network services like DNS, Mail Servers, Monitoring are sysadmin resources and web apps like Owncloud or other user-facing services like XMPP are self-hosted resources.

We could integrate the stuff from awesome-sysadmin here first, because self-hosted is the smaller list. Then we could remove the corresponding entries from awesome-sysadmin to clean it up. Or we merge both lists?

I'm really not sure how to proceed but agree that overlap sucks.

**Comment by nodiscc** [comment]
@n1trux There's a proposed plan at https://github.com/Kickball/awesome-selfhosted/issues/127

I'm glad that both projects can work together, thank you.

**Pull request closed without merging**
