### PR TITLE
Removed tasks.php from Raymii.org, not updated since 2013

### PR DESCRIPTION
**Pull request by cheerydo**
Thank you for taking the time to work on a PR for Awesome-Selfhosted!

To ensure your PR is dealt with swiftly please check the following:

- [x] Your submissions are formatted according to the guidelines. 
        
    ``[Name](http://homepage/) - Short description. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code)) `License` `Language```
- [x] Your additions are ordered alphabetically.
- [x] Your additions are [free software](https://en.wikipedia.org/wiki/Free_software), or if not they have been added to [non-free](non-free.md).
- [x] Any licenses you have added are in our [list of licenses](https://github.com/Kickball/awesome-selfhosted/blob/master/README.md#list-of-licenses).
- [x] You have searched the repository for any relevant issues or PRs.
- [x] Any category you are creating has the minimum requirement of 3 items.

### CODE REVIEW

**Comment by danger-awesome-Selfhosted** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please check PR guidelines and check the boxes.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by Kickball** [comment]
We have in the past kept older, non-heavily updated projects when they were simple and continued to function without support/updates.

Whether or not this project meets these guidelines is questionable. @nodiscc @n8225 @arylatt what do you think?

If we do need to get in touch with the creator we can do via email
> You can reach me by email, try mailing "contact" "at" "relst" "dot" "nl".

**Comment by Kickball** [comment]
@nodiscc I take it that this project doesn't meet the guidelines for keeping simple, not updated projects as mentioned in my previous comment?

**Comment by nodiscc** [comment]
```
$ cloc .
      31 text files.
      31 unique files.                              
       4 files ignored.

github.com/AlDanial/cloc v 1.70  T=0.18 s (157.0 files/s, 30858.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
CSS                             11            267            227           2232
JavaScript                       6            355            290           1211
PHP                              9            133            180            533
Markdown                         1             26              0             49
JSON                             1              0              0              1
-------------------------------------------------------------------------------
SUM:                            28            781            697           4026
-------------------------------------------------------------------------------
```

533 lines of php doesn't seem that large. I think it can be kept unless serious bugs are found.

**Comment by Kickball** [comment]
@cheerydo ping, please see nodiscc's comments above.

**Comment by Kickball** [comment]
@nodiscc I'm closing this, as @cheerydo has not provided the reasoning for removal. It can be reopened as needed.

**Comment by cheerydo** [comment]
Sorry @Kickball, been away - no specific problems found running on test instance. Thanks for the close and sorry again for the noise

**Pull request closed without merging**
