### PR TITLE
Add wger

### PR DESCRIPTION
**Pull request by rolandgeider**
Added wger to the self-hosting solutions because I couldn't find a better fitting category.

### CODE REVIEW

**Comment by nodiscc** [comment]
I think it would better fit in the Analytics section

**Comment by Kickball** [comment]
Do we think [reportr](http://www.reportr.io/) ([Source code](https://github.com/Reportr/dashboard)) would fit into whatever category these fit into?

**Comment by nodiscc** [comment]
Yes, reportr should also be moved to analytics... unless we find a better naming/new section.

**Comment by rolandgeider** [comment]
I just moved wger to the analytics section. I can also move reportr there, but I didn't know how specific you want your pull requests

**Comment by nodiscc** [comment]
thanks @rolandgeider I moved wger, reportr and habitica to a new section "Personal Dashboards". Is this ok?

**Comment by rolandgeider** [comment]
@nodiscc Yes, that makes more sense! (at least for wger, where I would say it's only 30% analytics)

**Pull request merged**
