### PR TITLE
Add Tiki Suite (Groupware)

### LINKED ISSUE #138: Add Tiki Suite (Groupware)
We need to add:

Tiki Suite - https://suite.tiki.org/tiki-index.php

Tiki Suite is a FLOSS server, providing features to organisations such as: Email, Website & Blog, Shopping Cart, Intranet & Project Management, E-learning, Social Networking, Knowledge base, File sharing, Issue Tracker, Video-conferencing, LDAP, VPN.

[LGPLv2](https://svn.code.sf.net/p/tikiwiki/code/branches/14.x/license.txt) License.

Demo: http://info.tiki.org/Demo

Primary Programming Language: PHP (I think)

### PR DESCRIPTION
**Pull request by Kickball**
* Add Tiki Suite (Groupware)

Resolves #138.

Note: this seems to be created by the same people as Tiki from #543, but seems to be a different project under the same name.

### CODE REVIEW

**Comment by nodiscc** [comment]
This should be moved to _Self-hosting solutions_ as it requires installing a whole OS (ClearOS). The language/platform should be changed to `ClearOS` to reflect this (it installs a lot of applications, which are not only PHP).

Actually it seems to be the same project (fork?) as WikiSuite in https://github.com/Kickball/awesome-selfhosted/pull/557. @marclaporte can you clarify the relationship between TikiSuite and WikiSuite?

**Comment by marclaporte** [comment]
Tiki Wiki CMS Groupware (tiki.org) is a full-featured web application, which is part of WikiSuite. It is already listed: https://github.com/Kickball/awesome-selfhosted/blob/master/README.md#wikis 

WikiSuite (WikiSuite.org) is a suite which includes Kolab, Tiki Wiki CMS Groupware, ClearOS, Openfire Meetings, etc. and others -> http://wikisuite.org/Software-Components

WikiSuite started its life as "Tiki Suite", but the name Tiki Suite is not used anymore.

@nodiscc indicated that WikiSuite should be in the "Self-hosting solutions" and with ClearOS as the platform so here is proposal:

* [WikiSuite](http://WikiSuite.org) - The most comprehensive and integrated Free / Libre / Open Source software suite ever developed. ([Source Code](http://wikisuite.org/Source)) `Various` `ClearOS`

Thanks!

**Comment by nodiscc** [comment]
> @nodiscc indicated that WikiSuite should be in the "Self-hosting solutions" and with ClearOS as the platform so here is proposal:

@marclaporte Yes this is ok.

@Kickball https://suite.tiki.org/tiki-index.php:

> News
>  2016-04-25 Soft launch of WikiSuite.org (Basic content for now, more in the works) WikiSuite is the new name for Tiki Suite 

So I guess we should abandon Tiki Suite (this PR) and wait for @marclaporte to submit a proper PR for WikiSuite.

**Comment by Kickball** [comment]
@nodiscc this sounds good, I'll close this PR now.

**Pull request closed without merging**
