### PR TITLE
Fix syntax errors.

### PR DESCRIPTION
**Pull request by n8225**
Thank you for taking the time to work on a PR for Awesome-selfhosted!

To ensure your PR is dealt with swiftly please check the following:

- [x] Your submissions are formatted according to the guidelines. 
        
    ``[Name](http://homepage/) - Short description. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code)) `License` `Language```
- [x] Your additions are ordered alphabetically.
- [x] Your additions are [free software](https://en.wikipedia.org/wiki/Free_software), or if not they have been added to [non-free](non-free.md).
- [x] Any licenses you have added are in our [list of licenses](https://github.com/Kickball/awesome-selfhosted/blob/master/README.md#list-of-licenses).
- [x] You have searched the repository for any relevant issues or PRs.
- [x] Any category you are creating has the minimum requirement of 3 items.

### CODE REVIEW

**Comment by Kickball** [comment]
All changes look good to me, thanks for fixing these!

**Comment by nodiscc** [comment]
Thanks, also looks go to me. Did you use the Makefile to detect these?

**Comment by n8225** [comment]
I believe the makefile passed a lot of those.  I used a scanner i created: https://n8225.github.io

**Comment by Kickball** [comment]
Wow, down to 3 errors now. Amazing work @n8225!

**Pull request merged**
