### PR TITLE
Add FHEM

### LINKED ISSUE #1027: Add FHEM
Website: http://fhem.de/fhem.html
FHEM is an open source, perl based and self hosted home automation system. From the website:

> FHEM (TM) is a GPL'd perl server for house automation. It is used to automate some common tasks in the household like switching lamps / shutters / heating / etc. and to log events like temperature / humidity / power consumption.
> The program runs as a server, you can control it via web or smartphone frontends, telnet or TCP/IP directly.

### PR DESCRIPTION
**Pull request by Kickball**
Resolves #1027.

The license is based on this file: https://svn.fhem.de/trac/browser/trunk/fhem/docs/copyright?rev=2103. I do have concerns as I have seen trademarked/copyright written in a few places.

---

Thank you for taking the time to work on a PR for Awesome-Selfhosted!

To ensure your PR is dealt with swiftly please check the following:

- [x] Your submissions are formatted according to the guidelines. 
        
    ``[Name](http://homepage/) - Short description. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code)) `License` `Language`` `
- [x] Your additions are ordered alphabetically.
- [x] Your additions are [Free software](https://en.wikipedia.org/wiki/Free_software), or if not they have been added to [non-free](non-free.md).
- [x] Your additions are not already listed at [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin) (IT infrastructure management), [staticgen.com](https://www.staticgen.com/) or [staticsitegenerators.net](https://staticsitegenerators.net/) (static site generators).
- [x] Any licenses you have added are in our [list of licenses](https://github.com/Kickball/awesome-selfhosted/blob/master/README.md#list-of-licenses).
- [x] You have searched the repository for any relevant issues or PRs.
- [x] Any category you are creating has the minimum requirement of 3 items.

### CODE REVIEW

**Comment by roots84** [comment]
Could you maybe point out those places? I'm not a developer of the software and not very familiar with the source code. But I've done a quick search and I couldn't find anything critical

**Comment by Kickball** [comment]
The main place that I saw it was on the home page (https://fhem.de/fhem.html) where it states,

'FHEM **(TM)** is a GPL'd perl server for house automation. It is used to automate some common tasks in the household like sw...'

**Comment by nodiscc** [comment]
The name being trademarked is not related to the software's license (eg. [Firefox is a trademark](https://www.mozilla.org/en-US/foundation/trademarks/list/), but is Free Software)

**Comment by roots84** [comment]
I would agree with nodiscc on that. I searched the trade mark database in Germany and found the entry: https://register.dpma.de/DPMAregister/marke/register/3020152110040/DE?lang=en

**Comment by Kickball** [comment]
Alright, that is good to hear. Thanks @nodiscc and @roots84.

**Pull request merged**
