### PR TITLE
added php password manager

### PR DESCRIPTION
**Pull request by richter-p**

### CODE REVIEW

**Comment by AndyR207** [comment]
Please order this alphabetically.

**Comment by richter-p** [comment]
Ordered alphabetically and fixed syntax.

**Comment by Kickball** [comment]
Please update the first link to use the projects site instead (http://www.ppma.pw).

It should look as follows:

```
* [PHP Password Manager](http://www.ppma.pw) - A web based, encrypting password manager, based on the Yii framework. ([Source Code](https://github.com/pklink/ppma)) `BSD` `PHP`
```

**Comment by richter-p** [comment]
Done, thanks for the input.

**Pull request merged**
