### PR TITLE
Added Pokémon Go Map

### PR DESCRIPTION
**Pull request by florian-184-de**

### CODE REVIEW

**Comment by nodiscc** [comment]
Should be in https://github.com/Kickball/awesome-selfhosted#games

Should have the `⚠` symbol since it requires non-free, third party services (https://github.com/AHAAAAAAA/PokemonGo-Map/wiki - Pokemon Club account, Google Maps API key)
(see for example [HuBoard](https://github.com/Kickball/awesome-selfhosted#ticketing))

**Comment by nodiscc** [comment]
Thanks

**Comment by AndyR207** [comment]
There's a double space between the description and the source code link. Please fix this.

**Comment by Kickball** [comment]
Project is now dead after a cease and desist from Niantic Labs.

**Pull request closed without merging**
