### PR TITLE
Update AUTHORS.md

### PR DESCRIPTION
**Pull request by n8225**
Updated AUTHORS.md
Created .mailmap file

Created AUTHORS.md with the following command:
`mv .github/.mailmap . && printf "Commits | Author \n:---: | ---\n" > AUTHORS.md && git shortlog -sne >> AUTHORS.md &&
sed -i 's/\t/ | /g' AUTHORS.md && mv .mailmap .github/.mailmap`

I put the .mailmap file in the .github folder to prevent cluttering the top level.  git shortlog will not take an argument for the .mailmap, so the above command moves it and moves it back.

If I missed anything on the .mailmap file please point it out or add it.

### CODE REVIEW

**Comment by nodiscc** [comment]
Thanks a lot. I believe this could be automated (replace the old [makecontrib target](https://github.com/Kickball/awesome-selfhosted/blob/master/Makefile#L32) in the Makefile).

**Comment by n8225** [comment]
@nodiscc I added it to the Makefile

**Comment by greggluhring** [comment]
Edward D please remove me


On December 16, 2016 12:40:45 PM n8225 <notifications@github.com> wrote:

@nodiscc I added it to the Makefile

**Comment by greggluhring** [comment]
Remove me


On December 16, 2016 8:46:52 AM nodiscc <notifications@github.com> wrote:

Thanks a lot. I believe this could be automated (replace the old 
[makecontrib 
target](https://github.com/Kickball/awesome-selfhosted/blob/master/Makefile#L32) 
in the Makefile).

**Comment by greggluhring** [comment]
Is kick well again I hate kickball please remove me


On December 16, 2016 8:45:47 AM nodiscc <notifications@github.com> wrote:

nodiscc approved this pull request.





-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/Kickball/awesome-selfhosted/pull/895#pullrequestreview-13345171

**Comment by greggluhring** [comment]
,,,, remove me you can complain to my host but I am I host remove me


On December 16, 2016 8:45:47 AM nodiscc <notifications@github.com> wrote:

nodiscc approved this pull request.





-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/Kickball/awesome-selfhosted/pull/895#pullrequestreview-13345171

**Comment by greggluhring** [comment]
Remove me please hurry up and remove me how long have I been asking you?


On December 16, 2016 8:45:47 AM nodiscc <notifications@github.com> wrote:

nodiscc approved this pull request.





-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/Kickball/awesome-selfhosted/pull/895#pullrequestreview-13345171

**Comment by greggluhring** [comment]
Remove me do you think I'll stop if you do he didn't stop when I asked you


On December 16, 2016 8:46:52 AM nodiscc <notifications@github.com> wrote:

Thanks a lot. I believe this could be automated (replace the old 
[makecontrib 
target](https://github.com/Kickball/awesome-selfhosted/blob/master/Makefile#L32) 
in the Makefile).

**Pull request merged**
