### PR TITLE
Add mkdocs

### PR DESCRIPTION
**Pull request by evitalis**

### CODE REVIEW

**Comment by AndyR207** [comment]
Looks good to me.

**Comment by nodiscc** [comment]
Nope, we don't list static site generators

https://github.com/Kickball/awesome-selfhosted/pulls?utf8=%E2%9C%93&q=is%3Apr%20static%20site%20generator%20is%3Aclosed%20

https://github.com/Kickball/awesome-selfhosted#static-site-generators

**Comment by evitalis** [comment]
Since there is no organization on the linked sites would it be worth putting any on the list at all? Or even having a new list for them with more detail?

**Comment by Kickball** [comment]
There are a few awesome lists for static site generators. It would probably best to send some PRs to them if you want a more detailed list.

* [awesome-static](https://github.com/statictimes/awesome-static)
* [awesome-static-generators](https://github.com/myles/awesome-static-generators)
* [awesome-static-website-services](https://github.com/aharris88/awesome-static-website-services)

**Pull request closed without merging**
