### PR TITLE
Added ArtVenue

### PR DESCRIPTION
**Pull request by tomc3**
Added ArtVenue one the most powerful self-hosted script for photographers, built on Laravel framework.

### CODE REVIEW

**Comment by Kickball** [comment]
I'm not sure how popular this is with photographers, but I'm against having paid, non-opensource scripts in here.

What do you think @nodiscc?

**Comment by nodiscc** [comment]
@Kickball yes, I need some time to think about it but we'll probably need to separate non-Free software (in a separate file?) if we don't want this list to turn into a commercial advertisement platform...

**Comment by nodiscc** [comment]
See #89

**Comment by nodiscc** [comment]
This may now be added to the [Non-Free](https://github.com/Kickball/awesome-selfhosted/blob/master/non-free.md) page.

@tomc3 can you edit your Pull Request?

**Comment by tomc3** [comment]
I have updated the list, nice decision to create a separate list for non-free awesome products.
Let me know if it's OK or I will open fresh pull request. :)

**Comment by nodiscc** [comment]
@tomc3 thank you; can you rebase on the latest `master`? `git remote add kickball https://github.com/Kickball/awesome-selfhosted; git remote update; git rebase kickball master`

**Comment by nodiscc** [comment]
Thank you, moved to https://github.com/Kickball/awesome-selfhosted/pull/133

**Pull request closed without merging**
