### PR TITLE
Added mailing lists managers

### PR DESCRIPTION
**Pull request by adminrezo**

### CODE REVIEW

**Comment by adminrezo** [comment]
Added sympa

**Comment by AndyR207** [comment]
The entire "Communication Systems" section is not alphabetically sorted. Can you please correct this, or wait until we do and then resubmit the PR please.

**Comment by nodiscc** [comment]
Or merge the PR now, and sort later?

**Comment by AndyR207** [comment]
Either way works, worried about closing this and forgetting about it though...

**Comment by nodiscc** [comment]
> worried about closing this and forgetting about it

https://github.com/Kickball/awesome-selfhosted/issues/460

**Comment by Kickball** [comment]
#463 sort the communication system section as @AndyR207 was concerned about.

**Pull request merged**
