### PR TITLE
Added classified ads

### PR DESCRIPTION
**Pull request by operatornormal**
Dear awsome-selfhosted Sirs,

please consider my PR. It seems like

- [X] Your submissions are formatted according to the guidelines. 
 * made with makefile
- [X] Your additions are ordered alphabetically.
 * hopefully
- [X] Your additions are [free software](https://en.wikipedia.org/wiki/Free_software), or if not they have been added to [non-free](non-free.md).
 * LGPLv2
- [-] Any licenses you have added are in our [list of licenses](https://github.com/Kickball/awesome-selfhosted/blob/master/README.md#list-of-licenses).
 * not applicable
- [X] You have searched the repository for any relevant issues or PRs.
 * SW was not previously listed and there was no PR. 
- [-] Any category you are creating has the minimum requirement of 3 items.
 * not applicable 

--
Antti Järvinen

### CODE REVIEW

**Comment by operatornormal** [comment]
Indeed, I should have left the ordering task to be done by proper algorithm, like qsort. 

-> but now sorted.

**Comment by n8225** [comment]
@operatornormal please fix the merge conflicts.

**Comment by nodiscc** [comment]
Hello, I don't know if we should merge this.

> Most of functionality is on top of Qt library so porting to other environments where Qt is available might be possible.

Though it use a decentralized network model, it is not possible to run this application on a server that has no display server/runs headless/etc. This is a desktop application. @Kickball @AndyR207 please advise.

**Comment by n8225** [comment]
Not sure how I missed that.  After looking through it again, since it's not self hosted we should close the PR.

**Comment by operatornormal** [comment]
All right,

classified-ads is desktop app. And written on top of Qt, so it is X11 or wayland app. Running that on headless server (like I do) requires usage of vnc or similar X11-nesting prog that you can detach. 

Motivation to suggesting that to self-hosted is that it provides users with range of communication-related services where users "host" the storage and transmission services to each others - this app is meant to be left running also when user is not actively using it. Reason for not splitting separate daemon+UI part is simplicity - I've witnessed numerous failures in this area where process of setting up various daemons etc. is too difficult for mainstream user ; here it is next to nil.

It didn't occur to me that not splitting the daemon+UI would be a showstopper here - you're already listing number of projects with partly overlapping goals and implementation but yes, most of them do include separate daemon part and UI part. 

--
Antti

**Comment by Kickball** [comment]
Hey @operatornormal,

As some of the other collaborators have mentioned above, this repository is only for client-server software (mostly the server side). Software that doesn't split the daemon and desktop application (UI) is therefore not eligible.

I understand the simplicity advantages of combining them, but that moves away from what this repository was created for.

Hope this clarifies,
Kickball

**Pull request closed without merging**
