### PR TITLE
Add Medusa

### PR DESCRIPTION
**Pull request by OmgImAlexis**
Medusa is a heavily modified fork of Sickrage.

### CODE REVIEW

**Comment by Kickball** [comment]
Medusa needs to be ordered alphabetically, please fix this.

**Comment by OmgImAlexis** [comment]
It might be an idea to add [Github PR template](https://github.com/blog/2111-issue-and-pull-request-templates) so people know this before opening the PR.

Fixed btw.

**Comment by nodiscc** [comment]
Thank you, I thought we had this requirement written down in [Contribution](https://github.com/Kickball/awesome-selfhosted#contributing), but apparently no. This should be fixed soon.

**Comment by Kickball** [comment]
Just to clarify this is a fork of Sickrage right?

**Comment by nodiscc** [comment]
It seems to be. I would be wary of adding too many forks.

**Comment by Kickball** [comment]
As long as there are a few major differences and changes then I am happy to list it as its own item. However if it is still similar then I think it should be listed as a sub-item.

**Comment by nodiscc** [comment]
@pymedusa Can you list the major differences between SickRage and Medusa?

**Comment by fernandog** [comment]
@nodiscc

First and most important: user can manual search. It shows all available releases with all needed info like quality, seeders, leechers, color font when find ignored or preferred words.

Its the only sickbeard fork that does that.
Entire team of devs - except one - left SickRage.
So here we are.

**Comment by fernandog** [comment]
Check it out:

image

**Comment by Kickball** [comment]
Forgive me as I am not familiar with Sickrage and its interface, so I can't compare your screenshot. Can you clarify if the manual search is the major only change?

**Comment by Kickball** [comment]
74765c1 adds Medusa, as agree with the collaborators in the Awesome Selfhosted chat.

**Pull request closed without merging**
