### PR TITLE
added DietPi

### LINKED ISSUE #1094: add DietPi
_i'm not sure if DietPi should be added and if yes, wether it really fits the "[Self-hosting Solutions](https://github.com/Kickball/awesome-selfhosted#self-hosting-solutions)" section or an other one... so i just opened this issue._

DietPi is a small lightweight debian optimized for ~30 and counting single-board computers (images for VirtualBox and VMware are also available):
- the installation can be automatized by simply editing a txt-file
- it uses just shell-scripts, so no special software is required
- customizing, backup, update and installing/uninstalling new "ready-to-run" software is easily done with GUI-like shell dialogues.

DietPi is maybe not a single service you are looking for, but if you want to selfhost something at home, or you just want to play around with a service before setting it up on your production server, DietPi is nice to have and wether you are an expert or beginner really eases some things.

the line - added wherever - should look something like that... i'm not sure if the description is (good) enough to point out scope and advantages of the project:
> [DietPi](http://dietpi.com/) - Highly optimized extremely lightweight minimal Debian OS, which allows you to get the maximum performance from your single-board computer. ([Source Code](https://github.com/Fourdee/DietPi)) `GPLv2` `Shell`

### PR DESCRIPTION
**Pull request by DJCrashdummy**
i hope the description is good, hits the point and short enough?

---

To ensure your PR is dealt with swiftly please check the following:

- [x] Your submissions are formatted according to the guidelines. 
        
    ``[Name](http://homepage/) - Short description. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code)) `License` `Language` ``

- [x] Your additions are ordered alphabetically.
- [x] Your additions are [Free software](https://en.wikipedia.org/wiki/Free_software)<s>, or if not they have been added to [non-free](non-free.md)</s>.
- [x] Your additions are not already listed at [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin) (IT infrastructure management), [staticgen.com](https://www.staticgen.com/) or [staticsitegenerators.net](https://staticsitegenerators.net/) (static site generators).
- [x] Any licenses you have added are in our [list of licenses](https://github.com/Kickball/awesome-selfhosted/blob/master/README.md#list-of-licenses).
- [x] You have searched the repository for any relevant issues or PRs.
        
    should fix #1094 

- [x] <s>Any category you are creating has the minimum requirement of 3 items.</s>

### CODE REVIEW

**Comment by DJCrashdummy** [comment]
@Kickball as mentioned in the initial post, there is an open issue #1094 with a little discussion about DietPi.

> Isn't this an operating system?

yes it is, but not only. see https://github.com/Kickball/awesome-selfhosted/issues/1094#issuecomment-313025167

> Does it fit here?

if you are asking me: yes, else i hadn't added it. see https://github.com/Kickball/awesome-selfhosted/issues/1094#issuecomment-313003511

> It doesn't seem to support self-hosted application install easier than a traditional OS.

yes it does. among others they have terminal UI for installing, uninstalling and updating applications by just selecting them (also/especially for applications which are not in the repos or outdated). - dietpi uses the current versions from their websites for installing.

**Comment by nodiscc** [comment]
@Kickball the discussion at #1094 (and the screenshot/list at http://dietpi.com/phpbb/viewtopic.php?f=8&t=5#p5) convinced me DietPi somehow made it easier to install self-hosted services. I think it qualifies.

**Comment by DJCrashdummy** [comment]
maybe expanding the description to _"Highly optimized extremely lightweight minimal Debian OS for single-board computers, which allows you to easily install and manage several services (via **just selecting in a** terminal UI) for selfhosting at home."_ would make it clearer?

**Comment by nodiscc** [comment]
> maybe expanding the description

Nope, the description is already quite long as it is

> Highly optimized extremely lightweight minimal

**Comment by DJCrashdummy** [comment]
@nodiscc i know... i took this wording somewhere from their site.

@"everybody": i'm still open for suggestions!

**Comment by nodiscc** [comment]
@DJCrashdummy I update the description: https://github.com/Kickball/awesome-selfhosted/pull/1123/commits/5bb9739d0833e140f55974295a76dd4065645ee3

Is that ok?

**Comment by DJCrashdummy** [comment]
i think it still hits the point and is shorter and nicer to read.

**Comment by Kickball** [comment]
@nodiscc @DJCrashdummy thanks for clarifying, I agree after reading #1094.

**Pull request merged**
