### PR TITLE
Added Myyna to Bookmarks & Link Sharing

### PR DESCRIPTION
**Pull request by Keyhaku**

### CODE REVIEW

**Comment by nodiscc** [comment]
:+1: Thanks. The demo server is offline currently. @Keyhaku @cubettech Is this temporary?

**Comment by Keyhaku** [comment]
Unfortunately, I don't know, maybe we can remove the link to the demo, since it can be easily find out on the main web site.

**Comment by cubettech** [comment]
Will be set live asap

On Sunday 22 November 2015, Keyhaku <notifications@github.com> wrote:

> Unfortunately, I don't know, maybe we can remove the link to the demo,
> since it can be easily find out on the main web site.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Kickball/awesome-selfhosted/pull/352#issuecomment-158735715>
> .
>


-- 
Regards,

PRASANTH P
Project Lead
Phone: +91 484 4054324|prasanth@cubettech.com |*Skype : *prasanth.cubettech
[image: Cubet Techno Labs]  <http://cubettech.com/>
www.cubettech.com
This email and any files transmitted with it are confidential and intended
solely for the use of the individual or entity to whom they are addressed.
If you have received this email in error please notify the sender. This
message contains confidential information and is intended only for the
individual named. If you are not the named addressee you should not
disseminate, distribute or copy this email. Please notify the sender
immediately by email if you have received this email by mistake and delete
this email from your system. If you are not the intended recipient you are
notified that disclosing, copying, distributing or taking any action in
reliance on the contents of this information is strictly prohibited.

P
*Please consider the environment before printing this email*
Save Paper, Save Trees! Print to paper only if necessary.[image: Cubet
Technologies Logo] <http://cubettechnologies.com/>

**Comment by Kickball** [comment]
Demo is back up, looks good to merge!

**Comment by Kulak** [comment]
Did you know that Myyna.com has a poor web of trust (WoT) rating?  I don't know if it is relevant or not...

https://www.mywot.com/en/scorecard/myyna.com?utm_source=addon&utm_content=rw-viewsc

**Comment by nodiscc** [comment]
@Kulak hi again. The only WOT report on myyna.com seems to be spam itself.

**Pull request merged**
