### PR TITLE
Fix/cleanup Federated Identity/Authentication & move to awesome-sysadmin

### PR DESCRIPTION
**Pull request by n8225**
Issues #35 #471

Removed OpenID/OpenID Connect as it appears to be a standard and not software.
Added Apachev1 to licenses for Openca or should this just fall under Apache?

Thank you for taking the time to work on a PR for Awesome-selfhosted!

To ensure your PR is dealt with swiftly please check the following:

- [x] Your submissions are formatted according to the guidelines. 
        
    ``[Name](http://homepage/) - Short description. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code)) `License` `Language```
- [x] Your additions are ordered alphabetically.
- [x] Your additions are [free software](https://en.wikipedia.org/wiki/Free_software), or if not they have been added to [non-free](non-free.md).
- [x] Any licenses you have added are in our [list of licenses](https://github.com/Kickball/awesome-selfhosted/blob/master/README.md#list-of-licenses).
- [x] You have searched the repository for any relevant issues or PRs.
- [x] Any category you are creating has the minimum requirement of 3 items.

### CODE REVIEW

**Comment by Kickball** [comment]
All the changes look good, I'm not sure on the best thing for the Apache licenses. @nodiscc has been the specialist on licenses, it would be good to see what he thinks.

**Comment by nodiscc** [comment]
I think we should move OCSPD (licensed under Apache v1.0) to awesome-sysadmin (Identity management section), following the discussion in https://github.com/Kickball/awesome-selfhosted/pull/704. I couldn't find a summary of the differences between Apache v1.0 and v2.0.

http://openca.dyndns.org:4443/projects/ocspd/

**Comment by n8225** [comment]
@n1trux @nodiscc Should the whole section be moved to [https://github.com/n1trux/awesome-sysadmin#identity-management](https://github.com/n1trux/awesome-sysadmin#identity-management)?

**Comment by nodiscc** [comment]
After giving it another look, I think the whole section should be moved to awesome-sysadmin. @n1trux please let us know if this is ok.

**Comment by n1trux** [comment]
RADIUS / FreeIPA are definitely Sysadmin topics, yes. Feel free to create a PR :)

Don't wonder when I'm not merging immediately, often I accumulate PRs and do them all at once when I have the time.

**Comment by Kickball** [comment]
[Awesome-Sysadmin#174](https://github.com/n1trux/awesome-sysadmin/pull/174) moves this section over. I wasn't 100% sure on which categories the items should go in so it could probably do with a look over. @n1trux @nodiscc @n8225.

**Comment by n8225** [comment]
Removed the entries that have been moved to Awesome-Sysadmin.  I think we should wait to merge this one until its committed on Awesome-Sysadmin.

**Comment by Kickball** [comment]
Yeah it is best to wait until our PR on awesome sysadmin is merged.

**Comment by nodiscc** [comment]
https://github.com/n1trux/awesome-sysadmin/issues/174 merged

**Comment by Kickball** [comment]
Is there a reason we are keeping daloRADIUS in the section?

**Comment by n8225** [comment]
Can't remember, I might have just overlooked it.

**Comment by Kickball** [comment]
Not a problem, I don't see any reason to keep it in there though.

**Comment by n8225** [comment]
Removed

**Comment by Kickball** [comment]
Thanks, looks good to me now. :+1:

**Pull request merged**
