### PR TITLE
Updated README.md to add Plone

### PR DESCRIPTION
**Pull request by pengc99**
Added Plone to list of CMSs

### CODE REVIEW

**Comment by nodiscc** [comment]
Wrong source code link? Where is the code for Plone itself?

**Comment by pengc99** [comment]
Source code is here: https://github.com/plone

**Comment by nodiscc** [comment]
All I see is a buch of repos for modules, toolbars, APIs, classes... Where is the main application source code?

**Comment by pengc99** [comment]
The Plone CMS is split up in the repo for different segments of the application. The core application is hosted in that repo under: https://github.com/plone/Products.CMFPlone

**Comment by nodiscc** [comment]
Thanks for your reply @pengc99

**Comment by Kickball** [comment]
Do we need to add something in the licenses section about the Zope license?

**Comment by nodiscc** [comment]
@Kickball good catch, @pengc99 the license is still missing.
From the files in this repo I gather the license is ZPL 2.1 http://opensource.org/licenses/ZPL-2.0

**Comment by Kickball** [comment]
#371 is the issue for the now missing ZPL 2.1 license.

**Pull request merged**
