### PR TITLE
Add Open Streaming Platform

### PR DESCRIPTION
**Pull request by deamos**
Thank you for taking the time to work on a PR for Awesome-Selfhosted!

To ensure your PR is dealt with swiftly please check the following:

- [x] Your submissions are formatted according to the following requirements:
        
``- [Name](http://homepage/) - Short description, less than 250 characters. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``

Depends on proprietary services:

``- [Name](http://homepage/) `⚠` - Short description, less than 250 characters. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``

Non-free software in `non-free.md`:

``- [Name](http://homepage/) `⊘ Proprietary` - Short description, less than 250 characters. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `Language` ``

- [x] Your additions are ordered alphabetically.
- [x] Your additions are [Free software](https://en.wikipedia.org/wiki/Free_software), or if not they have been added to [non-free](non-free.md) and marked `⊘ Proprietary`.
- [x] If your additions depend on proprietary services outside the user's control, they must be marked `⚠`.
- [x] Your additions are not already listed at [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin) (IT infrastructure management), [staticgen.com](https://www.staticgen.com/) or [staticsitegenerators.net](https://staticsitegenerators.net/) (static site generators).
- [x] Your additions have their `License` main server-side `Language`/platform/requirement listed.
- [x] Any licenses you have added are in our [list of licenses](https://github.com/Kickball/awesome-selfhosted/blob/master/README.md#list-of-licenses).
- [x] You have searched the repository for any relevant [issues](https://github.com/Kickball/awesome-selfhosted/issues) or [PRs](https://github.com/Kickball/awesome-selfhosted/pulls), including closed ones.
- [x] If the main link of your addition points to the program's source code, there is no need to add a duplicate _Source Code_ link. The _Demo_ and _Clients_ links are not mandatory.
- [x] Any category you are creating has the minimum requirement of 3 items. If not, your addition may be inserted into `Misc/Other`.
- [x] Any software project you are adding to the list is actively maintained.

### CODE REVIEW

**Comment by danger-awesome-Selfhosted** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please check PR guidelines and check the boxes.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by nodiscc** [comment]
I like it but the install script is "unsafe". Please use `set -o errexit; set -o nounset` or at least don't `cd` everywhere, and just use absolute paths :) I'll try to send a patch if I have time. I realize that

> OSP has only been tested on Ubuntu 16.04 and the installation script may not work properly on other OS's.

I will probably try it on Debian "soon". But I think just documenting the install process instead of recommending to blindly run a not-so-well-tested script (most of which runs as root) would be better. By the way `shellcheck` returns the following warnings:

```
$ shellcheck setup-osp.sh 

In setup-osp.sh line 17:
cd /tmp
^-- SC2164: Use cd ... || exit in case cd fails.


In setup-osp.sh line 22:
cd nginx-1.13.10
^-- SC2164: Use cd ... || exit in case cd fails.


In setup-osp.sh line 28:
cd $cwd/nginx
^-- SC2164: Use cd ... || exit in case cd fails.
   ^-- SC2086: Double quote to prevent globbing and word splitting.


In setup-osp.sh line 32:
cd $cwd/nginx
^-- SC2164: Use cd ... || exit in case cd fails.
   ^-- SC2086: Double quote to prevent globbing and word splitting.


In setup-osp.sh line 37:
cd $cwd/gunicorn
^-- SC2164: Use cd ... || exit in case cd fails.
   ^-- SC2086: Double quote to prevent globbing and word splitting.


In setup-osp.sh line 43:
cd /var/
^-- SC2164: Use cd ... || exit in case cd fails.


In setup-osp.sh line 46:
cd www
^-- SC2164: Use cd ... || exit in case cd fails.

```

Not something that would prevent it being added to the list, just my bash/sysadmin OCD kicking in :)

I have been looking for something like that for some time. I just want to stream video from OBS through a plain web server, no fancy chat widgets or channels or anything. I was thinking of using [Icecast](https://icecast.org/) - only tried audio streaming so far but apparently it can do video. But if your project does it well I might as well try it.

**Comment by deamos** [comment]
Thanks for the feedback.  I'll look into cleaning that install script up.

I'm glad it is something you have been looking for as well. Thanks for the awesome list and if you have any extra questions on OSP, feel free to reach out to us up on our Discord channel - [https://discord.gg/Jp5rzbD](https://discord.gg/Jp5rzbD)

**Comment by deamos** [comment]
I added some checks to the install script and also provided Manual instructions for install in the README

Thanks again,

**Pull request merged**
