### PR TITLE
Add FreeIPA to "Federated Identity/Authentication"

### PR DESCRIPTION
**Pull request by ilsi**

### CODE REVIEW

**Comment by Kickball** [comment]
Would it not be better to change the license to various as we have done before?

**Comment by nodiscc** [comment]
@Kickball I changed the wording in #669 to `Multiple` when there are multiple licenses.

**Comment by Kickball** [comment]
Alright, should we change the licenses to `Multiple` then?

**Comment by nodiscc** [comment]
Yes please @ilsi remove the link to the licenses page and simply tag it `Multiple`.

**Comment by ilsi** [comment]
Ok. Retaged to `Multiple`

**Pull request merged**
