### PR TITLE
Added Pyazo2

### PR DESCRIPTION
**Pull request by epiclyepicethan1**
Thank you for taking the time to work on a PR for Awesome-Selfhosted!

To ensure your PR is dealt with swiftly please check the following:

- [x] Your submissions are formatted according to the guidelines. 
        
    ``[Name](http://homepage/) - Short description. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code)) `License` `Language` ``

- [x] Your additions are ordered alphabetically.
- [x] Your additions are [Free software](https://en.wikipedia.org/wiki/Free_software), or if not they have been added to [non-free](non-free.md).
- [x] Your additions are not already listed at [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin) (IT infrastructure management), [staticgen.com](https://www.staticgen.com/) or [staticsitegenerators.net](https://staticsitegenerators.net/) (static site generators).
- [x] Any licenses you have added are in our [list of licenses](https://github.com/Kickball/awesome-selfhosted/blob/master/README.md#list-of-licenses).
- [x] You have searched the repository for any relevant issues or PRs.
- [x] Any category you are creating has the minimum requirement of 3 items.

### CODE REVIEW

**Comment by danger-awesome-Selfhosted** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Found 1 entries with syntax error(s).</td>
    </tr>
  </tbody>
</table>

#### Syntax Issues

 Name | Entry
----|----------------------
Pyazo2 |   * [Pyazo2](https://github.com/uzulla/Pyazo2) - Gyazo and Gifzo compatible server by perl `Perl` 
 

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by epiclyepicethan1** [comment]
The author didn't license it. 

It lets you host your own Gyazo or Gifzo server. In other words, instead of your clips being uploaded to their servers, they are stored on yours.

**Comment by nodiscc** [comment]
* It needs to be licensed under a Free Software license to be added to the list. You could open an issue, and direct the author to https://tldrlegal.com/licenses/browse or https://choosealicense.com/ to help them choose a license. Otherwise It must be added to `non-free.md`.
 * Now I get it, thanks. Can you change the description to `Gyazo and Gifzo compatible image/video server.` ? (mind the final dot)

**Comment by nodiscc** [comment]
Closing until the licensing/description issues are fixed.

**Pull request closed without merging**
