### PR TITLE
Add Strider to the CI section

### PR DESCRIPTION
**Pull request by rictorres**
Strider is an Open Source Continuous Deployment / Continuous Integration platform. It is written in Node.JS / JavaScript and uses MongoDB as a backing store. It is published under the BSD license.

### CODE REVIEW

**Comment by Kickball** [comment]
Could you please change the start to be:

* [Strider](http://stridercd.com) 

While at the moment that URL links back to the project's Github page in the future it may not and it will save us making changes down the line.

**Comment by rictorres** [comment]
Done!

**Comment by Kickball** [comment]
@nodiscc could you give this a look over and merge if it is all good?

**Comment by nodiscc** [comment]
I will merge the pending valid Pull Requests in the coming days. Thanks @Kickball @rictorres

**Comment by rictorres** [comment]
:+1:

**Pull request merged**
