### PR TITLE
added demo link for TaskBoard

### PR DESCRIPTION
**Pull request by DJCrashdummy**
Thank you for taking the time to work on a PR for Awesome-Selfhosted!

To ensure your PR is dealt with swiftly please check the following:

- [x] Your submissions are formatted according to the guidelines. 
        
    ``- [Name](http://homepage/) - Short description, less than 250 characters. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code)) `License` `Language` ``

- [ ] <s>Your additions are ordered alphabetically.</s>
- [ ] <s>Your additions are [Free software](https://en.wikipedia.org/wiki/Free_software), or if not they have been added to [non-free](non-free.md).</s>
- [ ] <s>Your additions are not already listed at [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin) (IT infrastructure management), [staticgen.com](https://www.staticgen.com/) or [staticsitegenerators.net](https://staticsitegenerators.net/) (static site generators).</s>
- [ ] <s>Any licenses you have added are in our [list of licenses](https://github.com/Kickball/awesome-selfhosted/blob/master/README.md#list-of-licenses).</s>
- [ ] <s>You have searched the repository for any relevant [issues](https://github.com/Kickball/awesome-selfhosted/issues) or [PRs](https://github.com/Kickball/awesome-selfhosted/pulls).</s>
- [ ] <s>Any category you are creating has the minimum requirement of 3 items.</s>
- [ ] <s>Any software project you are adding to the list is actively maintained.</s>

--- 

just added a demo link...

### CODE REVIEW

**Comment by danger-awesome-Selfhosted** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please check PR guidelines and check the boxes.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by Kickball** [comment]
scrumblr's demo was removed in this PR, was this intended @DJCrashdummy?

The [demo](http://scrumblr.ca/demo) still seems to be working.

**Comment by DJCrashdummy** [comment]
> scrumblr's demo was removed in this PR, was this intended @DJCrashdummy?

@Kickball no, definitely not!
as you can see in https://github.com/Kickball/awesome-selfhosted/pull/1408/commits/4f205e49c89038f26702a496cceb5010e8665e3a i just added the TaskBoard-Demo... you can also see that the master was still old (without the scrumblr-Demo) because i added it nearly at the same time (#1407). maybe this caused the problem... or was it even @nodiscc with `Merge branch 'master' into patch-3`?

please tell me what's the cause and i may have done wrong, because i'm still not so familiar with git(hub)!
--> or should i have collected all commits into one PR?

**Comment by Kickball** [comment]
No problem, it doesn't look like it was removed in your commit. I suspect that it was caused by close merge time with #1407 as you suggested.

I don't think you've done anything wrong in this case but I'm not a master of Git/GitHub myself and unfortunately can't offer any recommendations there.

I've raised #1423 to track re-adding it.

**Comment by DJCrashdummy** [comment]
> I don't think you've done anything wrong in this case but I'm not a master of Git/GitHub myself and unfortunately can't offer any recommendations there.

ok... thanks for confirming my assumption/hope at least a little bit. :wink: 

--- 

created #1427 (a "quasi-duplicate" of #1407) to finally solve #1423 and the whole confusion...

**Comment by Kickball** [comment]
@DJCrashdummy thanks for wrapping your head around this and making sure that it is all correct in the end.

I've approved #1423.

**Pull request merged**
