### PR TITLE
added - ZeroBin - zero knowledge pastebin.

### PR DESCRIPTION
**Pull request by mro**

### CODE REVIEW

**Comment by Kickball** [comment]
Generally we don't accept projects which are not maintained, and ZeroBin has not had a commit in almost 2 years! Also there are 20+ pull requests open, which the author has not responded to or acknowledged. 

In case we do accept this please update it to include the [demo](http://sebsauvage.net/paste/) and the [source code](https://github.com/sebsauvage/ZeroBin). Please follow our formatting standard:

``[Name](http://homepage/) - Short description ([Demo](http://url.to/demo), [Source code](http://url.of/source/code)) `License` `Language` ``

**Comment by mro** [comment]
no, I cannot justify the lack of commits, it's unmaintained. closing.

**Comment by nodiscc** [comment]
I have used it in the past, it used to work perfectly at the time. The github project is at https://github.com/sebsauvage/zerobin, if someone can find an actively maintained fork we might consider adding it.

**Comment by mro** [comment]
👍#451

**Pull request closed without merging**
