### PR TITLE
removed localpaste

### PR DESCRIPTION
**Pull request by DJCrashdummy**
Thank you for taking the time to work on a PR for Awesome-Selfhosted!

To ensure your PR is dealt with swiftly please check the following:

- [ ] <s>Your submissions are formatted according to the guidelines.</s> 
        
    ``- [Name](http://homepage/) - Short description, less than 250 characters. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``

- [ ] <s>Your additions are ordered alphabetically.</s>
- [ ] <s>Your additions are [Free software](https://en.wikipedia.org/wiki/Free_software), or if not they have been added to [non-free](non-free.md) and marked `⊘ Proprietary`.</s>
- [ ] <s>Your additions are not already listed at [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin) (IT infrastructure management), [staticgen.com](https://www.staticgen.com/) or [staticsitegenerators.net](https://staticsitegenerators.net/) (static site generators).</s>
- [ ] <s>Your additions have their `License` main server-side `Language`/platform/requirement listed.</s>
- [ ] <s>Any licenses you have added are in our [list of licenses](https://github.com/Kickball/awesome-selfhosted/blob/master/README.md#list-of-licenses).</s>
- [ ] <s>You have searched the repository for any relevant [issues](https://github.com/Kickball/awesome-selfhosted/issues) or [PRs](https://github.com/Kickball/awesome-selfhosted/pulls), incluing closed ones.</s>
- [ ] <s>If the main link of your addition points to the program's source code, there is no need to add a duplicate _Source Code_ link. The _Demo_ and _Clients_ links are not mandatory.</s>
- [ ] <s>Any category you are creating has the minimum requirement of 3 items. If not, your addition may be inserted into `Misc/Other`.</s>
- [x] Any software project you are adding to the list is actively maintained.

--- 

removed localpaste because it is inactive since 3 years.

### CODE REVIEW

**Comment by danger-awesome-Selfhosted** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please check PR guidelines and check the boxes.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by jadedgnome** [comment]
The software works as intended. development status shouldn't be the end all be all.

**Comment by DJCrashdummy** [comment]
@jadedgnome normally i don't ditch software just because it is "old"... ("old" and tested software often works better than the newest and shiniest one)!

but as @jherazob said, at the latest as you put software on a server which is connected to the internet, maintenance is definitively a must (for both, the software and the server :wink:)! - and therefore this is also clearly stated in the [contributing guidelines (last point)](https://github.com/Kickball/awesome-selfhosted/blob/master/.github/CONTRIBUTING.md) as it is very likely, that most of the software in the list would be installed on a server with internet-connection.

**Comment by nodiscc** [comment]
It can be argued that the software is very simple/does it's job, and doesn't need to be actively maintained anymore:

```
$ git clone https://github.com/petermaloney/localpaste
$ cloc localpaste/
       4 text files.
       4 unique files.                              
       3 files ignored.

github.com/AlDanial/cloc v 1.70  T=0.03 s (59.0 files/s, 19624.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           1             86            122            334
Markdown                         1             30              0             93
-------------------------------------------------------------------------------
SUM:                             2            116            122            427
-------------------------------------------------------------------------------
```

There have been exceptions to the "must be actively maintained" guideline before.

**Comment by nodiscc** [comment]
That said, localpaste's author has been away from github for some time, and has no public contact email address. The software takes input from a `curl` request on a listening HTTP port and writes contents of the request to a file on the server. The README states it must be run as root (even though it apparently drops privileges somewhere along the way).

So I think it is preferable to remove it, unless someone steps up to maintain it.

**Pull request merged**
