### PR TITLE
Feedreader Updates

### PR DESCRIPTION
**Pull request by Kickball**
* Add RSS Monster.
* Remove Tiny Tiny RSS Mobile (Last Commit Aug 2014, multiple reports of being broken)
* Added Licenses and Programming Languages
* Removed Broken Links

### CODE REVIEW

**Comment by nodiscc** [comment]
Good job.

About tt-rss-mobile, can you point to the reports asserting it's broken? Last time I used it it was fine (and faster than the native tt-rss UI). I thought the bug reports were mainly feature requests.

**Comment by Kickball** [comment]
I was referencing [ttrss-mobile#56](https://github.com/mboinet/ttrss-mobile/issues/56) and [ttrss-mobile#61](https://github.com/mboinet/ttrss-mobile/issues/61), which reference older devices.

The author did state that [he is no longer maintaining this project](https://github.com/mboinet/ttrss-mobile/issues/69), but if it does still work on normal/up-to-date devices then I'll add it back.

**Comment by nodiscc** [comment]
@Kickball I have push access to mboinet's repo (at the time I did some cleanup in the way files/releases were organized). I don't have enough time or skills to work on feature that I have no personal interest in, but I think mboinet and myself would gladly accept patches.

About older devices, same problem, I don't own them, have no way to test, lack skills and time. I think the software can live on with those "bugs" (which could as well be platform bugs). I'd appreciate if you can leave ttrss-mobile in the list.

Otherwise you patch looks fine

**Comment by Kickball** [comment]
I've readded ttrss-mobile in 5a796a7, given you have push access and can ensure it is maintained. :+1:

**Comment by nodiscc** [comment]
https://github.com/mboinet/ttrss-mobile/issues/70 might take some time (we need an agreement from all contributors)

grittt-rss in fact uses the [BSD license](https://opensource.org/licenses/BSD-2-Clause)

**Comment by AndyR207** [comment]
@Kickball I've resolved the merge conflicts here and we don't seem to be waiting on anything else...

**Comment by nodiscc** [comment]
:+1:

**Pull request merged**
