### PR TITLE
Added Eclipse Che

### PR DESCRIPTION
**Pull request by cipi1965**

### CODE REVIEW

**Comment by nodiscc** [comment]
Missing language/platform (Docker/Java)

**Comment by nodiscc** [comment]
@cipi1965 Please merge https://github.com/cipi1965/awesome-selfhosted/pull/1

**Comment by nodiscc** [comment]
@cipi1965 Please order the IDE/Tools section alphabetically.

**Comment by cipi1965** [comment]
Done

**Pull request merged**
