### PR TITLE
added Phant IoT Data Storage

### PR DESCRIPTION
**Pull request by cavebeat**

### CODE REVIEW

**Comment by AndyR207** [comment]
Looks good to me.

**Comment by cavebeat** [comment]
impossible, with the first try ;)

**Comment by AndyR207** [comment]
I take it back, you're missing a closing bracket after the Source Code link. Sorry

**Comment by nodiscc** [comment]
Same question as in https://github.com/Kickball/awesome-selfhosted/pull/455#issuecomment-185925508 ?

**Comment by AndyR207** [comment]
This one doesn't seem to do anything with the data apart from display it. That was what I got from a brief flick through the docs, anyway.

**Comment by cavebeat** [comment]
rdy

**Comment by nodiscc** [comment]
right.

**Pull request merged**
