### PR TITLE
Added omgnata TODO list web app.

### PR DESCRIPTION
**Pull request by chr15m**

### CODE REVIEW

**Comment by AndyR207** [comment]
Please sort into alphabetical order, demo link should be in brackets, please condense down to one language, or put a "/" between them (.e.g `PHP/Clojure`)

**Comment by chr15m** [comment]
Will squash these commits into one.

**Comment by chr15m** [comment]
The list was not in alphabetical order to begin with so I will fix that.

**Comment by chr15m** [comment]
Hello, I have made the fixes and update the PR.

**Comment by AndyR207** [comment]
Please change `GPLV3` to `GPLv3` and remove the hyphen between (Demo) and `GPLv3`

**Comment by chr15m** [comment]
Hi, done. I also fixed the incorrect capitalisation in Tracks' license.

**Pull request merged**
