### PR TITLE
Added SharpPaste under pastebins category.

### PR DESCRIPTION
**Pull request by phonicmouse**
Thank you for taking the time to work on a PR for Awesome-Selfhosted!

To ensure your PR is dealt with swiftly please check the following:

- [x] Your submissions are formatted according to the guidelines. 
        
    ``[Name](http://homepage/) - Short description. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code)) `License` `Language```
- [x] Your additions are ordered alphabetically.
- [x] Your additions are [free software](https://en.wikipedia.org/wiki/Free_software), or if not they have been added to [non-free](non-free.md).
- [x] Any licenses you have added are in our [list of licenses](https://github.com/Kickball/awesome-selfhosted/blob/master/README.md#list-of-licenses).
- [x] You have searched the repository for any relevant issues or PRs.
- [x] Any category you are creating has the minimum requirement of 3 items.

### CODE REVIEW

**Comment by danger-awesome-Selfhosted** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Found 1 link issue</td>
    </tr>
  </tbody>
</table>

#### Link issue by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
2 | Dupe | https://github.com/phonicmouse/SharpPaste 


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by nodiscc** [comment]
It is not required to link to the source code twice, you can remove the 2nd source code link.
Does this require Microsoft IIS to run (ASP.NET server)? If yes it would be better to tag it `C#/ASP.NET`

**Comment by phonicmouse** [comment]
@nodiscc This requires IIS Server, but it can run also standalone, thanks to Nancy.

**Comment by phonicmouse** [comment]
Anyway, I'll add ASP.NET

**Comment by phonicmouse** [comment]
Done. Waiting for review.

**Comment by Kickball** [comment]
@phonicmouse the PR has now been merged, thanks for your patience.

**Comment by phonicmouse** [comment]
@Kickball Thank you for accepting my software!

**Comment by phonicmouse** [comment]
@Kickball @nodiscc I have to report a merge error:

**Comment by Kickball** [comment]
@phonicmouse the formatting issue has been resolved.

**Comment by phonicmouse** [comment]
@Kickball Perfect, thank you!

**Pull request merged**
