### PR TITLE
Add Lektor CMS

### PR DESCRIPTION
**Pull request by niijv**

### CODE REVIEW

**Comment by Kickball** [comment]
Please remove a language or combine them in the `Language/Language` fashion.

**Comment by nodiscc** [comment]
> Lektor is a static website generator. It builds out an entire project from static files into many individual HTML pages and has a built-in admin UI and minimal desktop app.

https://github.com/Kickball/awesome-selfhosted/pulls?utf8=%E2%9C%93&q=static We do not list static site generators. See https://github.com/Kickball/awesome-selfhosted#static-site-generators

**Comment by mitsuhiko** [comment]
@nodiscc can you clarify by what logic Grav qualifies for that list but Lektor does not?

**Comment by nodiscc** [comment]
Hi @mitsuhiko after reviewing Grav a bit more I think it does not qualify either. Basically everything that is listed on https://staticsitegenerators.net/ does not qualify. This is to avoid duplication of effort. If you want to submit a patch to remove stray static site generators it would be great. Thanks for noticing.

**Pull request closed without merging**
