### PR TITLE
Remove Minio

### PR DESCRIPTION
**Pull request by nodiscc**
Thank you for taking the time to work on a PR for Awesome-Selfhosted!

To ensure your PR is dealt with swiftly please check the following:

- [ ] Your submissions are formatted according to the guidelines. 

> Minio is an open source object storage server with Amazon S3 compatible API. 

Since it's just an object store for Docker-based infrastructures, (and not a file sharing service proper), this would be more suited to https://github.com/n1trux/awesome-sysadmin/

It was added in #705, @timbe16 maybe you'd like to submit it there instead

### CODE REVIEW

**Comment by danger-awesome-Selfhosted** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please check PR guidelines and check the boxes.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by Lawri-van-Buel** [comment]
Minio is not for Docker based infrastructures, its for container based (which would encompass also things like plain old jails from bsd, LXC containers, Virtual Machines, etc.) 

Its usecases are not to be a file sharing service but to be a Object storage server, mimicking AWS's S3 Service.

So It is a self hosted replacement for AWS S3, and can be used in a plurality of other self-hosted solutions as a drop in place replacement for AWS S3, such as Rocket chat, Nextcloud/Owncloud, etc.

**Comment by nodiscc** [comment]
I see your point. It's probably better to move it to [Misc/Other](https://github.com/Kickball/awesome-selfhosted#miscother) for the time being, the Misc/Other category could be reorganized into sub-categories such as _Genealogy_, _API servers_, _Object stores_, _Mind maps_, ...

I will take care of it, thanks @Lawri-van-Buel for your input

**Comment by evaryont** [comment]
Minio is a good example of a project that stradles both selfhosted and sysadmin. It's not particularly useful for end users -- they won't care nor take advantage of the API access, so there are much better alternatives for a simple file uploading tool. On the other hand, it is *specifically* meant for self-hosting, just that the primary users are probably sysadmins too. Is that enough?

**Comment by dyu** [comment]
> On the other hand, it is specifically meant for self-hosting

100% on that.  I don't think it should be moved to misc/other

**Comment by nodiscc** [comment]
Closing following @Lawri-van-Buel @evaryont  @dyu advices, thank you, very appreciated. Minio stays where it is.

**Pull request closed without merging**
