### PR TITLE
Add Up1 - A Client-side Encrypted Image Host

### PR DESCRIPTION
**Pull request by TwizzyDizzy**

### CODE REVIEW

**Comment by nodiscc** [comment]
@TwizzyDizzy Check https://github.com/TwizzyDizzy/awesome-selfhosted/pull/1

**Comment by TwizzyDizzy** [comment]
Yeah right, indeed I forgot the demo. Thanks for adding it. Merged.

**Comment by AndyR207** [comment]
Needs sorting correctly alphabetically and there needs to be a full stop after the description.

**Comment by TwizzyDizzy** [comment]
Well now we should be good, at last.

**Comment by AndyR207** [comment]
Looks good to me

**Pull request merged**
