### PR TITLE
Added Kazoo to IPBXs

### PR DESCRIPTION
**Pull request by fredguth**
I was in doubt where to put it, it could also be in SIP.

### CODE REVIEW

**Comment by nodiscc** [comment]
@fredguth Please order the section alphabetically. Otherwise fine.

**Comment by AndyR207** [comment]
You have a double space between your description and Source Code link. Please correct this.

**Comment by Kickball** [comment]
@fredguth [fredguth/awesome-selfhosted#1](https://github.com/fredguth/awesome-selfhosted/pull/1) completes the formatting fixes identified above.

**Comment by Kickball** [comment]
Redone in #771.

**Pull request closed without merging**
