### PR TITLE
Update GoAccess license and description.

### PR DESCRIPTION
**Pull request by allinurl**

### CODE REVIEW

**Comment by nodiscc** [comment]
Hi @allinurl I propose moving GoAccess to [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin). We are currently moving monitoring/server admin tools there (issue https://github.com/Kickball/awesome-selfhosted/issues/127). I've submitted a pull request [to add it]( https://github.com/n1trux/awesome-sysadmin/pull/166).

I can recommend GoAccess, terminal and HTML views are very well done, with plenty of [options](https://goaccess.io/man). It's a great tool.

**Comment by allinurl** [comment]
Hi @nodiscc, Glad to hear that :) and thank you for submitting the PR to sysadmin. Should I go ahead and close this then?

**Comment by nodiscc** [comment]
Why not, or we can leave it open until https://github.com/n1trux/awesome-sysadmin/issues/166 is merged. Hey, I see you wrote goaccess, hats off! It's part of my routine server maintenance/reporting script. 

<sup>Can it list every visitor IP sorted by number of requests? I'm stuck with ` zcat -f /var/log/apache2/access.log* | awk '{print $1}' | sort | uniq -c | sort -nr` as I can't figure out how to do it with goaccess I could open an issue if you want.</sup>

**Comment by allinurl** [comment]
You can set goaccess to display all parsed data using `--max-items=<num>`, however, only the `CSV` and the `JSON` output allow a maximum number greater than the default value of `366` (or `50` in the real-time HTML output) items per panel. So if you are looking to show all IPs on a JSON output, you can run it as:

    # zcat -f /var/log/apache2/access.log* | goaccess --log-format=COMBINED --max-items=<num_of_items_to_show> -a -d -o report.json

By default it will sort the panel by the number of requests (take a look at the `SORT-PANEL` option if needed). Now, if you only want to show the hosts/IP panel, just make sure to uncomment all panels except `ignore-panel HOSTS` from the **[config file](https://github.com/allinurl/goaccess/blob/master/config/goaccess.conf#L411)**.

Hope that helps, otherwise feel free to open an [**issue**](https://github.com/allinurl/goaccess).

**Pull request closed without merging**
