### PR TITLE
Added Groove Basin

### PR DESCRIPTION
**Pull request by cron410**

### CODE REVIEW

**Comment by jungle-boogie** [comment]
I propose this be sorted alphabetically.

**Comment by Kickball** [comment]
@jungle-boogie is right.

If you could put this in the appropriate position alphabetically then we can merge the pull request.

Thanks!

**Comment by cron410** [comment]
How do I change my pull request, or do I just make another?

**Comment by cron410** [comment]
Was that right? I'm kinda new to contributing to projects.

**Comment by nodiscc** [comment]
@cron410 this is right.

https://github.com/Kickball/awesome-selfhosted/pull/52/commits
https://github.com/Kickball/awesome-selfhosted/pull/52/files

**Pull request merged**
