### PR TITLE
Add Pepperminty Wiki

### PR DESCRIPTION
**Pull request by sbrl**
For the last year I've been working on [Pepperminty Wiki](https://github.com/sbrl/Pepperminty-Wiki), and I thought I'd add it here. It's an entire markdown-powered wiki built into a single file. It's currently very usable, but I have plans to bring a bunch of big features to it which I'll be working on whenever I get some time.

### CODE REVIEW

**Comment by nodiscc** [comment]
Thank you

**Comment by sbrl** [comment]
@nodiscc Right - I'll change the license to the appropriate code.

As for the reason, licenses confuse me rather (that's why I used [tldrlegal](http://tldrlegal.com/) to pick it), and I wanted a fairly permissive license that requires attribution. I don't understand all this stuff about patents and sublicensing and trademarks etc. If you've got a more suitable license, I'd be glad to change it.

**Comment by sbrl** [comment]
@nodiscc I've updated the license code. Is that ok?

**Comment by nodiscc** [comment]
Nope, please merge https://github.com/sbrl/awesome-selfhosted/pull/1

**Comment by sbrl** [comment]
@nodiscc Ummm oops! Thanks for the PR. I've merged it in.

**Comment by sbrl** [comment]
Yeah! Thanks for adding my Wiki software!

**Pull request merged**
