### PR TITLE
Add Factor.io to the Continuous Integration section

### PR DESCRIPTION
**Pull request by akhyrul**
From the homepage:

>  "It's like IFTTT (if-this-then-that) for Dev and DevOps"
> Factor.io is a simple way to automate developer workflows by defining them programmatically using the Factor.io syntax and running them using the Factor.io Server.

Still not sure about the license. Moreover I cannot find the source code anywhere other than Ruby Gem repository.

### CODE REVIEW

**Comment by nclements** [comment]
Looks like the source code is here: https://github.com/factor-io/factor

And license is MIT.

**Comment by nodiscc** [comment]
This should be added to https://github.com/Kickball/awesome-selfhosted#continuous-integration instead of automation

**Comment by akhyrul** [comment]
@nclements @nodiscc thanks! 
should I amend the commit or just create a new one?

**Comment by nodiscc** [comment]
@akhyrul as you wish, doesn't matter.

**Comment by akhyrul** [comment]
@nodiscc done, PR updated

**Pull request merged**
