### PR TITLE
Added Firefly III to financial tools

### PR DESCRIPTION
**Pull request by stickgrinder**
My first addition, I hope I respected the rules.
Mind that no license tag is there since the license seem  to me a custom one.

I can fix this if needed but I need more info.

### CODE REVIEW

**Comment by nodiscc** [comment]
> Mind that no license tag is there since the license seem to me a custom one.

The license (from https://github.com/JC5/firefly-iii/blob/master/LICENSE) is [MIT](https://opensource.org/licenses/MIT).

**Comment by stickgrinder** [comment]
Thanks, I'll amend this. Do you want me to squash my commits?

**Comment by nodiscc** [comment]
> Do you want me to squash my commits?

It doesn't really matter, either way is fine. Thanks

**Comment by AndyR207** [comment]
Please see the following section taking from the contribution guidelines:

The syntax for links is [Name](http://homepage/) - Short description. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code)) `License` `Language`. All projects should have their license and main server-side language/platform/requirement listed, and a description at most 250 characters long.

Your description is 296 characters.

**Comment by stickgrinder** [comment]
Hi @AndyR207, thanks for your feedback.

I should have fixed my entry. I didn't spot the contribution guidelines at the bottom of the README, I'm very sorry!

I scan throught it and it seems to me that now the entry is ok! Let me know if I'm still missing something.

**Pull request merged**
