### PR TITLE
added tania farming management

### PR DESCRIPTION
**Pull request by cavebeat**
Thank you for taking the time to work on a PR for Awesome-Selfhosted!

To ensure your PR is dealt with swiftly please check the following:

- [x] Your submissions are formatted according to the guidelines. 
        
    ``[Name](http://homepage/) - Short description. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code)) `License` `Language` ``

- [x] Your additions are ordered alphabetically.
- [x] Your additions are [Free software](https://en.wikipedia.org/wiki/Free_software), or if not they have been added to [non-free](non-free.md).
- [x] Your additions are not already listed at [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin) (IT infrastructure management), [staticgen.com](https://www.staticgen.com/) or [staticsitegenerators.net](https://staticsitegenerators.net/) (static site generators).
- [x] Any licenses you have added are in our [list of licenses](https://github.com/Kickball/awesome-selfhosted/blob/master/README.md#list-of-licenses).
- [x] You have searched the repository for any relevant issues or PRs.
- [x] Any category you are creating has the minimum requirement of 3 items.

### CODE REVIEW

**Comment by cavebeat** [comment]
the subcategory ERP / Agriculture is related to https://github.com/Kickball/awesome-selfhosted/pull/1141

**Comment by danger-awesome-Selfhosted** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Found 1 link issue</td>
    </tr>
  </tbody>
</table>

#### Link issue by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
3 | Dupe | https://github.com/Tanibox/tania 


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by cavebeat** [comment]
Dupe link error fixed

**Comment by mrinc** [comment]
Domain doesn't work - http://gettania.org

I think they are having DNS issues. If they don't resolve within a few hours, rather just have the github link on the merge?

**Comment by nodiscc** [comment]
Website is still down. @mrinc ar you ok to change the entry to

     * [tania](https://github.com/Tanibox/tania) - A PHP based, free, and open source farming management system. `Apache` `PHP`

?

**Comment by cavebeat** [comment]
gnahh, it's strange, the dns problem started to occur hours after my PR, i swear i have checked it and had a look at the project homepage myself. 

should i remove the hp?

**Comment by Kickball** [comment]
@cavebeat given that the page is still down it would be best to change the entry to fit @nodiscc 's suggestion.

Once that has been done this PR is ready from my point of view.

**Comment by danger-awesome-Selfhosted** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please rebase to get rid of the merge commits in this Pull Request</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Pull request merged**
