### PR TITLE
Added bbPress and attempted to clarify difference w/BuddyPress

### PR DESCRIPTION
**Pull request by taoeffect**
Thank you for taking the time to work on a PR for Awesome-Selfhosted!

To ensure your PR is dealt with swiftly please check the following:

- [x] Your submissions are formatted according to the guidelines. 
        
    ``- [Name](http://homepage/) - Short description, less than 250 characters. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code)) `License` `Language` ``

- [x] Your additions are ordered alphabetically.
- [x] Your additions are [Free software](https://en.wikipedia.org/wiki/Free_software), or if not they have been added to [non-free](non-free.md).
- [x] Your additions are not already listed at [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin) (IT infrastructure management), [staticgen.com](https://www.staticgen.com/) or [staticsitegenerators.net](https://staticsitegenerators.net/) (static site generators).
- [x] Any licenses you have added are in our [list of licenses](https://github.com/Kickball/awesome-selfhosted/blob/master/README.md#list-of-licenses).
- [x] You have searched the repository for any relevant [issues](https://github.com/Kickball/awesome-selfhosted/issues) or [PRs](https://github.com/Kickball/awesome-selfhosted/pulls).
- [x] Any category you are creating has the minimum requirement of 3 items.
- [x] Any software project you are adding to the list is actively maintained.

### CODE REVIEW

**Comment by danger-awesome-Selfhosted** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Found 2 link issues</td>
    </tr>
  </tbody>
</table>

#### Link issues by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
3 | [403](https://httpstatuses.com/403) | https://bbpress.trac.wordpress.org/browser/trunk 
4 | [403](https://httpstatuses.com/403) | https://buddypress.svn.wordpress.org/trunk/ 


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by taoeffect** [comment]
don't know what bot is complaining about, those links work?

**Comment by nodiscc** [comment]
@taoeffect So buddypress requires bbpress to work?

**Comment by taoeffect** [comment]
@nodiscc That's my reading of it. BuddyPress adds some extra social/community features on top of it.

**Comment by nodiscc** [comment]
Apparently not:

 * https://whatswp.com/buddypress-vs-bbpress/
 * https://wisdmlabs.com/blog/beginners-guide-bbpress-vs-buddypress-basics/
 * https://duckduckgo.com/?q=bbpress+vs+buddypress ...

They are independent WordPress plugins, they can work in conjunction, but neither is a requirement for the other.

**Comment by nodiscc** [comment]
Oh sorry, I didn't mean to close this. If you can remove the `enhances bbpress` link, and make the bbpress entry a single line (it's split over 2 lines), this would be good to merge.

**Comment by taoeffect** [comment]
@nodiscc OK, done. I'll note that in one of the links I found on the BuddyPress website/docs it seemed to suggest that it used bbPress to handle the forums. I could be mistaken, but don't have time to look into it closely.

**Pull request merged**
