### PR TITLE
add Jirafeau and transfer.sh to file sharing category

### PR DESCRIPTION
**Pull request by fengshaun**

### CODE REVIEW

**Comment by nodiscc** [comment]
Transfer.sh is a command-line tool so it doesn't fit this list.
Jirafeau is already listed here https://github.com/Kickball/awesome-selfhosted#single-clickdrag-n-drop-upload

**Comment by fengshaun** [comment]
transfer.sh has a server component which is needed for the client. The cmdline utility is only the client. look at transfersh-server in the same repo.

**Comment by nodiscc** [comment]
Whoops, reopening (it has a server component, like unison). Can you remove Jirafeau from the PR and reorder the section alphabetically? Thanks.

**Comment by fengshaun** [comment]
Updated! Thanks!

**Comment by nodiscc** [comment]
:+1:

**Pull request merged**
