### PR TITLE
Travis Test

### PR DESCRIPTION
**Pull request by n8225**
Thank you for taking the time to work on a PR for Awesome-Selfhosted!

To ensure your PR is dealt with swiftly please check the following:

- [x] Your submissions are formatted according to the following requirements:
        
``- [Name](http://homepage/) - Short description, less than 250 characters. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``

Depends on proprietary services:

``- [Name](http://homepage/) `⚠` - Short description, less than 250 characters. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``

Non-free software in `non-free.md`:

``- [Name](http://homepage/) `⊘ Proprietary` - Short description, less than 250 characters. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `Language` ``

- [x] Your additions are ordered alphabetically.
- [x] Your additions are [Free software](https://en.wikipedia.org/wiki/Free_software), or if not they have been added to [non-free](non-free.md) and marked `⊘ Proprietary`.
- [x] If your additions depend on proprietary services outside the user's control, they must be marked `⚠`.
- [x] Your additions are not already listed at [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin) (IT infrastructure management), [staticgen.com](https://www.staticgen.com/) or [staticsitegenerators.net](https://staticsitegenerators.net/) (static site generators).
- [x] Your additions have their `License` main server-side `Language`/platform/requirement listed.
- [x] Any licenses you have added are in our [list of licenses](https://github.com/Kickball/awesome-selfhosted/blob/master/README.md#list-of-licenses).
- [x] You have searched the repository for any relevant [issues](https://github.com/Kickball/awesome-selfhosted/issues) or [PRs](https://github.com/Kickball/awesome-selfhosted/pulls), including closed ones.
- [x] If the main link of your addition points to the program's source code, there is no need to add a duplicate _Source Code_ link. The _Demo_ and _Clients_ links are not mandatory.
- [x] Any category you are creating has the minimum requirement of 3 items. If not, your addition may be inserted into `Misc/Other`.
- [x] Any software project you are adding to the list is actively maintained.

### CODE REVIEW

**Comment by danger-awesome-Selfhosted** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please check PR guidelines and check the boxes.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by nodiscc** [comment]
Excellent, #1777 fixes the token problem mentioned at #878. @n8225 have you tried submitting an incomplete PR (duplicate link or dead link or not checking all the boxes) to check that Danger automatic PS comments still work?

**Comment by n8225** [comment]
I did test unchecked boxes and it did provide a warning.  However, I'm just now noticing the js script didn't fail the PR as it should have(I think my test PR was missing too much to be tested by the script). I'll throw another test at it tomorrow.

**Comment by nodiscc** [comment]
Checks for https://github.com/Kickball/awesome-selfhosted/pull/1779 are failing because Danger can't find the API key: https://travis-ci.org/Kickball/awesome-selfhosted/builds/573778362

Do you want to remove Danger altogether and see how it goes for a while?

**Comment by n8225** [comment]
I haven't searched much but I haven't seen any alternatives to Danger.  Currently I'm leaning towards putting it back the way it was.  That was the recommended setup from https://danger.systems/guides/getting_started.html#setting-up-an-access-token  I'ts an account I created solely for this purpose and the api key only has public_repo access.

**Comment by Kickball** [comment]
I plan to make an organisation tomorrow with both of you setup in it. You should hopefully then be able to sign up as needed, as you know I have been quite inactive due to other committments.

**Comment by n8225** [comment]
After further testing I'm finding that Danger will not work without the API key exposed(travis, github actions...) So I think I'm just going to remove Danger.  We will still get a pass/fail from Travis or Github Actions and would be able to see what failed in the logs.

**Comment by nodiscc** [comment]
> So I think I'm just going to remove Danger.

Looks like the best thing to do, and also cuts down on external dependencies. We can find ways to make CI checks more contributor friendly.

> I plan to make an organisation tomorrow with both of you setup in it.

Would be great! I had setup the https://github.com/awesome-selfhosted organization a while ago, just invited you there, maybe you could transfer the repo to this org?

**Pull request merged**
