### PR TITLE
Add Bludit (Blogging Platforms)

### PR DESCRIPTION
**Pull request by Joery**
Thank you for taking the time to work on a PR for Awesome-Selfhosted!

To ensure your PR is dealt with swiftly please check the following:

- [X] Your submissions are formatted according to the guidelines. 
        
    ``[Name](http://homepage/) - Short description. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code)) `License` `Language```
- [X] Your additions are ordered alphabetically.
- [X] Your additions are [free software](https://en.wikipedia.org/wiki/Free_software), or if not they have been added to [non-free](non-free.md).
- [X] Any licenses you have added are in our [list of licenses](https://github.com/Kickball/awesome-selfhosted/blob/master/README.md#list-of-licenses).
- [X] You have searched the repository for any relevant issues or PRs.
- [x] Any category you are creating has the minimum requirement of 3 items.

### CODE REVIEW

**Comment by Joery** [comment]
Note; I'm not the creator/maintainer of this application.

**Comment by danger-awesome-Selfhosted** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please check PR guidelines and check the boxes.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by Kickball** [comment]
It is not clear if the privacy issues highlighted in [#373](https://github.com/dignajar/bludit/issues/373) would make this dependent on external services as are other items in the list.

**Comment by nodiscc** [comment]
@Joery @Kickball correct, if sharing with bludit.com is opt-out then it should be marked as dependent on a third party service.

 https://github.com/Kickball/awesome-selfhosted/blob/master/.github/CONTRIBUTING.md :

> The ⚠ character must be inserted for software that relies on a third party service the user does not control, e.g [Name](http://homepage/) `⚠` - Short description....

**Comment by Joery** [comment]
My bad, added the ⚠

**Pull request merged**
