### PR TITLE
Large update for all sections up to the CMS section

### PR DESCRIPTION
**Pull request by Kovah**
Updated the links, licenses and main programming languages

### CODE REVIEW

**Comment by nodiscc** [comment]
awwwesome work @Kovah ! Thanks.
I have added comments on some changes, can you fix those? (especially the unneeded FREE license entry) Then it should be good to merge.

There are still a few bogus language entries (`JavaScript, NodeJS`) which were already there in the previous version, that we should fix _after_ merging. This is a large patch that will cause merge conflicts with other PRs if we wait for too long. I suggest fixing the few errors and merging it ASAP.

**Comment by Kovah** [comment]
:+1:

**Comment by nodiscc** [comment]
:+1:

**Comment by Kovah** [comment]
Do you want to wait for some more commits until merge?

**Comment by nodiscc** [comment]
Please wait for the merge before adding more commits. If you want to start working now, but not have your commits in this PR, you can start a new branch from your current `master` (eg. `git checkout -b more-work`) and propose merging your `more-work` in another PR.

@Kickball @AndyR207 please review?

**Comment by AndyR207** [comment]
[Countly](https://count.ly) - Real time mobile & web analytics, crash reporting and push notifications platform ([Source Code](https://github.com/countly)) `AGPL` `Javascript`
Missing full stop

    [htmly](https://www.htmly.com/) - Databaseless Blogging Platform (Flat-File Blog). ([Source Code]((https://github.com/danpros/htmly)), [Demo](https://www.htmly.com/demo/)) `GPLv2` `PHP`
Bad brackets and Demo needs to come Before Source Code

    [Bookie](https://github.com/bookieio/Bookie) - Python based delicious.com replacement. ([Firefox addon](https://github.com/bookieio/bookie-firefox), [Demo](http://bmark.us/), [Documentation](http://docs.bmark.us/) `unlicensed` `Python`
Firefox Addon and Documentation are not valid. Please remove them. Please capitalize "Unlicensed" although I feel like this entire entry should be removed because I don't think we're accepting "Unlicensed" as a valid thing?? @Kickball @nodiscc 

    [Firefox Sync Server](https://docs.services.mozilla.com/howtos/run-sync-1.5.html) - Sync Firefox bookmarks, passwords, history, tabs, preferences. ([Source Code](https://github.com/mozilla-services/syncserver)) `unlicensed` `Python`
See above comment about licensing.

    [Lobsters](https://lobste.rs) - Run your own link aggregation site. ([Source Code](https://github.com/jcs/lobsters))
No license or language

    [Shaarli](https://github.com/shaarli/Shaarli) - Personal, minimalist, super-fast, no-database bookmarking and link sharing plaform. ([Demo](http://shaarlidemo.tuxfamily.org/Shaarli/) `demo/demo`) `Zlib` `PHP`
Remove the demo/demo part

    [calypso](http://keithp.com/calypso/) - A python-based CalDAV/CardDAV server. ([Source Code](http://keithp.com/cgi-bin/gitweb.cgi?p=calypso.git;a=tree)) `GPLv3`
Missing language

    [DAViCal](http://www.davical.org/) - A server for calendar sharing (CalDAV). ([Source Code](https://gitlab.com/davical-project/davical)) `MIT`
See above

    [ownCloud calendar](https://doc.owncloud.org/server/7.0/user_manual/pim/calendar.html) - The ownCloud Calendar app enables you to create and edit events, synchronize to other calendars you might use, and create new, personalized calendars. ([Source Code ownCloud < 9](https://github.com/owncloud/calendar), [Source Code ownCloud 9+](https://github.com/owncloud/calendar-rework)) `AGPLv3` `PHP`
Can't have two Source Code links, remove one and change the label to just "Source Code"

    [Kandan](http://getkandan.com/) – Kandan is an Open Source Alternative to HipChat. ([Source Code](https://github.com/kandanapp/kandan)) `AGPLv3` `Ruby`
This one is going to seem trivial but that hypen needs to be a short hyphen as opposed to a long one

    [Lets-Chat](http://sdelements.github.io/lets-chat/) - A self hosted chat suite written in Node. ([Source](https://github.com/sdelements/lets-chat)) `MIT` `JavaScript, NodeJS`
Source Code

    [Rocket.Chat](https://rocket.chat/) – Teamchat solution similar to Gitter.im or Slack. ([Source Code](https://github.com/RocketChat/Rocket.Chat)) `MIT`
Missing language

    [hMailServer](https://www.hmailserver.com) - Open source e-mail server for Microsoft Windows. ([Source Code](https://github.com/hmailserver/hmailserver)) `C++`  
Missing License

     [iRedMail](http://www.iredmail.org/) - Full-featured mail server solution based on Postfix and Dovecot.
Missing license/lang

    [Citadel](http://www.citadel.org/) - Feature packed, easy, versatile, and powerful mail server, thanks to exclusive "rooms" based architecture. ([Source Code](http://code.citadel.org/?p=citadel.git;a=summary))
See above

    [Exim](http://www.exim.org/) - Message transfer agent (MTA) developed at the University of Cambridge. `GPL`
Missing language

    [OpenSMTPD](https://opensmtpd.org/) - Secure SMTP server implementation from the OpenBSD project. `ISC`
Missing language

    [Qmail](http://www.qmail.org/top.html) - Secure Sendmail replacement. `CC0`
Missing language

    [Sendmail](http://www.sendmail.com/sm/open_source/) - Message transfer agent (MTA).
Missing license/lang

    [Cyrus IMAP/POP3](http://cyrusimap.org/) - Intended to be run on sealed servers, where normal users are not permitted to log in.
See above

    [Roundcube](https://roundcube.net) - Browser-based IMAP client with an application-like user interface. ([Screenshots](https://roundcube.net/screens/)) ([Source Code](https://github.com/roundcube/roundcubemail/)) `GPLv3` `PHP`
Remove Screenshots

    [Asterisk](http://www.asterisk.org/) - An easy to use but advanced IP PXB system, VoIP gateway and conference server `GPLv2` `C`
Needs a full stop after the description

    [FreeSWITCH](https://freeswitch.org/) - Scalable open source cross-platform telephony platform ([Source Code](https://freeswitch.org/stash/projects/FS/repos/freeswitch/browse)) `MPLv2` `C`
See above

    [Kamailio](http://www.kamailio.org/w/) - Modular SIP server (registrar/proxy/router/etc) ([Source Code](https://github.com/kamailio/kamailio)) `GPLv2` `C`
See above

    [Ostel](https://dev.guardianproject.info/projects/ostel/wiki/Server_Documentation) - Secure SIP telephony setup with ZRTP encryption `GPLv3` `Ruby`
See above

    [Friendica](http://friendica.com/) - Social Communication Server. ([Source Code](https://github.com/friendica/friendica)) `AGPLv3`
Missing language

    [Jappix](https://jappix.com/) - Jappix is an open social platform, that let's you easily get or keep in touch with everyone. ([Source Code](https://github.com/jappix/jappix)) `AGPLv3`
Missing language

    [Loomio](https://www.loomio.org/) - Loomio is a collaborative decision-making tool that makes it easy for anyone to participate in decisions which affect them.  ([Source Code](https://github.com/loomio/loomio)) `AGPLv3` `Ruby`
Double space after description

    [Oxwall](http://www.oxwall.org/) Oxwall is used for a wide range of projects starting from family sites and custom social networks to collaboration tools and enterprise community solutions. ([Source Code](https://bitbucket.org/oxwall/public) `CPALv1` `PHP`
Missing hyphen between URL and description, missing closing bracket after Source Code

    [PPnet](https://github.com/pixelpark/ppnet) Create and host your own social network. `MIT` `JavaScript`
Missing hyphen between URL and description

    [Reddit](https://www.reddit.com/) - Social networking and news website where registered community members can submit content. ([Demo](https://www.reddit.com/) [Source Code](https://github.com/reddit/reddit)) `CPALv1` `Python`
Missing comma after demo link

    [ejabberd](https://www.ejabberd.im/) - XMPP instant messaging server. ([Source](https://github.com/processone/ejabberd)) `GPL` `Erlang`
Source -> Source Code

    [Metronome IM](https://lightwitch.org/metronome) - Fork of Prosody IM. ([Source](http://code.lightwitch.org/)) `MIT` `Lua`
See above

    [MongooseIM](https://www.erlang-solutions.com/products/mongooseim.html) - Fork of ejabberd. ([Source](https://github.com/esl/MongooseIM)) `MIT` `Erlang`
See above

    [Openfire](http://www.igniterealtime.org/projects/openfire/) - Real time collaboration (RTC) server. ([Source](https://github.com/igniterealtime/Openfire)) `Apache` `Java`
See above

    [Prosody IM](http://prosody.im/) - Feature-rich and easy to configure XMPP server. ([Source](http://hg.prosody.im/)) `MIT` `Lua`
See above

    [Tigase](http://www.tigase.net/content/tigase-xmpp-server) - XMPP server implementation in Java. `Java`
Missing license

    [Candy](http://candy-chat.github.io/candy/) - Multi user XMPP client written in Javascript. ([Source](https://github.com/candy-chat/candy)) `MIT` `JavaScript`
Source -> Source Code

    [Converse.js](https://conversejs.org/) - A free and open-source XMPP chat client in your browser ([Source](https://github.com/jcbrand/converse.js)) `MPLv2` `Javascript`
Full stop after description, Source -> Source Code

    [Kontalk](http://kontalk.org/) – Kontalk is an Open Source Messenger, similiar to WhatsApp (app for android only currently), including end-to-end encryption, server is based on Tigase XMPP Server - ([Source Code](https://github.com/kontalk)) `GPLv3`
Hyphen needs replacing with short hypen, there should be a full stop after the description not a hyphen, missing language

    [Libervia](http://wiki.goffi.org/wiki/Libervia/en) - Web frontend from Salut à Toi ([Source Code](http://repos.goffi.org/libervia)) `AGPLv3` `Python`
Missing full stop after description

    [99ko CMS](http://www.99ko.org/) - 99ko allows you to create a website in minutes without knowledge of Web development. It does not use a database server but relies on simple text files (JSON format) to store your data. ([Source Code](https://github.com/99ko-project/99ko-cms))
Missing license and language

    [GetSimple CMS](http://get-simple.info/) - The Simplest Content Management System. Ever. `GPLv3`
Missing language

    [ImpressPages CMS](https://www.impresspages.org/) - Easy code meets easy admin. ([Demo](https://www.impresspages.org/demo), [Source Code](https://github.com/impresspages/ImpressPages)) `GPLv3`/`MIT`  `PHP`
Dual language needs to removed or condensed, double space between license and language

    [daloRADIUS](http://www.daloradius.com) - Open-source web management platform for FreeRADIUS-based deployments. ([Source Code](https://github.com/lirantal/daloradius)) `GPLv2`
Missing language

    [OpenCA OCSPD](https://pki.openca.org/projects/ocspd/) - An [OCSP](https://en.wikipedia.org/wiki/Online_Certificate_Status_Protocol) Responder.
Missing license and language

    [OpenID/OpenID Connect](http://openid.net/developers/libraries/) - A Simple Identity layer on top of OAuth 2.0
Missing full stop after description, missing license and language

**Comment by nodiscc** [comment]
@AndyR207 these errors were already present beforehand. We can't expect Kovah to fix the whole file. Good to merge.

**Comment by nodiscc** [comment]
@AndyR207 reminder to fix the set of problems you mentioned in https://github.com/Kickball/awesome-selfhosted/issues/470

**Comment by Kickball** [comment]
The issues were also moved to #471.

**Pull request merged**
