### PR TITLE
Added Kinto storage service

### PR DESCRIPTION
**Pull request by leplatrem**

### CODE REVIEW

**Comment by nodiscc** [comment]
Thanks @leplatrem It looks like Javascript is only used client-side. If this is the case please change the language to just `Python`

**Comment by leplatrem** [comment]
Yes indeed, I'll change it then.

**Comment by leplatrem** [comment]
Updated, thanks!

**Comment by AndyR207** [comment]
Please sort this entry into alphabetical order.

**Comment by leplatrem** [comment]
Done!

**Comment by Kickball** [comment]
Merged, thanks for the commit!

**Pull request merged**
