### PR TITLE
add back to top link for each section

### PR DESCRIPTION
**Pull request by nodiscc**
Preview at ~~https://github.com/Kickball/awesome-selfhosted/blob/a6b35f0d4801a85ff84c571c881767ea8048b090/README.md~~ https://github.com/Kickball/awesome-selfhosted/blob/a3660e997c9ebbf39254b16473ae0b3b81478d2a/README.md

Alternatively we could just add a [`^`](#awesome-selfhosted) in the section titles but it would affect the table of contents.

### CODE REVIEW

**Comment by Kickball** [comment]
Looks good to me. Just a ping for @AndyR207 to make sure we remember to consider this for the scanner.

**Comment by n8225** [comment]
I like it

**Comment by nodiscc** [comment]
Hey I just noticed that it works exactly one time. After you've clicked  `back to top` once, subsequent clicks will do nothing. Can someone confim?

A workaround is to use  `#` as the link target

**Comment by Kickball** [comment]
Just checked and encountered the same issue as @nodiscc. The problem seems to be that the top of page link cannot be clicked twice in a row, if you click something in between the back to top works. (Back to Top -> DNS -> Back to Top - _works_) (Back to Top -> Back to Top - _doesn't work_)

**Comment by nodiscc** [comment]
Workaround added

**Comment by Kickball** [comment]
Nice fix, good to merge for me. Just got the merge conflict.

**Comment by n8225** [comment]
I just fixed the merge conflict if you want to look over it again.

**Comment by Kickball** [comment]
@AndyR207 why was needs work added?

@nodiscc @n8225 it looks good to merge to me apart from the merge conflict.

**Pull request merged**
