### PR TITLE
Add GlusterFS under Distributed Filesystems

### PR DESCRIPTION
**Pull request by justinclift**

### CODE REVIEW

**Comment by AndyR207** [comment]
Please remove the 'License Info' section, it is not a valid section. We need to cut it down to only one license. Either LGPLv3 or GPLv2. I'm open to suggestions from everyone else which one it should be.

**Comment by justinclift** [comment]
No worries about removing the license section.  Removing one of the licenses from a __literally__ dual licensed project :wink: kind of makes things inaccurate though.

Are there utils or something which auto-process that information, and might get mucked up?

**Comment by justinclift** [comment]
@vbellur Thoughts? :smile:

**Comment by nodiscc** [comment]
@justinclift `LGPLv3/GPLv2` would be ok.

**Comment by justinclift** [comment]
Thanks, will update it now. :smile:

**Comment by justinclift** [comment]
Updated. :smile:

**Comment by Kickball** [comment]
@justinclift thanks for the PR, will be merging it now.

We are working on a [system](https://github.com/AndyR207/awesome-selfhosted-com) to help us with development, the solution @nodiscc will work better with the system.

**Comment by justinclift** [comment]
Thanks, that's great. :smile:

**Pull request merged**
