### PR TITLE
Grafana & Hastic projects

### PR DESCRIPTION
**Pull request by jonyrock**
Adding to tools for processing time series data.

### CODE REVIEW

**Comment by danger-awesome-Selfhosted** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please provide a summary in the Pull Request description</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by jonyrock** [comment]
add description

**Comment by jonyrock** [comment]
Should I fix anything else? Looks like Travis failed because I didn't add description to PR.
But I fixed it later.

**Comment by jonyrock** [comment]
I think I should remake it without Grafana

**Comment by jonyrock** [comment]
@Kickball , my pleasure https://github.com/Kickball/awesome-selfhosted/pull/1404

**Pull request closed without merging**
