### PR TITLE
Add ZeroNet

### PR DESCRIPTION
**Pull request by mightyfree**
Added ZeroNet to satisfy issue #919. Self-hosting solutions is the best category due to its use for distributing websites. This is a hybrid self-hosted application, as it utilizes the BitTorrent network.

Thank you for taking the time to work on a PR for Awesome-Selfhosted!

To ensure your PR is dealt with swiftly please check the following:

- [x] Your submissions are formatted according to the guidelines. 
        
    ``[Name](http://homepage/) - Short description. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code)) `License` `Language` ``

- [x] Your additions are ordered alphabetically.
- [x] Your additions are [Free software](https://en.wikipedia.org/wiki/Free_software), or if not they have been added to [non-free](non-free.md).
- [x] Your additions are not already listed at [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin) (IT infrastructure management), [staticgen.com](https://www.staticgen.com/) or [staticsitegenerators.net](https://staticsitegenerators.net/) (static site generators).
- [x] Any licenses you have added are in our [list of licenses](https://github.com/Kickball/awesome-selfhosted/blob/master/README.md#list-of-licenses).
- [x] You have searched the repository for any relevant issues or PRs.
- [x] Any category you are creating has the minimum requirement of 3 items.

### CODE REVIEW

**Comment by danger-awesome-Selfhosted** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Found 1 entries with syntax error(s).</td>
    </tr>
  </tbody>
</table>

#### Syntax Issues

 Name | Entry
----|----------------------
ZeroNet |   * [ZeroNet](https://zeronet.io/) `⚠` - Open, free, and uncensorable websites, 
 

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by mightyfree** [comment]
@nodiscc Custom is a subcategory of Communication. ZeroNet is a website hosting platform that utilizes BitTorrent so perhaps it would be better suited under File-Sharing & Synchronization or Self-hosting Solutions.

**Comment by mightyfree** [comment]
@nodiscc I see there are other similar platforms in the custom category. Perhaps the categories can be reorganized in the future. This one is good to go!

**Comment by nodiscc** [comment]
> I see there are other similar platforms in the custom category

Yes, that's why I suggested moving ZeroNet there

> Perhaps the categories can be reorganized in the future

Some reorganization is planned (eg. https://github.com/Kickball/awesome-selfhosted/issues/1146), but not started yet.

**Pull request merged**
