### PR TITLE
Added Email Marketing category and phpList app

### PR DESCRIPTION
**Pull request by samtuke**
Disclaimer: I hack on and work for phpList ;)

### CODE REVIEW

**Comment by samtuke** [comment]
@nodiscc phpList is not a mailing list manager in the usual sense of the term - mailing lists are for many-to-many communication, whereas phpList, and the hundreds of apps like it, are for one-to-many communication. Listing phpList as a mailing list application would, I fear, encourage confusion.

**Comment by nodiscc** [comment]
@samtuke I understand. I think we should try to avoid creating new sections that contain only one entry (the table of contents is already large), but in this case _Mailing lists_ would be confusing.

Is it ok to change the section title to _Newsletter management_? You should also add a section link in the TOC.

**Comment by samtuke** [comment]
@nodiscc Sounds good -- changed the section name to _Newsletter Management_, and added link in TOC.

**Comment by nodiscc** [comment]
Thanks!

**Pull request merged**
