### PR TITLE
Added miniProxy

### PR DESCRIPTION
**Pull request by icterine**
Added miniProxy to Proxy section

### CODE REVIEW

**Comment by nodiscc** [comment]
Please order the section alphabetically.

**Comment by icterine** [comment]
Ordered entire Proxy section alphabetically and commit as second change,

**Comment by AndyR207** [comment]
Looks good to me.

**Comment by nodiscc** [comment]
I didn't even realize that the section was _not_ ordered correctly in the first place. Thanks @icterine for fixing it.

**Pull request merged**
