### PR TITLE
Add Skygear

### PR DESCRIPTION
**Pull request by david90**
Add Skygear to list of self-hosting solutions. Skygear is a go-lang based mobile and web application backend.

### CODE REVIEW

**Comment by nodiscc** [comment]
> Skygear is an open source development kit

I think this should go to Misc/Other category. Self-hosting solutions as listed here are software suites/OS distributions for end users, that automate setting up and maintaining their self-hosted services

**Comment by david90** [comment]
Updated.

**Comment by Kickball** [comment]
Please change the license to just `Apache`.

**Comment by david90** [comment]
License updated to `Apache`

**Pull request merged**
