### PR TITLE
Add Asterisk

### PR DESCRIPTION
**Pull request by radriaanse**
Add Asterisk to the VoIP group

### CODE REVIEW

**Comment by Kickball** [comment]
Please order it alphabetically.

**Comment by radriaanse** [comment]
I'm sorry, it's done now.

**Comment by nodiscc** [comment]
@radriaanse can you rebase on the latest `master` please?
Your patch removes recent additions https://github.com/Kickball/awesome-selfhosted/pull/164/files

**Comment by radriaanse** [comment]
Should be good now, right?

**Comment by nodiscc** [comment]
Not exactly. Anyway I merged the Asterisk addition https://github.com/Kickball/awesome-selfhosted/commits/master. Thanks @radriaanse

**Comment by radriaanse** [comment]
I'm sorry. I started the PR from the Github website and is you want to rebase then later on it's a bit weird. But anyways thanks!

**Pull request closed without merging**
