### PR TITLE
Add Centrifugo

### PR DESCRIPTION
**Pull request by FZambia**
Hello! Added https://github.com/centrifugal/centrifugo to a list.

### CODE REVIEW

**Comment by danger-awesome-Selfhosted** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Found 1 entries with syntax error(s).</td>
    </tr>
  </tbody>
</table>

#### Syntax Issues

 Name | Entry
----|----------------------
Centrifugo |   * [Centrifugo](https://github.com/centrifugal/centrifugo) – Language-agnostic real-time messaging (Websockets or SockJS) server `MIT` `Go`


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by FZambia** [comment]
Sorry, don't see what's wrong with syntax..

**Comment by Kickball** [comment]
There is a '.' missing from the end of the description and the [demo](https://centrifugo.herokuapp.com/#/) is missing.

**Comment by FZambia** [comment]
@Kickball thanks, will fix a dot! Btw our [demo](https://centrifugo.herokuapp.com/) has a password `demo` - can I write this somehow in entry?

**Comment by nodiscc** [comment]
@FZambia it is preferable that you write down the login/pw on the demo site itself,

you can also write the username/password combination right after the Demo link, like `Tryton` in https://github.com/Kickball/awesome-selfhosted#money-budgeting-and-management.

**Comment by FZambia** [comment]
@nodiscc it's problematic as requires changes in source code - I deploy it right from source code using `Deploy to Heroku` button every time new server release out. I noticed that many entries have no demo at all - maybe if my fixed entry does not fit convenient format we can just omit demo from it.

**Comment by FZambia** [comment]
@Kickball so what should I do now?😄

**Comment by arylatt** [comment]
If you put an anchor in your README just before the demo you could link that? That way it'll take people straight to the demo section where the password and link is listed...

**Comment by FZambia** [comment]
@arylatt sure, done

**Pull request merged**
