### PR TITLE
Adds WTFDYUM (Why The Fuck Did You Unfollow Me)

### PR DESCRIPTION
**Pull request by jchampemont**
Disclaimer: I am the developer of WTFDYUM.

I created a new sub category for "Social Networks Tools", because I was not sure it fits inside "Social Networks and Forums". (WTFDYUM is definitely not a Social Network, neither a forum ;) ).

### CODE REVIEW

**Comment by Kickball** [comment]
Please change the formatting from:

* [WTFDYUM](https://github.com/jchampemont/WTFDYUM) a.k.a Why The Fuck Did You Unfollow Me - find out who stops following you on Twitter. ([Demo](https://www.wtfdyu.me/) [Source Code](https://github.com/jchampemont/WTFDYUM)) `Apache`

to

* [WTFDYUM](https://github.com/jchampemont/WTFDYUM) a.k.a Why The Fuck Did You Unfollow Me - find out who stops following you on Twitter. ([Demo](https://www.wtfdyu.me/), [Source Code](https://github.com/jchampemont/WTFDYUM)) `Apache` `Java`

**Comment by Kickball** [comment]
As for the unique aspects of this I'd like @nodiscc 's opinion on the new category and how we can format the aka section.

**Comment by nodiscc** [comment]
I think `Automation` is the proper category.

**Comment by Kickball** [comment]
It does seem to fit (not perfectly) the automation category best.

@jchampemont Please move it to the appropriate place in the automation section.

**Comment by jchampemont** [comment]
Regarding the features I plan to add some day, it fits the automation category :)

Thanks guys!

**Pull request merged**
