### PR TITLE
Axeloz vagrant lamp

### PR DESCRIPTION
**Pull request by axeloz**
Thank you for taking the time to work on a PR for Awesome-Selfhosted!

To ensure your PR is dealt with swiftly please check the following:

- [x] Your submissions are formatted according to the guidelines. 
        
    ``[Name](http://homepage/) - Short description. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code)) `License` `Language` ``

- [x] Your additions are ordered alphabetically.
- [x] Your additions are [Free software](https://en.wikipedia.org/wiki/Free_software), or if not they have been added to [non-free](non-free.md).
- [x] Your additions are not already listed at [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin) (IT infrastructure management), [staticgen.com](https://www.staticgen.com/) or [staticsitegenerators.net](https://staticsitegenerators.net/) (static site generators).
- [x] Any licenses you have added are in our [list of licenses](https://github.com/Kickball/awesome-selfhosted/blob/master/README.md#list-of-licenses).
- [x] You have searched the repository for any relevant issues or PRs.
- [x] Any category you are creating has the minimum requirement of 3 items.

### CODE REVIEW

**Comment by danger-awesome-Selfhosted** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Found 1 link issue</td>
    </tr>
  </tbody>
</table>

#### Link issue by [`awesome_bot`](https://github.com/dkhamsing/awesome_bot)

  Line | Status | Link
| ---: | :----: | --- |
2 | Dupe | https://github.com/axeloz/vagrant-lamp 


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by evaryont** [comment]
Is this really relevant to the list? It's a development tool rather than a user-facing application. Also, there is the relative young age and lack of attention compared to other established Vagrant based projects, like [Homestead](https://laravel.com/docs/5.5/homestead).

**Comment by nodiscc** [comment]
Closing for reasons stated by evaryont, and also reasons similar to #1213:

> I know we have not set very strict quality/scope guidelines but going this way we could also add the thousands of ansible roles/chef cookbooks and custom install/bootstrap scripts found all over github.

>Not to detract anything from aenigma, I think it is good that such automation/setup projects exist (I myself have https://github.com/nodiscc/srv01), I just think that they should not be added to the list. Some exceptions were made - for example sovereign, or Mailinabox which do more or less the same thing, but had a lot of work going into them, and are also more complex.

>I hope that didn't sound rude. The list is already quite big and the question of curation was brought up multiple times. We just don't have any real curation guidelines.

**Comment by axeloz** [comment]
No problem, I get it. Thanks

**Pull request closed without merging**
